TrainerHubPackage/main/default/objects/Coding_Assessment__c/Coding_Assessment__c.object-meta.xml
<CustomObject>
    <label>Coding Assessment</label>
    <nameField>
        <displayFormat>CASS-{0000}</displayFormat>
        <label>Coding Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coding Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Coding_Assessment__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Coding Assessments</relationshipLabel>
    <relationshipName>Coding_Assessments</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Apex_Test_Result__c/Hero_Apex_Test_Result__c.object-meta.xml
<CustomObject>
    <label>Hero Apex Test Result</label>
    <nameField>
        <displayFormat>Test-{0000}</displayFormat>
        <label>Hero Apex Test Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Apex Test Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Hero_Apex_Test_Result__c/fields/Coding_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Coding_Assessment__c</fullName>
    <label>Coding Assessment</label>
    <referenceTo>Coding_Assessment__c</referenceTo>
    <relationshipLabel>Hero Apex Test Results</relationshipLabel>
    <relationshipName>Hero_Apex_Test_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CorePackage/main/default/objects/Titan__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Technology for the Titan in Trial of The Titan</description>
    <label>Technology</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <description>Technologies in the Trial of The Titans</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

TrainerHubPackage/main/default/classes/HeroResultPageController_Test.cls
@isTest
private class HeroResultPageController_Test {

   
    @TestSetup
    static void makeData(){
        Account acc = new Account(Name = 'Gladius Maximus');
        insert acc;

        Titan__c titan = new Titan__c();
        titan.Name = 'test titan';
        titan.Technology__c = 'Salesforce';
        insert titan;

        Exam__c[] examList = new List<Exam__c>();
        for (Integer i = 0; i < 200; i++) {
            Exam__c exam = new Exam__c();
            exam.Name = 'myExam';
            exam.Titan__c = titan.Id;
            examList.add(exam);
        }
        insert examList;

        Exam_Result__c[] resultList = new List<Exam_Result__c>();
        for (Integer i = 0; i < 200; i++) {
            Exam_Result__c result = new Exam_Result__c();
            result.Exam__c = examList[i].Id;
            result.Account__c = acc.Id;
            resultList.add(result);
        }
        insert resultList;
        // system.debug([SELECT Name, Exam__c, Account__r.Name from Exam_Result__c]);
        // Code Assessment Section
        Coding_Assessment__c[] codeList = new List<Coding_Assessment__c>();
        for (Integer i = 0; i < 200; i++) {
            Coding_Assessment__c codeAssess = new Coding_Assessment__c();
            
            codeAssess.Titan__c= titan.Id;
            codeList.add(codeAssess);
        }
        insert codeList;
        
        Hero_Apex_Test_Result__c[] cResultList= new List <Hero_Apex_Test_Result__c>();
        for (Integer i=0; i<200; i++){
            Hero_Apex_Test_Result__c car= new Hero_Apex_Test_Result__c();
            car.Coding_Assessment__c = codeList[i].Id;
            
            //car.Code_Assessment_Result_To_Account__c = acc.Id;
            cResultList.add(car);
        }
        insert cResultList;
    }
    @isTest
    static void getResultListTest() {
        Test.startTest();
        Exam_Result__c[] resultList = HeroResultPageController.getResultList();
        Test.stopTest();
        system.assertEquals(200, resultList.size());
    }
    @isTest
    static void getCodeAssessmentResultListTest(){
        Test.startTest();
        List<Id> cResultsList = HeroResultPageController.retrieveResults();
        Test.stopTest();
        system.assertEquals(200, cResultsList.size());
    }
    // Titan Section
    @isTest
    static void getTitanListTest() {
        Test.startTest();
        List<String> str = HeroResultPageController.getTitanList();
        Test.stopTest();
        system.assertEquals('test titan', str[0]);
    }
}