TrainerHubPackage/main/default/objects/Coding_Assessment__c/Coding_Assessment__c.object-meta.xml
<CustomObject>
    <label>Coding Assessment</label>
    <nameField>
        <displayFormat>CASS-{0000}</displayFormat>
        <label>Coding Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coding Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Coding_Assessment__c/fields/Percent_Passed__c.field-meta.xml
<CustomField>
    <fullName>Percent_Passed__c</fullName>
    <formula>Passed__c / (Failed__c +  Passed__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Percent Passed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

TrainerHubPackage/main/default/classes/CodingExamListController.cls
////////////////////////////////////////////////////
//
//  Name: Exam Results Apex Controller
//  Author: Joshua Faaborg
//  Description: Controller for Coding Exam List Component
//               to be able to disply data from org 
//               on the component about Coding Exam Results
//               from each hero
//
////////////////////////////////////////////////////
public with sharing class CodingExamListController {
	@AuraEnabled
    public static List<Coding_Assessment__c> CodingExamList(String cohortId) {
        List<Coding_Assessment__c> testResult = [Select Name, Percent_Passed__c
                                                     From Coding_Assessment__c];
        return testResult;

    }
 
}