TrainerHubPackage/main/default/objects/Coding_Assessment__c/Coding_Assessment__c.object-meta.xml
<CustomObject>
    <label>Coding Assessment</label>
    <nameField>
        <displayFormat>CASS-{0000}</displayFormat>
        <label>Coding Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Coding Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Coding_Assessment__c/fields/Passed__c.field-meta.xml
<CustomField>
    <fullName>Passed__c</fullName>
    <label>Passed</label>
    <summaryFilterItems>
        <field>Hero_Apex_Test_Result__c.Passed__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Hero_Apex_Test_Result__c.Coding_Assessment__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Apex_Test_Result__c/Hero_Apex_Test_Result__c.object-meta.xml
<CustomObject>
    <label>Hero Apex Test Result</label>
    <nameField>
        <displayFormat>Test-{0000}</displayFormat>
        <label>Hero Apex Test Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Apex Test Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Hero_Apex_Test_Result__c/fields/Coding_Assessment__c.field-meta.xml
<CustomField>
    <fullName>Coding_Assessment__c</fullName>
    <label>Coding Assessment</label>
    <referenceTo>Coding_Assessment__c</referenceTo>
    <relationshipLabel>Hero Apex Test Results</relationshipLabel>
    <relationshipName>Hero_Apex_Test_Results</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Apex_Test_Result__c/fields/Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Method_Name__c</fullName>
    <label>Method Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

TrainerHubPackage/main/default/objects/Hero_Apex_Test_Result__c/fields/Passed__c.field-meta.xml
<CustomField>
    <fullName>Passed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Passed</label>
    <type>Checkbox</type>
</CustomField>

TrainerHubPackage/main/default/classes/TrialOfTheTitansAPI.cls
@RestResource(urlMapping='/code-assessment/results')
global class TrialOfTheTitansAPI {
    
    global class TestResult{
        global String outcome;
        global String methodName;
    }
    
    global class TestResultsJSON{
        global List<TestResult> resultList;
        
        global TestResultsJSON(){
            resultList = new List<TestResult>();
        }
    }
    
    @HttpPut
    global static String sendResults(List<TestResult> resultList){
        
        system.debug(resultList);
        
        Coding_Assessment__c newAssessment = new Coding_Assessment__c();
        
        try{
            insert newAssessment;
        } catch (Exception e) {
            system.debug(e.getMessage());
        }
        
        List<Hero_Apex_Test_Result__c> newResults = new List<Hero_Apex_Test_Result__c>();
        
        for(TestResult tr : resultList){
            Hero_Apex_Test_Result__c t = new Hero_Apex_Test_Result__c();
            t.Coding_Assessment__c = newAssessment.id;
            t.Method_Name__c = tr.methodName;
            t.Passed__c = tr.outcome.equals('Pass');
            newResults.add(t);
        }
        
        /*List<Test_Result__c> newResults = new List<Test_Result__c>();
        
        for(TestResult tr : resultList){
            Test_Result__c t = new Test_Result__c();
            t.Method__c = tr.methodName;
            t.Pass__c = tr.outcome;   
            newResults.add(t);
        }
        
        
        
        //Test_Result__c t = new Test_Result__c();
        //t.Method__c = 'testing...';
        ///*/
        system.debug(newResults);
        
        
        try{
            //insert t;
            insert newResults;
        }
        catch (Exception e){
            system.debug(e.getMessage());
        }
        
        return 'testing...';
    }
}