TrialoftheTitansPackage/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Assessment object for 1-on-1s, projects, and misc.</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>a check box indicating if a cohort is active or not</description>
    <label>Currently Active</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Assessment__c/Hero_Assessment__c.object-meta.xml
<CustomObject>
    <label>Hero Assessment</label>
    <nameField>
        <displayFormat>HA-{0000}</displayFormat>
        <label>Hero Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Hero_Assessment__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <description>Relating Hero Assessment to Assessment</description>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Hero Assessments</relationshipLabel>
    <relationshipName>Hero_Assessments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/QC_Question_Answer__c.object-meta.xml
<CustomObject>
    <label>QC Question Answer</label>
    <nameField>
        <displayFormat>QCA-{000000}</displayFormat>
        <label>QC Question Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QC Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <description>The QC interview this question/answer data were a part of.</description>
    <inlineHelpText>The QC interview this set of questions and answers are a part of.</inlineHelpText>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>QC Question Answers</relationshipLabel>
    <relationshipName>QC_Question_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/classes/AssessmentSetupTest.cls
/////////////////////////////////////////////////////
//
//  Name: AssessmentSetupTest
//  Author: Kameron Fincher
//  Description: Utility class to create new data for 
//	the Cohort Page and Trainer Hub. It is ideal to 
//	run UserAccountSetup.UserSetup prior to this.
//	It's also best to run Setup first, then associateCohort
//	and finally QCSetup
//	
///////////////////////////////////////////////////
@isTest
public class AssessmentSetupTest {
	@testSetup
    static void Setup(){
    	UserAccountSetup.UserSetUp();
    }
    
    @isTest
    static void OverallTest(){
        AssessmentSetup.Setup();
        List<Hero_Assessment__c> heroAssessmentList = [SELECT Name FROM Hero_Assessment__c];
        List<Assessment__c> assessmentList = [SELECT Name FROM Assessment__c];
        System.assertNotEquals(0, heroAssessmentList.size());
        System.assertNotEquals(0, assessmentList.size());
        System.assertEquals(25, heroAssessmentList.size());
        System.assertEquals(5, assessmentList.size());
        
        AssessmentSetup.associateCohort();
        
        Cohort__c coh = [Select Name, Active__c from Cohort__c WHERE Active__c=true LIMIT 1];
        
        System.assertNotEquals(null,coh);
        
        AssessmentSetup.QCSetup('QC');
        
        List<QC_Question_Answer__c> QCQuesAns = [SELECT Name from QC_Question_Answer__c];
        List<QC_Interview__c> QCInt = [SELECT Name from QC_Interview__c];
        
        System.assertEquals(25, heroAssessmentList.size());
        System.assertEquals(5, assessmentList.size());
    }
    
}