TrialoftheTitansPackage/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Assessment object for 1-on-1s, projects, and misc.</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Assessment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Assessment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Misc</fullName>
                <default>true</default>
                <label>Misc</label>
            </value>
            <value>
                <fullName>1-on-1</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrainerHubPackage/main/default/classes/AssessmentListController.cls
////////////////////////////////////////////////////
//
//  Name: Assessment Apex Controller
//  Author: Josue Cisneros
//  Description: Controller for Assessment List 
//               Component to be able to disply data
//               from org on the component about each
//               Assessment
//
////////////////////////////////////////////////////

public with sharing class AssessmentListController {
    @AuraEnabled
    public static List<Assessment__c> AssessmentList(){
        List<Assessment__c> assessmentResultSearch = [SELECT Name, Type__c FROM Assessment__c];
        return assessmentResultSearch;
    }
}