TrialoftheTitansPackage/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Assessment object for 1-on-1s, projects, and misc.</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Assessment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Assessment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Misc</fullName>
                <default>true</default>
                <label>Misc</label>
            </value>
            <value>
                <fullName>1-on-1</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/classes/AssementListControllerTest.cls
////////////////////////////////////////////////////
//
// Name: Assessment List Apex Controller Test
// Author: Josue Cisneros
// Description: Test the SOQL server side controller
//              for retrieving Assessment data
//
////////////////////////////////////////////////////

@isTest
private class AssementListControllerTest {

    @isTest
    private static void TestPositive(){
        List<Assessment__c> listOfAssessments= new List<Assessment__c>();
        Assessment__c a;
        for(Integer i=0;i<10;i++){
            a = new Assessment__c(Name='Testing'+string.valueof(i), Type__c='Project');
            listOfAssessments.add(a);
        }
        for(Integer i=10;i<20;i++){
            a = new Assessment__c(Name='Testing'+string.valueof(i), Type__c='1-on-1');
            listOfAssessments.add(a);
        } for(Integer i=20;i<30;i++){
            a = new Assessment__c(Name='Testing'+string.valueof(i), Type__c='Misc');
            listOfAssessments.add(a);
        }

        insert listOfAssessments;

        List<Assessment__c> listOfAssessmentsTest = AssessmentListController.AssessmentList();
        System.assert( listOfAssessmentsTest != null); 


    }

    @isTest
    private static void TestNegative(){

        List<Assessment__c> listOfAssessments= AssessmentListController.AssessmentList();
        System.assert( listOfAssessments.isEmpty(), true); 
    }
}