PortfolioPackage/main/default/objects/About_Me_Record__c/About_Me_Record__c.object-meta.xml
<CustomObject>
    <label>About Me Record</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>About Me Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>About Me Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PortfolioPackage/main/default/objects/About_Me_Record__c/fields/About_Me__c.field-meta.xml
<CustomField>
    <fullName>About_Me__c</fullName>
    <label>About Me</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

PortfolioPackage/main/default/objects/About_Me_Record__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>About_Me_Records</relationshipName>
    <type>Lookup</type>
</CustomField>

CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Date_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Issued__c</fullName>
    <label>Date Issued</label>
    <type>Date</type>
</CustomField>

PortfolioPackage/main/default/objects/Certification__c/fields/List_Label__c.field-meta.xml
<CustomField>
    <fullName>List_Label__c</fullName>
    <formula>Name &amp; &quot; -- &quot; &amp; TEXT(Date_Issued__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>List Label</label>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Curriculum__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technology</label>
    <referenceTo>Technology__c</referenceTo>
    <relationshipLabel>Curricula</relationshipLabel>
    <relationshipName>Curricula</relationshipName>
    <type>Lookup</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PortfolioPackage/main/default/classes/UserInfoReadOnlyHelper.cls
/**
Created by Theodore Moore @Theodore#1829 on Discord


Helper class for Read only Portfolio 
Needs to be combined with the normal one
All components in normal one rely on the user being 
the owner of portfolio, this helper is to prevent it from being seen in that context

*/

public without sharing class UserInfoReadOnlyHelper {
    @AuraEnabled(cacheable=true)
        /**
        Grabs the user info based on input of userID string
    */
    public static User getBasicUserInfo(String uid) {
    Id userID = Id.valueOf(uid.substring(0,18));
        return [
            SELECT Id,FirstName,LastName,FullPhotoUrl 
            FROM User
            WHERE Id =: userID 
            LIMIT 1
        ][0];
    }
    //Grabs certifications based on userID input
    @AuraEnabled(cacheable=true)
    public static List<Certification__c> getCertifications(String uid) {


        Id userID = Id.valueOf(uid.substring(0,18));
        return [
            SELECT Id,Date_Issued__c,Name,List_Label__c 
            FROM Certification__c
            WHERE User__c =: userID
        ];
    }
    //Grabs Technologies based on userID input
    @AuraEnabled(cacheable=true)
    public static Curriculum__c getTechInfo(String uid){
        Id userID = Id.valueOf(uid.substring(0,18));
        User conObj = [SELECT name,ContactId,Id FROM User WHERE Id=: userID LIMIT 1];
        id conId = conObj.ContactId;
        Contact accObj = [SELECT name,AccountId,Id FROM Contact WHERE Id=: conId LIMIT 1];
        id accId = accObj.AccountId;
        Account curObj = [SELECT name,Curriculum__c,Id FROM Account WHERE Id=: accId LIMIT 1];
        id curId = curObj.Curriculum__c;
        return [ SELECT name,Technology__c,Id FROM Curriculum__c WHERE Id=: curId LIMIT 1];

    }
    //grabs about me based on userID record
    @AuraEnabled(cacheable=true) 
    public static List<About_Me_Record__c> getAboutMeRecord(String uid){
        Id userID = Id.valueOf(uid.substring(0,18));

        List<About_Me_Record__c> aboutMeRecord = new List<About_Me_Record__c>();
        
        aboutMeRecord = [SELECT  About_Me__c, User__c  //Add User__c
                         FROM About_Me_Record__c 
                         WHERE User__c = :userID
                        ];
             
             return aboutMeRecord;
         }
}