TrialoftheTitansPackage/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Feedback__c/fields/Fluence__c.field-meta.xml
<CustomField>
    <fullName>Fluence__c</fullName>
    <label>Fluency</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Mock_Interview_Self__c.field-meta.xml
<CustomField>
    <fullName>Mock_Interview_Self__c</fullName>
    <label>Mock Interview Self</label>
    <referenceTo>Mock_Interview_Self__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/MI_Question_Pool__c/MI_Question_Pool__c.object-meta.xml
<CustomObject>
    <label>MI Question Pool</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MI Question Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Mock_Interview_Self__c/Mock_Interview_Self__c.object-meta.xml
<CustomObject>
    <label>Mock Interview Self</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mock Interview Selves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P3/force-app/main/default/objects/Mock_Interview_Self__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mock Interview Selves</relationshipLabel>
    <relationshipName>Mock_Interview_Selves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

P3/force-app/main/default/objects/Mock_Interview_Self__c/fields/MI_Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>MI_Question_Pool__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MI Question Pool</label>
    <referenceTo>MI_Question_Pool__c</referenceTo>
    <relationshipLabel>Mock Interview Selves</relationshipLabel>
    <relationshipName>Mock_Interview_Selves3</relationshipName>
    <type>Lookup</type>
</CustomField>

P3/force-app/main/default/classes/MockInterviewDataFactory.cls
/////////////////////////////////////////////////////////////////////////////
//
//	Name: MockInterviewHubDataFactory
//	Author: Camron Miller
//	Description: Creates data for testing functionality related to the
//				 Mock interview Package.
//
/////////////////////////////////////////////////////////////////////////////

public class MockInterviewDataFactory 
{
    public static void dataFactory()
    {
        // create 10 new accounts and add them to the org
        // only filling in the required fields
        List<Account> testAccounts = new List<Account>();
        for(integer i = 0; i < 10; i++)
        {
            testAccounts.add(new Account(Name = 'Test Account #' + (i + 1)));
        }
        insert testAccounts; 

        // create 5 mock interview self records for each account, 50 total
        // only filling in the required fields
        List<Mock_Interview_Self__c> testMockInterviews = new List<Mock_Interview_Self__c>();
        for(Account a : testAccounts)
        {
            for(integer i = 0; i < 5; i++)
            {
                testMockInterviews.add(new Mock_Interview_Self__c(Account__c = a.Id));
            }
        }
        insert testMockInterviews;

        // create 2 feedback records for each mock interview self
        // only filling in the required fields
        List<Feedback__c> testFeedbacks = new List<Feedback__c>();
        for(Mock_Interview_Self__c m : testMockInterviews)
        {
            for(integer i = 0; i < 2; i++)
            {
                testFeedbacks.add(new Feedback__c(Mock_Interview_Self__c = m.Id, Fluence__c = i));
            }
        }
        insert testFeedbacks;

        // create 10 mock interview pools
        // only filling in the required fields
        List<MI_Question_Pool__c> testMIQuestionPools = new List<MI_Question_Pool__c>();
        for(integer i = 0; i < 10; i++)
        {
            testMIQuestionPools.add(new MI_Question_Pool__c());
        }
        insert testMIQuestionPools; 
    }
}