HeroHubPackage/main/default/objects/Equivalency__c/Equivalency__c.object-meta.xml
<CustomObject>
    <label>Equivalency</label>
    <nameField>
        <label>Equivalency</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equivalencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HeroHubPackage/main/default/objects/Equivalency__c/fields/Skill_Equivalency__c.field-meta.xml
<CustomField>
    <fullName>Skill_Equivalency__c</fullName>
    <label>Skill Equivalency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Equivalencies</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/classes/lwcPortFolioIndustryEquivs.cls
public with sharing class lwcPortFolioIndustryEquivs {

    //returns any records to the javascript controller for each item to be iterated upon.
    @AuraEnabled(cacheable=true)
    public static List<Equivalency__c> returnSkillNames() {
        Id UserId = UserInfo.getUserid();
        List<Equivalency__c> PortSkill = [SELECT Name, Skill_Equivalency__c FROM Equivalency__c WHERE User__c =:UserId LIMIT 5];
        
        //fill in default data if the returned list is empty.
        if(PortSkill.isEmpty()){
            for(integer i=0; i<5; i++){
                PortSkill.add(new Equivalency__c(
                    Name = 'Skill No. '+i,
                    Skill_Equivalency__c = i + 6));
            }
        }
        return PortSkill;
    }
}