ExamPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <!--actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Exam_Record_Page1</content>
        <formFactor>Small</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
    </actionOverrides-->
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ExamPackage/main/default/classes/ExamResultTriggerHandler.cls
//////////////////////////////////////////
//
//Name: ExamResultTriggerHandler
//Author: Abdul-Shahid Wali
//Date Created: 05/26/21
//Date Updated: 05/28/21
//Description: Handler class for the ExamResultTrigger trigger
//
//////////////////////////////////////////
//
public class ExamResultTriggerHandler {
    
    //Prevents new Exam Result objects from being created if that exam has already been assigned
    //newResults: all exam results that have been newly inserted or updated
    public static void PreventDuplicateExams(List<Exam_Result__c> newResults){
        //Get all Exam Result objects in the database
        List<Exam_Result__c> allResults = [SELECT Account__c, Exam__c, Status__c FROM Exam_Result__c];
        //Compare the newly inserted or update results against each other
        for(Integer i = 0; i < newResults.size(); i++){
            for(Integer k = newResults.size() - 1; k >= 0; k--){
                if((newResults[i].Account__c == newResults[k].Account__c) && (newResults[i].Exam__c == newResults[k].Exam__c) && (newResults[i].Status__c == 'Assigned') && (newResults[k].Status__c == 'Assigned') && (i != k)){
                    //If multiple of the same exam is assgined at once, only assign 1 and unassgined the others
               		newResults[k].Status__c = 'Unassigned';  
            	}
            }
        }
        //Compare the newly inserted or updated results against all results
        for(Exam_Result__c nr: newResults){
            for(Exam_Result__c ar: allResults){
                if((nr.Account__c == ar.Account__c) && (nr.Exam__c == ar.Exam__c) && (nr.Status__c == 'Assigned') && (ar.Status__c == 'Assigned') && (ar.Id != nr.Id)){
                    //If a new exam has already been assigned, set its status to unassigned
                    nr.Status__c = 'Unassigned';
                }
            }
        }
        
        
    }

}