ExamPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <!--actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Exam_Record_Page1</content>
        <formFactor>Small</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
    </actionOverrides-->
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Pool_Assignment__c/Exam_Pool_Assignment__c.object-meta.xml
<CustomObject>
    <label>Exam Pool Assignment</label>
    <nameField>
        <displayFormat>EP-{0000}</displayFormat>
        <label>Exam Pool Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Pool Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Pool_Assignment__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipName>Exam_Pools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ExamPackage/main/default/objects/Exam_Pool_Assignment__c/fields/Number_to_pull__c.field-meta.xml
<CustomField>
    <fullName>Number_to_pull__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Number to pull</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Pool_Assignment__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Question_Pool__c</referenceTo>
    <relationshipName>Exam_Pools</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/Exam_Question__c.object-meta.xml
<CustomObject>
    <label>Exam Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Question__c/fields/Correct_Answer_s__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer_s__c</fullName>
    <label>Correct Answer(s)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <label>Options</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ExamPackage/main/default/objects/Question_Assignment__c/Question_Assignment__c.object-meta.xml
<CustomObject>
    <label>Question Assignment</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Question Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Question_Assignment__c/fields/Exam_Question__c.field-meta.xml
<CustomField>
    <fullName>Exam_Question__c</fullName>
    <label>Exam Question</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Question Assignments</relationshipLabel>
    <relationshipName>Question_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Assignment__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Question_Pool__c</referenceTo>
    <relationshipLabel>Question Assignments</relationshipLabel>
    <relationshipName>Question_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Pool__c/Question_Pool__c.object-meta.xml
<CustomObject>
    <label>Question Pool</label>
    <nameField>
        <label>Question Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Question_Pool__c/fields/Number_Of_Questions__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Questions__c</fullName>
    <label>Number Of Questions</label>
    <summaryForeignKey>Question_Assignment__c.Question_Pool__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Question_Pool__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Question Pool</relationshipLabel>
    <relationshipName>Question_Pools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/classes/ExamCreationAuraController.cls
public class ExamCreationAuraController {
    
    public class QuestionPoolWrapper{
        @AuraEnabled
        public Id poolId {get; set;}
        @AuraEnabled
        public Integer quantity {get; set;}
        @AuraEnabled
        public String poolName {get; set;}
        @AuraEnabled
        public Double poolQuestionAmount {get; set;}
        
        public QuestionPoolWrapper(Id i, String n, Decimal a){
            poolId = i;
            quantity = 0;
            poolName = n;
            poolQuestionAmount = a;
        }
    }
    @AuraEnabled
    public static Map<Integer, List<QuestionPoolWrapper>> getQuestionPool(String searchKeyword){
        // Searchkey is null
        String searchkey= String.isBlank (searchKeyword) ? '%%' : '%'+searchKeyword+'%';
        
        Map<Integer,List<QuestionPoolWrapper>> qpm = new Map<Integer, List<QuestionPoolWrapper>>();
        List<QuestionPoolWrapper> qpw = new List<QuestionPoolWrapper>();
        Integer counter = 1;
        Integer pageNumber = 1;
        for(Question_Pool__c qp: [SELECT Id, Name, Number_Of_Questions__c FROM Question_Pool__c WHERE Name LIKE : searchkey]){
            qpw.add(new QuestionPoolWrapper(qp.Id, qp.Name, qp.Number_Of_Questions__c));
            if(counter == 10){
                qpm.put(pageNumber, qpw);
                pageNumber++;
                qpw = new List<QuestionPoolWrapper>();
            }
            counter++;
        }
        if(!qpw.isEmpty()){
            qpm.put(pageNumber, qpw);
        }
        return qpm;
    }
    
    @AuraEnabled
    public static List<Exam_Question__c> getExamQuestions(Id poolId){
        List<Exam_Question__c> eql  = new List<Exam_Question__c>();
        for(Question_Assignment__c qp: [SELECT Id, Question_Pool__c, 
                                        Exam_Question__r.Name, Exam_Question__r.Correct_Answer_S__c, Exam_Question__r.Question_Text__c, Exam_Question__r.Options__c
                                  		FROM Question_Assignment__c 
                                        WHERE Question_Pool__c = :poolId]){
            eql.add(new Exam_Question__c(Name = qp.Exam_Question__r.Name, 
                                         Correct_Answer_s__c = qp.Exam_Question__r.Correct_Answer_S__c,
                                         Question_Text__c = qp.Exam_Question__r.Question_Text__c,
                                         Options__c = qp.Exam_Question__r.Options__c
                                        )
                   );
        }
        return eql;
    }
    
    @AuraEnabled
    public static void createExamAssignment(String examId, Map<Id, Integer> poolAndNumber){
        List<Exam_Pool_Assignment__c> eal = new List<Exam_Pool_Assignment__c>();
        for(String key: poolAndNumber.keyset()){
            eal.add(new Exam_Pool_Assignment__c(Exam__c = examId, Question_Pool__c = key, Number_to_pull__c = poolAndNumber.get(key)));
        }
        insert eal;
    }
}