ExamPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <!--actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Exam_Record_Page1</content>
        <formFactor>Small</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
    </actionOverrides-->
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Pool_Assignment__c/Exam_Pool_Assignment__c.object-meta.xml
<CustomObject>
    <label>Exam Pool Assignment</label>
    <nameField>
        <displayFormat>EP-{0000}</displayFormat>
        <label>Exam Pool Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Pool Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Pool_Assignment__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipName>Exam_Pools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ExamPackage/main/default/objects/Exam_Pool_Assignment__c/fields/Number_to_pull__c.field-meta.xml
<CustomField>
    <fullName>Number_to_pull__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Number to pull</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Pool_Assignment__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Question_Pool__c</referenceTo>
    <relationshipName>Exam_Pools</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/Exam_Question__c.object-meta.xml
<CustomObject>
    <label>Exam Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

ExamPackage/main/default/objects/Hero_Answer__c/Hero_Answer__c.object-meta.xml
<CustomObject>
    <label>Hero Answer</label>
    <nameField>
        <displayFormat>HA-{0}</displayFormat>
        <label>Hero Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Hero_Answer__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Correct</label>
    <type>Checkbox</type>
</CustomField>

ExamPackage/main/default/objects/Hero_Answer__c/fields/Exam_Question__c.field-meta.xml
<CustomField>
    <fullName>Exam_Question__c</fullName>
    <label>Exam Question</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Hero Answers</relationshipLabel>
    <relationshipName>Hero_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Hero_Answer__c/fields/Exam_Result__c.field-meta.xml
<CustomField>
    <fullName>Exam_Result__c</fullName>
    <label>Exam Result</label>
    <referenceTo>Exam_Result__c</referenceTo>
    <relationshipLabel>Hero Answers</relationshipLabel>
    <relationshipName>Hero_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Assignment__c/Question_Assignment__c.object-meta.xml
<CustomObject>
    <label>Question Assignment</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Question Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Question_Assignment__c/fields/Exam_Question__c.field-meta.xml
<CustomField>
    <fullName>Exam_Question__c</fullName>
    <label>Exam Question</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Question Assignments</relationshipLabel>
    <relationshipName>Question_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Assignment__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Question_Pool__c</referenceTo>
    <relationshipLabel>Question Assignments</relationshipLabel>
    <relationshipName>Question_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Pool__c/Question_Pool__c.object-meta.xml
<CustomObject>
    <label>Question Pool</label>
    <nameField>
        <label>Question Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Question_Pool__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Question Pool</relationshipLabel>
    <relationshipName>Question_Pools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/classes/ExamResultsPoolPageController.cls
public with sharing class ExamResultsPoolPageController {
    //Grab all question for a given Exam result
    @AuraEnabled
    public static List<Exam_Pool_Assignment__c> getExamResultPools(/*Id examId */){

        //List<Exam_Pool_Assignment__c> epa = new List<Exam_Pool_Assignment__c>();

    /*  List<Exam__c> eql  =  [SELECT Id, Name, 
        (SELECT Question_Pool__c FROM Exam_Pools__r) 
        FROM Exam__c WHERE Id IN 
        (SELECT Exam__c FROM Exam_Pool_Assignment__c WHERE Exam__c = 'a085e000000GfC5AAK')];
        System.debug(eql);
    */
        List<Exam_Pool_Assignment__c> epa = [SELECT Name, Exam__c, Number_to_pull__c, Question_Pool__c, Question_Pool__r.Name
                                            FROM Exam_Pool_Assignment__c 
                                            WHERE Exam__c = 'a085e000000GfC5AAK'];
                                            System.debug(epa);

        
        
        return epa;
    }

    public static void getExamResultAnswers(Id examResultsId, Id examId){

        

        /*List<Hero_Answer__c> hal = [SELECT Name, Exam_Question__c, Correct__c
                                    FROM Hero_Answer__c
                                    WHERE Exam_Result__c = :examResultsId];
                                    return hal;*/
        List<Question_Assignment__c> qal = new List<Question_Assignment__c>();

        for(Hero_Answer__c hal : [SELECT Name, Exam_Question__c, Correct__c
                                    FROM Hero_Answer__c
                                    WHERE Exam_Result__c = :examResultsId]){

        String examQuestion = hal.Exam_Question__c;

            for(Question_Assignment__c qa : [SELECT Question_Pool__c, Question_Pool__r.Name
            FROM Question_Assignment__c 
            WHERE Exam_Question__c = :examQuestion]){

               // qal.add(new Question_Assignment__c(Exam_Question__c = ));

            }

            }
                                   
    }

}