ExamPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <!--actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Exam_Record_Page1</content>
        <formFactor>Small</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
    </actionOverrides-->
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam__c/fields/Default_Passing_Grade__c.field-meta.xml
<CustomField>
    <fullName>Default_Passing_Grade__c</fullName>
    <label>Default Passing Grade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

ExamPackage/main/default/objects/Exam__c/fields/Default_Time_Limit__c.field-meta.xml
<CustomField>
    <fullName>Default_Time_Limit__c</fullName>
    <label>Default Time Limit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Pool_Assignment__c/Exam_Pool_Assignment__c.object-meta.xml
<CustomObject>
    <label>Exam Pool Assignment</label>
    <nameField>
        <displayFormat>EP-{0000}</displayFormat>
        <label>Exam Pool Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Pool Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Pool_Assignment__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipName>Exam_Pools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Pool_Assignment__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Question_Pool__c</referenceTo>
    <relationshipName>Exam_Pools</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/Exam_Question__c.object-meta.xml
<CustomObject>
    <label>Exam Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

ExamPackage/main/default/objects/Hero_Answer__c/Hero_Answer__c.object-meta.xml
<CustomObject>
    <label>Hero Answer</label>
    <nameField>
        <displayFormat>HA-{0}</displayFormat>
        <label>Hero Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Hero_Answer__c/fields/Exam_Question__c.field-meta.xml
<CustomField>
    <fullName>Exam_Question__c</fullName>
    <label>Exam Question</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Hero Answers</relationshipLabel>
    <relationshipName>Hero_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Hero_Answer__c/fields/Exam_Result__c.field-meta.xml
<CustomField>
    <fullName>Exam_Result__c</fullName>
    <label>Exam Result</label>
    <referenceTo>Exam_Result__c</referenceTo>
    <relationshipLabel>Hero Answers</relationshipLabel>
    <relationshipName>Hero_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Assignment__c/Question_Assignment__c.object-meta.xml
<CustomObject>
    <label>Question Assignment</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Question Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Question_Assignment__c/fields/Exam_Question__c.field-meta.xml
<CustomField>
    <fullName>Exam_Question__c</fullName>
    <label>Exam Question</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Question Assignments</relationshipLabel>
    <relationshipName>Question_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Assignment__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Question_Pool__c</referenceTo>
    <relationshipLabel>Question Assignments</relationshipLabel>
    <relationshipName>Question_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Flow_Helper__c/Question_Flow_Helper__c.object-meta.xml
<CustomObject>
    <label>Question Flow Helper</label>
    <nameField>
        <label>Flow Helper Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Flow Helpers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Question_Pool__c/Question_Pool__c.object-meta.xml
<CustomObject>
    <label>Question Pool</label>
    <nameField>
        <label>Question Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Question_Pool__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Question Pool</relationshipLabel>
    <relationshipName>Question_Pools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/classes/ExamDataFactory1.cls
/////////////////////////////////////////////////////////////////////////////
//
//	Name: ExamDataFactory1
//	Authors: Matthew Nicholson and Omer Sade
//	Description: Creates data for testing functionality related to the
//				 Exam app.
//
/////////////////////////////////////////////////////////////////////////////



public class ExamDataFactory1{
    // Creates an exam with 20 questions and a question assignment for each question.
    // Each question can be assigned to the question pool.
    // Every question has an answer and every exam has a result.  
    public static void dataFactory(String examName, String questionPool, Integer timeLimit, Integer passingGrade) {
        Exam__c examTest = new Exam__c(Name = examName, Default_Time_Limit__c = timeLimit, Default_Passing_Grade__c = passingGrade);
        insert examTest;
        Exam_Result__c examResultTest = new Exam_Result__c();
        insert examResultTest;
        Question_Pool__c questionPoolTest = new Question_Pool__c(Name=questionPool);
        insert questionPoolTest;
        Exam_Pool_Assignment__c poolTest = new Exam_Pool_Assignment__c(Exam__c = examTest.Id, Question_Pool__c=questionPoolTest.Id);
        insert poolTest;
        List<Exam_Question__c> questionList = new List<Exam_Question__c>();
        for(Integer i=0; i<20;i++){
            Exam_Question__c examQuestionTest = new Exam_Question__c(Name='Test' + i);
            questionList.add(examQuestionTest);
        }
        insert questionList;
        List<Hero_Answer__c> answerList = new List<Hero_Answer__c>();
        for(Integer j=0;j<20;j++){
            Hero_Answer__c heroAnswerTest = new Hero_Answer__c(Exam_Question__c=questionList[j].Id, Exam_Result__c=examResultTest.Id);
            answerList.add(heroAnswerTest);
        }
        insert answerList;
        List<Question_Assignment__c> assignmentList = new List<Question_Assignment__c>();
        for(Integer k=0;k<20;k++){
            Question_Assignment__c questionAssignmentTest = new Question_Assignment__c(Exam_Question__c=questionList[k].Id, Question_Pool__c=questionPoolTest.Id);
            assignmentList.add(questionAssignmentTest);
        }
        insert assignmentList;
        Question_Flow_Helper__c flowTest = new Question_Flow_Helper__c(Name='Test');
        insert flowTest;
    }
}