TrialoftheTitansPackage/main/default/objects/Exam_Question__c/Exam_Question__c.object-meta.xml
<CustomObject>
    <!---->
    <label>Exam Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <label>Options</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

P3/force-app/main/default/objects/Exam_Question__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Multiple Choice</fullName>
            </value>
            <value>
                <fullName>Multiple Choice - multiple answers</fullName>
            </value>
            <value>
                <fullName>True-false</fullName>
            </value>
            <value>
                <fullName>Matching</fullName>
            </value>
            <value>
                <fullName>Numerical</fullName>
            </value>
            <value>
                <fullName>Short answer</fullName>
            </value>
            <value>
                <fullName>Essay</fullName>
            </value>
            <value>
                <fullName>Missing word</fullName>
                <isActive>false</isActive>
                <label>Missing word</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/classes/ExamQuestionTriggerHelperTest.cls
//////////////////////////////////////////
//
//Name: ExamQuestionTriggerHelperTest
//Author: Zain Hamid
//Date Created: 02/10/22
//Date Updated: 02/10/22
//Description: Test class for ExamQuestionTriggerHelper
//
//////////////////////////////////////////
//

@isTest
public with sharing class ExamQuestionTriggerHelperTest {
    public ExamQuestionTriggerHelperTest() {

    }
    private static Integer numberOfTests = 20;


    /*Schema.DescribeFieldResult fieldDetail =Exam_Question__c.Question_Type__c.getDescribe();   
    List<Schema.PicklistEntry> values = fieldDetail.getPicklistValues();
    for(Schema.PicklistEntry value: values) */

    @TestSetup
    static void setup() {
        List<Exam_Question__c> tfQuestions = new List<Exam_Question__c>();
        for(Integer i = 0; i <= numberOfTests; i++) {
            tfQuestions.add(new Exam_Question__c(Name = 'This is Test Question ' + i, Question_Type__c = 'True-False', Question_Text__c = 'This is test question ' + i + ' text.'));
        }
        insert tfQuestions;
    }
    
    @isTest
    static void tfCorrectOptionsBulk() {
        Integer successes;
        List<Exam_Question__c> allTFQuestions = [SELECT Id,Name,Question_Type__c,Question_Text__c,Options__c FROM Exam_Question__c WHERE Question_Type__c = 'True-False'];
        for(Exam_Question__c question: allTFQuestions) {
            if(question.Options__c == 'TRUE||FALSE') {
                successes++;
            }
        }

        System.assertEquals(numberOfTests, successes);
    }
}