TrialoftheTitansPackage/main/default/objects/Exam_Question__c/Exam_Question__c.object-meta.xml
<CustomObject>
    <!---->
    <label>Exam Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/Flag_Category__c.field-meta.xml
<CustomField>
    <fullName>Flag_Category__c</fullName>
    <label>Flag Categories</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Flag_Category_Picklist</valueSetName>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/Flag_Notes__c.field-meta.xml
<CustomField>
    <fullName>Flag_Notes__c</fullName>
    <description>This field is for users to add an explanation for why they flagged the question</description>
    <label>Explanation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/IsFlagged__c.field-meta.xml
<CustomField>
    <fullName>IsFlagged__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsFlagged</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/globalValueSets/Flag_Category_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Formatting</fullName>
    </customValue>
    <customValue>
        <fullName>Missing Info</fullName>
    </customValue>
    <customValue>
        <fullName>Outdated</fullName>
    </customValue>
    <customValue>
        <fullName>Text</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Flag_Category_Picklist</masterLabel>
</GlobalValueSet>

ExamInterviewPackage/main/default/classes/QuestionFlagUpdatesTest.cls
@isTest
public with sharing class QuestionFlagUpdatesTest {
   
    @isTest static void flagTest() {
      
    //System.debug('flag test has started');
    Exam_Question__c eq = new Exam_Question__c();
    eq.IsFlagged__c= false;
    eq.Flag_Category__c 	= 'Other';
    eq.Flag_Notes__c 		= ' ';

	//System.debug('new question isflagged=false created');
          
    Test.startTest();
      
          try{
              //System.debug('try block started');
              insert eq;
              //System.debug('inserted eq');
              Exam_Question__c q = new Exam_Question__c();
        
            q = [SELECT Id, IsFlagged__c, Flag_Category__c, Flag_Notes__c FROM Exam_Question__c];
                
            QuestionFlagUpdates.lookupQuestion(q.Id);
            QuestionFlagUpdates.flagQuestion(q.Id, q.Flag_Category__c, q.Flag_Notes__c);
            //System.debug('method executed successfully');
          }
       catch(exception e){
           
           //System.debug('handled exception' + e);
       }
   	
       
    Test.stopTest();
  
       
   }  
}