TrialoftheTitansPackage/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Name of the company</description>
    <label>Company</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position held at the company</description>
    <label>Position</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

P3/force-app/main/default/classes/ExperiencesController.cls
/////////////////////////////////////////////////////
//
//  Name: ExperiencesController
//  Author: Will Harris, Ethan Wilson
//  Created: 9/8/2021
//  Updated: 10/25/2021
//  Description: ExperiencesController allows for the 
//  other experiences component to communicate with the
//  database. (Edited to work with LWC)
//  
// 
//  Modified On: 10/26/2021
//  Modified By: Iteration VI
//  Description: we modified the query by adding "LIMIT 10" because
//      we have data factories that populate a great deal of records,
//      and because not all of the records need to be shown on the
//      Experience site.
//  
///////////////////////////////////////////////////
public with sharing class ExperiencesController {

    /*getExperiences() queries a list of experiences based on the user invoking it.
    userId: id of the user invoking the method. Parameter is passed on from JavaScript helper 
     -- iteration 6 removed this. idk why they just didn't use with sharing
    */
    @AuraEnabled(cacheable=true)
    public static List<Experience__c> getExperiences(){
        return [SELECT Id, Company__c, Position__c, Start_Date__c, End_Date__c 
                    FROM Experience__c LIMIT 10];

        //There could possibly be cases for when we are returning null experiences.
        //So some functionaility to throw exceptions or errors in those cases, maybe.
    }

    /*updateExperiences() updates experiences in the database
    experiences: experiences to update*/
    @AuraEnabled(cacheable=true)
    public static void updateExperiences(List<Experience__c> experiences){
        if(experiences != null){
            update experiences;
        }
    }

    /*deleteExperience() deletes experiences in the database
    experiences: experiences to delete */
    @AuraEnabled(cacheable=true)
    public static void deleteExperience(Experience__c experience){
        Database.delete(experience);
    }
}