TrialoftheTitansPackage/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Name of the company</description>
    <label>Company</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position held at the company</description>
    <label>Position</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

P3/force-app/main/default/classes/ExperienceTriggerHandlerTest.cls
/////////////////////////////////////////////////////
//
//  Name: ExperienceTriggerHandlerTest
//  Author: Will Harris
//  Created: 9/13/2021
//  Updated: 9/14/2021
//  Description: Tests that ExperienceTriggerHandler works as expected
//  
///////////////////////////////////////////////////
@isTest
private with sharing class ExperienceTriggerHandlerTest {
    public ExperienceTriggerHandlerTest() {

    }

    @isTest
    static void posSingleTest(){
        User testUser = [SELECT Id FROM User WHERE Profile.Name='System Administrator' Limit 1];

        Experience__c experience = new Experience__c(
            Company__c='Test Company',
            Position__c='Tester',
            Start_Date__c= Date.valueOf('2011-11-11'),
            End_Date__c= Date.today()
        );

        System.runAs(testUser){
            insert experience;
        }

        Experience__c actualExperience = [SELECT User__c FROM Experience__c WHERE Company__c = 'Test Company' LIMIT 1];

        //experience created should have the same user id in User__c as testUser
        System.assertEquals(testUser.Id, actualExperience.User__c);
    }
}