TrialoftheTitansPackage/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Name of the company</description>
    <label>Company</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position held at the company</description>
    <label>Position</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

PortfolioPackage/main/default/classes/GetExperienceInformation.cls
//Mohammed Azad
//Returns a list of the employment object based on the user
public with sharing class GetExperienceInformation {
    @AuraEnabled(cacheable=true)
    public static List<Experience__c> returnExperienceList() { 
        id userIdHolder = UserInfo.getUserId();
    	List <Experience__c> ExperienceList = [SELECT Company__c, Position__c, Start_Date__c, End_Date__c FROM Experience__c WHERE  User__c =: userIdHolder];
        return ExperienceList;
    }
}