TrialoftheTitansPackage/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/classes/ExperienceTriggerHandler.cls
/////////////////////////////////////////////////////
//
//  Name: ExperienceTriggerHandler
//  Author: Will Harris
//  Created: 9/13/2021
//  Updated: 9//2021
//  Description: Ensures that experiences created have a user id.
//  
///////////////////////////////////////////////////
public with sharing class ExperienceTriggerHandler {
    
    public static void checkUser(List<Experience__c> experiences){
        for(Experience__c experience : experiences){
            if(experience.User__c == null){
                experience.User__c = UserInfo.getUserId();
            }
        }
    }
}