TrialoftheTitansPackage/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <label>Assessor</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Date_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Issued__c</fullName>
    <label>Date Issued</label>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Verification_Site__c.field-meta.xml
<CustomField>
    <fullName>Verification_Site__c</fullName>
    <label>Verification Site</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Educations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/DateGraduate__c.field-meta.xml
<CustomField>
    <fullName>DateGraduate__c</fullName>
    <label>DateGraduate</label>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <label>Degree</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Major__c.field-meta.xml
<CustomField>
    <fullName>Major__c</fullName>
    <label>Major</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Educations</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/Equivalency__c.object-meta.xml
<CustomObject>
    <label>Equivalency</label>
    <nameField>
        <label>Equivalency</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equivalencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Equivalencies</relationshipLabel>
    <relationshipName>Equivalencies</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/Skill_Equivalency__c.field-meta.xml
<CustomField>
    <fullName>Skill_Equivalency__c</fullName>
    <label>Skill Equivalency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Equivalencies</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <label>Experience</label>
    <nameField>
        <label>Experience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <description>Name of the company</description>
    <label>Company</label>
    <length>45</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <description>Position held at the company</description>
    <label>Position</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Experience__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Projects listed in the Portfolio.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/Roles_Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Roles_Responsibilities__c</fullName>
    <label>Roles and Responsibilities</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/Technologies__c.field-meta.xml
<CustomField>
    <fullName>Technologies__c</fullName>
    <label>Technologies</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/classes/ShowPortfolioController.cls
public with sharing class ShowPortfolioController {
    
    @AuraEnabled
    public static List<String> GetUserList() {

        List<User> AllUsers = [SELECT Name FROM User];
        List<String> AllStringUsers = new List<String>();
        for(User Users: AllUsers){
            AllStringUsers.add(Users.Name);
        }
        return AllStringUsers;
    }
    @AuraEnabled
    public static List<Equivalency__c> EquivGet(String Hero){
        
        

        List<User> HeroIdList = [SELECT Id, Name FROM User WHERE Name =: Hero LIMIT 1];
        

        
        List<Equivalency__c> Equiv = [SELECT Name,Skill_Equivalency__c, Id FROM Equivalency__c WHERE User__c=:HeroIdList[0].Id];

        return Equiv;
  
    }
    @AuraEnabled
    public static List<Project__c> ProjectGet(String Hero){

        List<User> HeroIdList = [SELECT Id FROM User Where Name =: Hero LIMIT 1];

        List<Project__C> Proj = [SELECT Name, Description__c, Roles_Responsibilities__c, Technologies__c FROM Project__c  WHERE User__c=:HeroIdList[0].Id];
        
        for(Project__c P : Proj){
            P.Description__c = P.Description__c.replaceAll('<[/a-zAZ0-9]*>','');
            P.Roles_Responsibilities__c = P.Roles_Responsibilities__c.replaceAll('<[/a-zAZ0-9]*>','');
            P.Technologies__c = P.Technologies__c.replaceAll('<[/a-zAZ0-9]*>','');
            
        }                                                                                             
                                                                                                        
                                                                                                        
        return Proj;

    }
    @AuraEnabled
    public static List<Education__c> EducationGet(String Hero){

        List<User> HeroIdList = [SELECT Id FROM User Where Name =: Hero LIMIT 1];

        List<Education__C> Ed = [SELECT Name, Major__c, Degree__c, DateGraduate__c FROM Education__c WHERE User__c=:HeroIdList[0].Id];
                                                                                                    
        return Ed;

    }
    @AuraEnabled
    public static List<Certification__c> CertGet(String Hero){

        List<User> HeroIdList = [SELECT Id FROM User Where Name =: Hero LIMIT 1];

        List<Certification__c> Cd = [SELECT Name, Assessor__c, Verification_Site__c, Date_Issued__c FROM Certification__c WHERE User__c=:HeroIdList[0].Id];
                                                                                                    
        return Cd;

    }
    @AuraEnabled
    public static List<Experience__c> ExpGet(String Hero){

        List<User> HeroIdList = [SELECT Id FROM User Where Name =: Hero LIMIT 1];

        List<Experience__c> Exp = [SELECT Position__c,Company__c,Start_Date__c,End_Date__c FROM Experience__c WHERE User__c=:HeroIdList[0].Id];
                                                                                                    
        return Exp;

    }
}