TrialoftheTitansPackage/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Certification_Exam__c.field-meta.xml
<CustomField>
    <fullName>Certification_Exam__c</fullName>
    <label>Certification Exam</label>
    <referenceTo>Certification_Exam__c</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PortfolioPackage/main/default/objects/Certification_Exam__c/Certification_Exam__c.object-meta.xml
<CustomObject>
    <label>Certification Exam</label>
    <nameField>
        <label>Certification Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/classes/getCertificationsTest.cls
@isTest
public with sharing class getCertificationsTest {

    private static List<Certification__c> certs;
    private static List<Certification__c> certsBulk;
    private static List<Certification__c> insertCert = new List<Certification__c>();


    @TestSetup
    static void mockCertSetup(){
        Certification_Exam__c mock1 = new Certification_Exam__c();
        Contact mock2 = new Contact(firstName='Perseus', lastname='Eurymedon');

        insert mock1;
        insert mock2;
    }

    @isTest
    static void getRecord() {

        Certification__c c = new Certification__c();
        c.Certification_Exam__c = [SELECT Id FROM Certification_Exam__c LIMIT 1][0].Id;
        c.Candidate__c = [SELECT Id FROM Contact LIMIT 1][0].Id;
        //Inserts a certification into the database
        insert c;

        //Calls the method and returns the certifications to the certs variable
        certs = getCertifications.Certifications();
        //checks to see if the inserted cert is returned
        System.assert(certs.size()==1);
    }
    @isTest
    static void getRecordBulk(){

        //Creates a list of certifications to be added into the list
        String mockCertId = [SELECT Id FROM Certification_Exam__c LIMIT 1][0].Id;
        String mockCandId = [SELECT Id FROM Contact LIMIT 1][0].Id;
        for(Integer i = 0; i<10; i++)
        {
            insertCert.add(new Certification__c(
                Certification_Exam__c=mockCertId,
            Candidate__c=mockCandId));
        }
        Test.startTest();
        //inserts the list of certifications
        insert insertCert;
        //Returns all of the certifications in the database
        certsBulk = getCertifications.Certifications();
        Test.stopTest();

        System.assert(certsBulk.size()==10);
    }

    @isTest
    static void getRecordNegative(){

        //Returns all the certifications however there should not be any so an error is thrown and the result should be null
        try{
            certs = getCertifications.Certifications();
        } catch(Exception e){
            System.assert(certs==null);
        }
    }
}