TrialoftheTitansPackage/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <label>Assessor</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Date_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Issued__c</fullName>
    <label>Date Issued</label>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <label>Image URL</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Verification_Site__c.field-meta.xml
<CustomField>
    <fullName>Verification_Site__c</fullName>
    <label>Verification Site</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

PortfolioPackage/main/default/classes/getCertificationInfo.cls
public with sharing class getCertificationInfo {
    @AuraEnabled(cacheable=true)
   public static List<Certification__c> Certifications() {
        Id userIdHolder = UserInfo.getUserId();

       //Returns all of the Certifications from the database for the user
      List<Certification__c> cer= [SELECT Assessor__c, Name,Id, Verification_Site__c, Date_Issued__c, Image_URL__c FROM Certification__c WHERE  User__c =: userIdHolder];
       return cer;
   }

}