TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/Account/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Account/fields/Squad__c.field-meta.xml
<CustomField>
    <fullName>Squad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The squad of the hero from The Trial of The Titans</description>
    <label>Squad</label>
    <referenceTo>Squad__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Finalized__c.field-meta.xml
<CustomField>
    <fullName>Finalized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this interview has been finalized; determines whether or not it shows up in statistics and analytics.</description>
    <inlineHelpText>Whether or not this interview has been finalized.</inlineHelpText>
    <label>Finalized</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/QC_Score__c.field-meta.xml
<CustomField>
    <fullName>QC_Score__c</fullName>
    <description>Overall score for this hero&apos;s QC. The value is calculated automatically, but can be overridden (a reason must also be provided).</description>
    <inlineHelpText>The overall score for this hero&apos;s QC; the value is calculated automatically, but can be overridden (a reason must also be provided).</inlineHelpText>
    <label>QC Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <description>The week for which this interview is conducted.</description>
    <inlineHelpText>The week for which the interview is conducted.</inlineHelpText>
    <label>Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Picklist</valueSetName>
    </valueSet>
</CustomField>

Trial of the Titans/CorePackage/objects/Squad__c/Squad__c.object-meta.xml
<CustomObject>
    <label>Squad</label>
    <nameField>
        <label>Squad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Squads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/globalValueSets/Week_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Week 1</fullName>
    </customValue>
    <customValue>
        <fullName>Week 2</fullName>
    </customValue>
    <customValue>
        <fullName>Week 3</fullName>
    </customValue>
    <customValue>
        <fullName>Week 4</fullName>
    </customValue>
    <customValue>
        <fullName>Week 5</fullName>
    </customValue>
    <customValue>
        <fullName>Week 6</fullName>
    </customValue>
    <customValue>
        <fullName>Week 7</fullName>
    </customValue>
    <customValue>
        <fullName>Week 8</fullName>
    </customValue>
    <customValue>
        <fullName>Week 9</fullName>
    </customValue>
    <customValue>
        <fullName>Week 10</fullName>
    </customValue>
    <customValue>
        <fullName>Week 11</fullName>
    </customValue>
    <customValue>
        <fullName>Week 12</fullName>
    </customValue>
    <masterLabel>Week Picklist</masterLabel>
</GlobalValueSet>

QCHubPackage/main/default/classes/QC_Interview.cls
public with sharing class QC_Interview {

     /* public static QC_Hub_Wrapper getQC_Weeks(String weekId){ */
    @AuraEnabled
    public static QCInterviewWrapper getQCWeeks(String cohortStr){

            Schema.DescribeSObjectResult acctDesc = Account.SObjectType.getDescribe();
            Map<String, Schema.RecordTypeInfo> acctRecTypeMap = acctDesc.getRecordTypeInfosByName();
            Id heroTypeId = acctRecTypeMap.get('Hero').getRecordTypeId();

            Cohort__c cohort = (Cohort__c) JSON.deserialize(cohortStr, Cohort__c.class);
            
            List<Account> weekList =  [SELECT Name, QC_Interview__r.Week__c FROM Account WHERE RecordTypeId=:heroTypeId AND Cohort__r.Name=:cohort.Name];

            Map<String, List<Account>> squadMap = new Map<String, List<Account>>();

            for (Account hero : weekList){
                String currentHeroSquad = hero.Squad__r.Name;
                if (squadMap.containsKey(currentHeroSquad)){
                    squadMap.get(currentHeroSquad).add(hero);
                }
                else (squadMap.put(hero.Squad__r.Name, new List<Account>{hero}));
    
            }
            QCInterviewWrapper cohortData = new QCInterviewWrapper();
            cohortData.cohort = cohort;
            cohortData.squadList = squadMap;
    
            return cohortData;

            }
            @AuraEnabled
            public static QC_Interview__c saveQC_Iterview(QC_Interview__c interview){
                // Perform isUpdateable() checking first, then
                insert interview;
                return interview;
                }
    }

/*
    public class QC_Hub_Wrapper{
        public QC_Interview__c weeks {get;set;}
    
        public QC_Hub_Wrapper (QC_Interview__c myweeks){
            weeks = myweeks;
        }
    }
    public Map<Id, QC_Hub_Wrapper> selectedWeek {
        get {
            if (selectedWeek == null) {
                selectedWeek = new Map<Id, QC_Hub_Wrapper>();
            }
            return selectedWeek;
        }
        private set;
    } */


/* 
@AuraEnabled
    public static List<QC_Interview__c> getQC_Interview(){
   // Check to make sure all fields are accessible to this user
   String[] fieldsToCheck = new String[] {
    'Name', 'Week__c', 'QC_Score__c' , 'Finalized__c', 'Cohort__c'
    };
    Map<String,Schema.SObjectField> fieldDescribeTokens = Schema.SObjectType.QC_Interview__c.fields.getMap();
    for(String field : fieldsToCheck) {
        //if( ! fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
            if( field != null && fieldDescribeTokens != null && fieldDescribeTokens.get(field) != null &&
            fieldDescribeTokens.get(field).getDescribe() != null &&
            fieldDescribeTokens.get(field).getDescribe().isAccessible() != null &&
            !fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException();
                }
            }
    return [SELECT Name, Week__c, QC_Score__c, Finalized__c, Cohort__c FROM QC_Interview__c];
    }     */