TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/Account/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Account/fields/Squad__c.field-meta.xml
<CustomField>
    <fullName>Squad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The squad of the hero from The Trial of The Titans</description>
    <label>Squad</label>
    <referenceTo>Squad__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hero&apos;s Team in The Trial of The Titans</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/Finalized__c.field-meta.xml
<CustomField>
    <fullName>Finalized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this interview has been finalized; determines whether or not it shows up in statistics and analytics.</description>
    <inlineHelpText>Whether or not this interview has been finalized.</inlineHelpText>
    <label>Finalized</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/QC_Score__c.field-meta.xml
<CustomField>
    <fullName>QC_Score__c</fullName>
    <description>Overall score for this hero&apos;s QC. The value is calculated automatically, but can be overridden (a reason must also be provided).</description>
    <inlineHelpText>The overall score for this hero&apos;s QC; the value is calculated automatically, but can be overridden (a reason must also be provided).</inlineHelpText>
    <label>QC Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Squad__c/Squad__c.object-meta.xml
<CustomObject>
    <label>Squad</label>
    <nameField>
        <label>Squad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Squads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Squad__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Squads</relationshipLabel>
    <relationshipName>Squads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanPage/Main/default/objects/Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Team a User belongs to.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/classes/Test_QCICohortSelectionAuraController.cls
//////////////////////////////////////////////////////////////////////
//
//  Name: Test_QCICohortSelectionAuraController
//  Author: Natalie Clark
//  Description:    Tests the following Apex classes:
//                  QCInterviewCohortSelectionAuraController
//
//////////////////////////////////////////////////////////////////////
@isTest
public class Test_QCICohortSelectionAuraController {
    @TestSetup
    static void makeData(){
    // factory creates 1 cohort (named cohortName) with 20 heroes (named namePrefix[0-19])
    // each hero receives 1 interview and 5 interview questions
        QCHubDataFactory.dataFactory('cohortName', 'namePrefix');

        //creates team and squads for heroes created
        //delete following lines if refactored QCHubDataFactory to include squad assignation
        Team__c t = new Team__c(Name='teamName');
        insert t;
        Squad__c s = new Squad__c(Name='squadName', Team__c=t.Id);
        insert s;
        List<Account> accountUpdate = [SELECT Id FROM Account];
        for (Integer i=0 ; i<accountUpdate.size() ; i++) {
            accountUpdate[i].Squad__c = s.Id;
        }
        update accountUpdate;

        //updates Finalized__c field for all interviews
        List<QC_Interview__c> interviews = [SELECT Id FROM QC_Interview__c];
        for (Integer i=0 ; i<interviews.size() ; i++) {
            interviews[i].Finalized__c = true;
            interviews[i].QC_Score__c = 4;
        }
        update interviews;
    }

    @isTest
    static void heroReviewTest() {

        //creates params for input into getHeroes method
        Cohort__c c = [SELECT Id FROM Cohort__c WHERE Name='cohortName' LIMIT 1];

        //executes getHeroes method, with system.asserts to verify
        List<Account> accs = QCInterviewCohortSelectionAuraController.getHeroes(c);

        System.assertEquals('cohortName', accs[0].Cohort__r.Name);
        System.assert(accs.size()==20);
        System.assertEquals('squadName', accs[0].Squad__r.Name);

        //executes getInterviews method, with system.asserts to verify
        List<QC_Interview__c> qci = QCInterviewCohortSelectionAuraController.getInterviews(accs);

        System.assert(qci[0].Finalized__c);
        System.assertEquals(4, qci[0].QC_Score__c);
        System.assert(qci.size() == 20);
    }
}