TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/One_on_One__c/One_on_One__c.object-meta.xml
<CustomObject>
    <label>One on One</label>
    <nameField>
        <label>One on One Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One on Ones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/One_on_One__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <label>Hero</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>One on Ones</relationshipLabel>
    <relationshipName>One_on_Ones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

TrialoftheTitansPackage/main/default/objects/One_on_One__c/fields/Internal_Comments__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comments__c</fullName>
    <label>Internal Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

P3/force-app/main/default/objects/One_on_One__c/fields/Personal_Comments__c.field-meta.xml
<CustomField>
    <fullName>Personal_Comments__c</fullName>
    <label>Personal Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/One_on_One__c/fields/Professionalism__c.field-meta.xml
<CustomField>
    <fullName>Professionalism__c</fullName>
    <inlineHelpText>Ability to act and present a professional demeanor and appearance.</inlineHelpText>
    <label>Professionalism</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrainerHubPackage/main/default/objects/One_on_One__c/fields/Soft_Skill_Confidence__c.field-meta.xml
<CustomField>
    <fullName>Soft_Skill_Confidence__c</fullName>
    <inlineHelpText>Ability to project a sense of being a subject matter expert.</inlineHelpText>
    <label>Soft Skill Confidence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/One_on_One__c/fields/Soft_Skill_Fluency__c.field-meta.xml
<CustomField>
    <fullName>Soft_Skill_Fluency__c</fullName>
    <inlineHelpText>Ability to speak effectively with minimal disfluency or other factors.</inlineHelpText>
    <label>Soft Skill Fluency</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrainerHubPackage/main/default/objects/One_on_One__c/fields/Technical_Accuracy__c.field-meta.xml
<CustomField>
    <fullName>Technical_Accuracy__c</fullName>
    <inlineHelpText>Ability to accurately explain and describe things related to the technology.</inlineHelpText>
    <label>Technical Accuracy</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/One_on_One__c/fields/Technical_Fluency__c.field-meta.xml
<CustomField>
    <fullName>Technical_Fluency__c</fullName>
    <inlineHelpText>Ability to use correct technical terminology when discussing the technology.</inlineHelpText>
    <label>Technical Fluency</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

P3/force-app/main/default/objects/One_on_One__c/fields/Trainer__c.field-meta.xml
<CustomField>
    <fullName>Trainer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trainer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>One_on_Ones</relationshipName>
    <type>Lookup</type>
</CustomField>

P3/force-app/main/default/objects/One_on_One__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <label>Week</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/classes/TrainerOneOnOneControllerTest.cls
@IsTest
public class TrainerOneOnOneControllerTest {
    @TestSetup
    static void makeData(){
        Cohort__c testCohort = new Cohort__c(Name = 'testCohort');
        insert testCohort;
        
        Account testHero = new Account(Name = 'Odysseus', Cohort__c = testCohort.Id);
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
        
        User testTrainer = new User(Alias = 'ari', Email='ari@greece.com', 
            EmailEncodingKey='UTF-8', LastName='Plato', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='ari@greece.com');
        
        insert testHero;
        insert testTrainer;
        
        One_on_One__c testOne = new One_on_One__c(Name = 'test', Hero__c = testHero.Id, Trainer__c = testTrainer.Id, Week__c = '2', Professionalism__c = 6, 
                                                   Soft_Skill_Confidence__c = 8, Soft_Skill_Fluency__c	= 7, Technical_Accuracy__c = 8,
                                                  Technical_Fluency__c = 7, Internal_Comments__c = 'Bad', Personal_Comments__c = 'Bene');
        One_on_One__c testOneNeg = new One_on_One__c(Name = 'test', Hero__c = testHero.Id, Trainer__c = testTrainer.Id, Week__c = '1', Professionalism__c = 6, 
                                                   Soft_Skill_Confidence__c = 8, Soft_Skill_Fluency__c	= 7, Technical_Accuracy__c = 8,
                                                  Technical_Fluency__c = 7, Internal_Comments__c = 'Good', Personal_Comments__c = 'No bene');
		insert testOne;
        insert testOneNeg;
        
        List <One_on_One__c> bulkTest = new List <One_on_One__c>();
        for(Integer t = 0; t < 25; t++){
            One_on_One__c test = new One_on_One__c(Name = 'test ' + t, Hero__c = testHero.Id, Trainer__c = testTrainer.Id, Week__c = '2', Professionalism__c = 6, 
                                    Soft_Skill_Confidence__c = 8, Soft_Skill_Fluency__c	= 7, Technical_Accuracy__c = 8,
                                    Technical_Fluency__c = 7, Internal_Comments__c = 'Bad', Personal_Comments__c = 'No good');
            One_on_One__c testNeg = new One_on_One__c(Name = 'test', Hero__c = testHero.Id, Trainer__c = testTrainer.Id, Week__c = '1', Professionalism__c = 6, 
                                    Soft_Skill_Confidence__c = 8, Soft_Skill_Fluency__c	= 7, Technical_Accuracy__c = 8,
                                    Technical_Fluency__c = 7, Internal_Comments__c = 'Good', Personal_Comments__c = 'No bene');
            bulkTest.add(test);
            bulkTest.add(testNeg);
        }
        insert bulkTest;
    }
    @IsTest
    public static void singleTests() {
        Cohort__c testCohort = [SELECT Name, Id FROM Cohort__c WHERE Name = 'testCohort'];
        User testTrainer = [SELECT Id FROM User WHERE LastName = 'Plato'];
        //positive
        List <One_on_One__c> testQueryList = TrainerOneOnOneController.getOneOnOneId(testTrainer.Id, '2', testCohort.Id);
        One_On_One__c test = testQueryList[0];
		String testId = test.Id;
        System.assertEquals(testId, testQueryList[0].Id);
        //negative
        List <One_on_One__c> testNegList = TrainerOneOnOneController.getOneOnOneId(testTrainer.Id, '1', testCohort.Id);
        One_On_One__c negTest = testNegList[0];
        String testNegId = negTest.Id;
        System.assertNotEquals(negTest.Id, testQueryList[0].Id);
    }
    @IsTest
    public static void bulkTests(){
        User testTrainer = [SELECT Id FROM User WHERE LastName = 'Plato'];
        Cohort__c testCohort = [SELECT Name, Id FROM Cohort__c WHERE Name = 'testCohort'];
        List <One_on_One__c> testQueryListBulk = TrainerOneOnOneController.getOneOnOneId(Id.valueof(testTrainer.Id), '2', Id.valueof(testCohort.Id));
        for(Integer i = 0; i < testQueryListBulk.size(); i++){
           List <One_on_One__c> test = TrainerOneOnOneController.getOneOnOneId(Id.valueof(testTrainer.Id), '2', Id.valueof(testCohort.Id));
           System.assertEquals(testQueryListBulk[i], test[i]);
        }
        for(Integer i = 0; i < testQueryListBulk.size(); i++){
           List <One_on_One__c> testNegative = TrainerOneOnOneController.getOneOnOneId(Id.valueof(testTrainer.Id), '1', Id.valueof(testCohort.Id));
           System.assertNotEquals(testQueryListBulk[i], testNegative[i]);
        }
    }
}