TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Account/fields/Squad__c.field-meta.xml
<CustomField>
    <fullName>Squad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The squad of the hero from The Trial of The Titans</description>
    <label>Squad</label>
    <referenceTo>Squad__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hero&apos;s Team in The Trial of The Titans</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/Exam_Question__c.object-meta.xml
<CustomObject>
    <!---->
    <label>Exam Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

P3/force-app/main/default/objects/Exam_Result__c/fields/Graded__c.field-meta.xml
<CustomField>
    <fullName>Graded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Graded</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Answer__c/Hero_Answer__c.object-meta.xml
<CustomObject>
    <label>Hero Answer</label>
    <nameField>
        <displayFormat>HA-{0}</displayFormat>
        <label>Hero Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P3/force-app/main/default/objects/Hero_Answer__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Correct</label>
    <type>Checkbox</type>
</CustomField>

ExamPackage/main/default/objects/Hero_Answer__c/fields/Exam_Question__c.field-meta.xml
<CustomField>
    <fullName>Exam_Question__c</fullName>
    <label>Exam Question</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Hero Answers</relationshipLabel>
    <relationshipName>Hero_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Answer__c/fields/Exam_Result__c.field-meta.xml
<CustomField>
    <fullName>Exam_Result__c</fullName>
    <label>Exam Result</label>
    <referenceTo>Exam_Result__c</referenceTo>
    <relationshipLabel>Hero Answers</relationshipLabel>
    <relationshipName>Hero_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Squad__c/Squad__c.object-meta.xml
<CustomObject>
    <label>Squad</label>
    <nameField>
        <label>Squad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Squads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Squad__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Squads</relationshipLabel>
    <relationshipName>Squads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanPage/Main/default/objects/Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Team a User belongs to.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/classes/HeroHubControllerTest.cls
/////////////////////////////////////////////////////
//
//  Name: HeroHubController Test
//  Author: Josh Miccolo
//  Created: 5/24/2021
//  Updated: 9/3/2021
//  Description: Tests for the Hero Hub controller.
//  
//
///////////////////////////////////////////////////
@isTest
public class HeroHubControllerTest {

    //heroTestSetup() calls createUsers to create an admin and hero user for testing.
    @testSetup
    static void heroTestSetup(){
        HeroHubTestUtilities.createUsers();
    }

    //testContextInfoRightUser() tests to see if the information for the user is correct, using
    //getUserInfo from the HeroHubController to check this information.
   	@isTest
    static void testContextInfoRightUser(){
    	HeroHubTestUtilities.fullSetup();
    	User testUser = [SELECT Id FROM USER WHERE alias = 'testUser' LIMIT 1];
        UserContextInfo info;
    
    	system.runAs(testUser){
            info = HeroHubController.getUserInfo();
    	}

        Account useracct = [SELECT Id, Team__c, Squad__c FROM Account WHERE name = 'User'];
        
        //Assert user information associated with Id, squad, and team
        system.AssertEquals(useracct.Id, info.acc.Id);
        system.AssertEquals(useracct.Squad__c, info.squad.Id);
        system.AssertEquals(useracct.Team__c, info.team.Id);
  
        //Assert information about the user such as amount of exams and amount of results involving Apex
        //system.AssertEquals(3, info.userExams.size());
        //system.AssertEquals(0, info.userExams.get('Apex').size());
        //system.AssertEquals(2, info.userExams.get('Apex')[0].currentResults.size());
       	//system.AssertEquals(true, info.userExams.get('Apex')[0].isPassed);
    }

    //testAuraException() tests the negative use case where the running user would throw an aura exception
    //when we call the getUserInfo of HeroHubController
    @isTest
    static void testAuraException(){
        Boolean exceptionCaught = false;

        try{
            HeroHubTestUtilities.createWrongUser();
            
            HeroHubTestUtilities.fullSetup();

            User testUser = [SELECT Id FROM USER WHERE alias = 'TTrain' LIMIT 1];
            UserContextInfo info;

            System.runAs(testUser){
                info = HeroHubController.getUserInfo();
            }
        }catch(Exception e){
            exceptionCaught = true;
        }
        System.assertEquals(true, exceptionCaught);
    }
    
    //returnsdifferentTeams() checks to see if the two accounts returned have different teams
    //by getting the score by teams and then asserting that the size of the map created is 2.
    @isTest
    static void returnsdifferentTeams(){
        User testUser = [SELECT Id FROM USER WHERE alias = 'testUser'];
        
        List<Account> twoAccounts = getTwoAccounts();
		createResultsWithAnswers(twoAccounts);
        system.runAs(testUser){
        	Map<String, Decimal> teamScores = HeroHubController.getScoresbyTeam();
    
           	system.assertEquals(1, teamScores.size());
        }
   	}
    
    //findAllResults() queries for a testUser before getting the team scores and asserting that 
    //the resulting map has a size of 3
    @isTest
    static void findAllResults(){
        User testUser = [SELECT Id FROM User WHERE alias = 'testUser' LIMIT 1];
        system.runAs(testUser){
            Map<String, Map<String, Decimal>> HeroHub =  HeroHubController.getTeamScores();
            
            system.assertEquals(3, HeroHub.size());
        }
    }

    //getTwoAccounts() creates and inserts two accounts and their associated teams, squads and cohorts
    // into the database.
    private static List<Account> getTwoAccounts(){
        List<Account> acctList = new List<Account>();
        List<Team__c> teamList = new List<Team__c>();
        List<Squad__c> squadList = new List<Squad__c>();
        List<Cohort__c> cohortList = new List<Cohort__c>();
        
        //create two teams and two cohorts
        for(Integer i = 0; i < 2; i++){
            Team__c newTeam = new Team__c(Name = 'Team'+i);
            teamList.add(newTeam);
            Cohort__c newCohort = new Cohort__c(Name= 'Cohort' + i);
      		cohortList.add(newCohort);
       	}
        
        database.insert(teamList);
        database.insert(cohortList);
        
        //create a squad for each of the two teams
        for(Team__c team:teamList){
            Squad__c newSquad = new Squad__c(Name=team.Name+'squad', Team__c = team.Id);
            squadList.add(newSquad);
        }
        
        database.insert(squadList);
      	
        //create two accounts with the correct information.
        for(Integer i = 0; i < 2; i++){
            Account newAcct = new Account(Name='Test'+i, Team__c = teamlist[i].Id, 
            Squad__c = squadList[i].Id, Cohort__c = cohortList[i].Id);
            acctList.add(newAcct);
        }

        database.insert(acctList);
        return acctList;
        
    }
    
    //createResultsWithAnswers() creates and inserts exam results and answers for each account.
    //twoAccounts: list of two accounts to create results and answers for
    private static void createResultsWithAnswers(List<Account> twoAccounts){
        Exam__c newExam = new Exam__c(Name='testExam');
        database.insert(newExam);
        
        Exam_Question__c newQuestion = new Exam_Question__c(Name='testquestion');
       	database.insert(newQuestion);
        
        for(Account acct: twoAccounts){
        	Exam_Result__c newResult = new Exam_Result__c(Exam__c = newExam.Id, 
                                                            Account__c = acct.Id, 
                                                            Graded__c=true, 
                                                            Status__c = 'Completed');
            database.insert(newResult);

            Hero_Answer__c newAnswer = new Hero_Answer__c(Exam_Question__c = newQuestion.Id, 
                                                            Exam_Result__c = newResult.id, 
                                                            Correct__c = true);

            database.insert(newAnswer);
        }
    }
}