TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/Account/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Account/fields/Squad__c.field-meta.xml
<CustomField>
    <fullName>Squad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The squad of the hero from The Trial of The Titans</description>
    <label>Squad</label>
    <referenceTo>Squad__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/Cohort__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>a check box indicating if a cohort is active or not</description>
    <label>Currently Active</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Answer__c/Hero_Answer__c.object-meta.xml
<CustomObject>
    <label>Hero Answer</label>
    <nameField>
        <displayFormat>HA-{0}</displayFormat>
        <label>Hero Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The hero this QC Interview was for.</description>
    <inlineHelpText>The hero this QC Interview was for.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>QC Interviews can only be associated with a &quot;hero&quot;-type account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Hero</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <description>The week for which this interview is conducted.</description>
    <inlineHelpText>The week for which the interview is conducted.</inlineHelpText>
    <label>Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Picklist</valueSetName>
    </valueSet>
</CustomField>

QCHubPackage/main/default/objects/QC_Question__c/QC_Question__c.object-meta.xml
<CustomObject>
    <description>Pre-made question for QC Interviews.</description>
    <label>QC Question</label>
    <nameField>
        <label>QC Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Question__c/fields/Expected_Answer__c.field-meta.xml
<CustomField>
    <fullName>Expected_Answer__c</fullName>
    <label>Expected Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Question__c/fields/QC_Question_Deck__c.field-meta.xml
<CustomField>
    <fullName>QC_Question_Deck__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QC Question Deck</label>
    <referenceTo>QC_Question_Deck__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>QC_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question__c/fields/Question_Body__c.field-meta.xml
<CustomField>
    <fullName>Question_Body__c</fullName>
    <label>Question Body</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Question_Answer__c/QC_Question_Answer__c.object-meta.xml
<CustomObject>
    <label>QC Question Answer</label>
    <nameField>
        <displayFormat>QCA-{000000}</displayFormat>
        <label>QC Question Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QC Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/Expected_Answer__c.field-meta.xml
<CustomField>
    <fullName>Expected_Answer__c</fullName>
    <description>Answer that was expected, based on the question given.</description>
    <inlineHelpText>Answer that was expected, based on the question given.</inlineHelpText>
    <label>Expected Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Question_Answer__c/fields/Hero_Answer__c.field-meta.xml
<CustomField>
    <fullName>Hero_Answer__c</fullName>
    <description>The answer that was given by the hero.</description>
    <inlineHelpText>The answer that was given by the hero.</inlineHelpText>
    <label>Hero Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <description>The QC interview this question/answer data were a part of.</description>
    <inlineHelpText>The QC interview this set of questions and answers are a part of.</inlineHelpText>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>QC Question Answers</relationshipLabel>
    <relationshipName>QC_Question_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Question_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>The question that was asked during the interview; it could either be from the question deck, or provided directly by the QC Interviewer.</description>
    <inlineHelpText>The question that was asked during the interview.</inlineHelpText>
    <label>Question</label>
    <type>TextArea</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Question_Answer__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Score assigned by the interviewer to the hero&apos;s answer.</description>
    <inlineHelpText>Score assigned by the interviewer to the hero&apos;s answer.</inlineHelpText>
    <label>Score</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Question_Deck__c/QC_Question_Deck__c.object-meta.xml
<CustomObject>
    <label>QC Question Deck</label>
    <nameField>
        <label>QC Question Deck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Question Decks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Question_Deck__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <description>The week this question deck is intended for.</description>
    <inlineHelpText>The week this question deck is intended for.</inlineHelpText>
    <label>Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Picklist</valueSetName>
    </valueSet>
</CustomField>

Trial of the Titans/CorePackage/objects/Squad__c/Squad__c.object-meta.xml
<CustomObject>
    <label>Squad</label>
    <nameField>
        <label>Squad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Squads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P3/force-app/main/default/objects/Squad__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

QCHubPackage/main/default/globalValueSets/Week_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Week 1</fullName>
    </customValue>
    <customValue>
        <fullName>Week 2</fullName>
    </customValue>
    <customValue>
        <fullName>Week 3</fullName>
    </customValue>
    <customValue>
        <fullName>Week 4</fullName>
    </customValue>
    <customValue>
        <fullName>Week 5</fullName>
    </customValue>
    <customValue>
        <fullName>Week 6</fullName>
    </customValue>
    <customValue>
        <fullName>Week 7</fullName>
    </customValue>
    <customValue>
        <fullName>Week 8</fullName>
    </customValue>
    <customValue>
        <fullName>Week 9</fullName>
    </customValue>
    <customValue>
        <fullName>Week 10</fullName>
    </customValue>
    <customValue>
        <fullName>Week 11</fullName>
    </customValue>
    <customValue>
        <fullName>Week 12</fullName>
    </customValue>
    <masterLabel>Week Picklist</masterLabel>
</GlobalValueSet>

QCHubPackage/main/default/classes/RetrieveHero_Info.cls
public with sharing class RetrieveHero_Info {
    
    public class QCInterviewWrapper {

        @AuraEnabled        
        public Id QCInterviewId {get;set;}

        @AuraEnabled
        public Cohort__c objCohort {get;set;}

        @AuraEnabled
        public Account objHero {get;set;}

        @AuraEnabled
        public Boolean isActive {get;set;}
        
        public QCInterviewWrapper(Id id, String name, Boolean active) {
            QCInterviewId = id;
            objCohort = new Cohort__c();
            objHero = new Account();
            isActive = active;
        }
    }

    public class Wrapper{
        @AuraEnabled public String cohortId {get; set;}
        @AuraEnabled public String cohortName {get; set;}
        @AuraEnabled public String heroId {get; set;}
        @AuraEnabled public String heroName {get; set;}
        @AuraEnabled public String weekName {get; set;}
        @AuraEnabled public String qcInterviewId {get; set;}

    }

    public class MasterWrapper{
        @AuraEnabled public Map<String, List<Wrapper>> mapCohortNameVsWrapper {get;set;}
        @AuraEnabled public Set<String> cohortNames {get;set;}
        @AuraEnabled public Set<String> setWeeks {get;set;}
        @AuraEnabled public List<QC_Question_Deck__c> allQuestionDeckWithQuestions {get; set;}

        public MasterWrapper(){
            mapCohortNameVsWrapper = new Map<String, List<Wrapper>>();
            cohortNames = new Set<String>();
            setWeeks =  new Set<String>();
            allQuestionDeckWithQuestions = new List<QC_Question_Deck__c>();
        }
    }

    @AuraEnabled
    public static MasterWrapper getData(){
        MasterWrapper wrap = new MasterWrapper();
        Map<String, List<Wrapper>> mapCohortNameVsWrapper = new Map<String, List<Wrapper>>();
        Set<String> cohortNames = new Set<String>();
        for(QC_Interview__c qcInterviews: [SELECT Id, Week__c,Cohort__c,Cohort__r.Name, Cohort__r.Active__c,
                                         Account__c, Account__r.Name FROM QC_Interview__c ]){
            if(null != qcInterviews.Cohort__c && null != qcInterviews.Account__c &&  qcInterviews.Cohort__r.Active__c){
                List<Wrapper> listWrapper = new List<Wrapper>();
                if(mapCohortNameVsWrapper.containsKey(qcInterviews.Cohort__r.Name)){
                    listWrapper.addAll(mapCohortNameVsWrapper.get(qcInterviews.Cohort__r.Name));
                }
                Wrapper obj = new Wrapper();
                obj.cohortId = qcInterviews.Cohort__c;
                obj.cohortName = qcInterviews.Cohort__r.Name;
                obj.heroId = qcInterviews.Account__c;
                obj.heroName = qcInterviews.Account__r.Name;
                obj.weekName = qcInterviews.Week__c;
                obj.qcInterviewId = qcInterviews.Id;
                listWrapper.add(obj);
                cohortNames.add(qcInterviews.Cohort__r.Name);
                mapCohortNameVsWrapper.put(qcInterviews.Cohort__r.Name, listWrapper);
            }
        
        }
        wrap.cohortNames = cohortNames;
        wrap.mapCohortNameVsWrapper = mapCohortNameVsWrapper;
        wrap.setWeeks = getWeekPickListValues();
        wrap.allQuestionDeckWithQuestions = getQuestionDeckWithQuestions();
        return wrap;
    }

    @AuraEnabled
    public static List<QC_Question_Deck__c> getQuestionDeckWithQuestions(){
        List<QC_Question_Deck__c> listQuestionDecks = new List<QC_Question_Deck__c>();
        listQuestionDecks = [Select Id, Name, Week__c,
        (Select Id,Name , Question_Body__c, Expected_Answer__c from QC_Questions__r) 
        from QC_Question_Deck__c];

        return listQuestionDecks;
        
    }

    @AuraEnabled
    public static QC_Question_Deck__c getQuestionDeckAndQuestions(String weekName){
        QC_Question_Deck__c questionDeck = new QC_Question_Deck__c();
        questionDeck = [Select Id, Name, Week__c,
        (Select Id,Name , Question_Body__c, Expected_Answer__c from QC_Questions__r LIMIT 1) 
        from QC_Question_Deck__c Where Week__c =: weekName LIMIT 1];

        return questionDeck;
        
    }

    @AuraEnabled 
    public static void submitTheAnswer(String qcInterviewId, String answer, String question){
        try {
            QC_Question_Answer__c qa= new QC_Question_Answer__c();
            //qa.Name = 'Test';
            qa.Hero_Answer__c = answer;
            qa.QC_Interview__c = qcInterviewId;
            qa.Question__c = question;
            qa.Score__c = 20;
            System.debug('#### qa = '+ qa);
            insert qa;
        } catch (Exception e) {
            System.debug('#### error = '+ e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
    }


    public static Set<String> getWeekPickListValues(){
        Set<String> pickListValuesList= new Set<String>();
        Schema.DescribeFieldResult fieldResult = QC_Interview__c.Week__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            pickListValuesList.add(pickListVal.getLabel());
        }  
        System.debug('### pickListValuesList = '+ pickListValuesList);
        return pickListValuesList;
     }


   /*  @AuraEnabled
    public static Map<Integer, List<QCInterviewWrapper>> getActiveCohorts(){   
        
        Map<Integer, List<QCInterviewWrapper>> cohmap = new Map<Integer, List<QCInterviewWrapper>>();

        List<QCInterviewWrapper> cQCw = new List<QCInterviewWrapper>();

        Integer index = 1;
        Integer counter = 1;

        for(Cohort__c ch: [SELECT Id ,Name, Active__c FROM Cohort__c WHERE Active__c = TRUE]){
            cQCw.add(new QCInterviewWrapper(ch.Id , ch.Name, ch.Active__c));
            cohmap.put(index, cQCw);
            cQCw = new List<QCInterviewWrapper>();      
            counter++;
        }
        if(!cQCw.isEmpty()){
            cohmap.put(index, cQCw);
        }
        
        return cohmap;

    }
    @AuraEnabled
    public static List<Account> GetHerosforEachCohort(Id QCInterviewId){
        
        List<Account> cohortHeros  = new List<Account>();
        
        for(QC_Interview__c heros: [SELECT Id, Cohort__c, Account__r.Name
                                 FROM QC_Interview__c WHERE Cohort__c = :QCInterviewId]){
                                     // put the heros in to the list
                                     cohortHeros.add(new Account(Name = heros.Account__r.Name));
        }
        return cohortHeros;
    } */





 
/*     public Map<Id, QCInterviewWrapper> selectedCohort{
        get{
            if(selectedCohort == null){
                selectedCohort = new Map<id, QCInterviewWrapper>();
             /*    Cohort__c showCohort  = [SELECT Name , Active__c FROM Cohort__c WHERE Active__c = TRUE];
                selectedCohort.put(new QCInterviewWrapper(showCohort));  
                            }
            return selectedCohort;
        }
        private set;     
    }
  
    public List<QCInterviewWrapper> activeCohortMembers{
        get{
            if(activeCohortMembers==null){
                activeCohortMembers = new List<QCInterviewWrapper>();
                for(Account myWeeks : [SELECT Id, Name FROM Account]){
                    activeCohortMembers.add(new QCInterviewWrapper(activeCohortMembers.get(myWeeks.Id),activeCohortMembers.get(myWeeks.Name)));

                  //  this.wrapperList.add(new MyWrapper(conMap.get(ocr.ContactId),oppMap.get(ocr.OpportunityId)));
                }
            }
            return activeCohortMembers;
        }
        set;          
    }
    */

  
  /*   public static QCInterviewWrapper pickedCohort(String pickedCohort){

        pickedCohort = this.selectedCohort;
        pickedCohort.clear();

        for (QCInterviewWrapper cl : activeCohort){
            pickedCohort.put(cl.cohortMembers.Id, cl);
        }
        if(pickedCohort.size() > 1){
            return pickedCohort;
        }else{
            System.debug('error');
            return null;
        }    
    } */







 /*    @AuraEnabled
    public static QCInterviewWrapper getQCWeeks(String cohortStr){

            Schema.DescribeSObjectResult acctDesc = Account.SObjectType.getDescribe();
            Map<String, Schema.RecordTypeInfo> acctRecTypeMap = acctDesc.getRecordTypeInfosByName();
            Id heroTypeId = acctRecTypeMap.get('Hero').getRecordTypeId();

            Cohort__c cohort = (Cohort__c) JSON.deserialize(cohortStr, Cohort__c.class);
            
            List<Account> weekList =  [SELECT Name, QC_Interview__r.Week__c FROM Account WHERE RecordTypeId=:heroTypeId AND Cohort__r.Name=:cohort.Name];

            Map<String, List<Account>> squadMap = new Map<String, List<Account>>();

            for (Account hero : weekList){
                String currentHeroSquad = hero.Squad__r.Name;
                if (squadMap.containsKey(currentHeroSquad)){
                    squadMap.get(currentHeroSquad).add(hero);
                }
                else (squadMap.put(hero.Squad__r.Name, new List<Account>{hero}));
    
            }
            QCInterviewWrapper cohortData = new QCInterviewWrapper();
            cohortData.cohort = cohort;
            cohortData.squadList = squadMap;
    
            return cohortData;

            }
            @AuraEnabled
            public static QC_Interview__c saveQC_Iterview(QC_Interview__c interview){
                // Perform isUpdateable() checking first, then
                insert interview;
                return interview;
                }    */
}