TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/Account/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Flag__c/QC_Flag__c.object-meta.xml
<CustomObject>
    <description>Added to a hero&apos;s QC Interview to note comments about the interview.</description>
    <label>QC Flag</label>
    <nameField>
        <label>QC Flag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Flags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Flag__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Flag__c/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>QC Flags</relationshipLabel>
    <relationshipName>QC_Flags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Finalized__c.field-meta.xml
<CustomField>
    <fullName>Finalized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this interview has been finalized; determines whether or not it shows up in statistics and analytics.</description>
    <inlineHelpText>Whether or not this interview has been finalized.</inlineHelpText>
    <label>Finalized</label>
    <type>Checkbox</type>
</CustomField>

QCHubPackage/main/default/classes/Test_QCInterviewHeroReviewAuraController.cls
@isTest
public class Test_QCInterviewHeroReviewAuraController {
    @TestSetup
    static void makeData(){
    // factory creates 1 cohort (named cohortName) with 20 heroes (named namePrefix[0-19])
    // each hero receives 1 interview and 5 interview questions
        QCHubDataFactory.dataFactory('cohortName', 'namePrefix');
    }

    // tests all methods in the QCInterviewHeroReviewAuraController class
    @isTest
    static void heroReviewTest() {

        //creates params for input into getInterview method
        Cohort__c c = [SELECT Id FROM Cohort__c WHERE Name='cohortName' LIMIT 1];
        Account a = [SELECT Id FROM Account WHERE Name='namePrefix5' LIMIT 1];

        //executes getInterview method, with system.asserts to verify
        QC_Interview__c qci = QCInterviewHeroReviewAuraController.getInterview(c, a);

        System.assertEquals(c.Id, qci.Cohort__c);
        System.assertEquals('namePrefix5QC namePrefix', qci.Name);
        System.assert(qci.Finalized__c != true);

        // executes setInterview method, with system.asserts to verify
        QCInterviewHeroReviewAuraController.setInterview(qci);

        System.assert(qci.Finalized__c == true);

        //creates 5 flags for insertion
        List<QC_Flag__c> flags = new List<QC_Flag__c>();
        for (Integer i=0 ; i<5 ; i++ ) {
            QC_Flag__c f = new QC_Flag__c(Name='flag '+i, Description__c='genericDescription'+i, QC_Interview__c=qci.Id);
            flags.add(f);
        }

        // executes setFlags method, with system.asserts to verify
        QCInterviewHeroReviewAuraController.setFlags(flags);

        QC_Flag__c check = [SELECT Name, QC_Interview__c FROM QC_Flag__c WHERE Name='flag 3' LIMIT 1];

        System.assertEquals('flag 3', check.Name);
        System.assertEquals(qci.Id, check.QC_Interview__c);
    }

}