TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

TrialoftheTitansPackage/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Assessment object for 1-on-1s, projects, and misc.</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>a check box indicating if a cohort is active or not</description>
    <label>Currently Active</label>
    <type>Checkbox</type>
</CustomField>

TrainerHubPackage/main/default/objects/Hero_Assessment__c/Hero_Assessment__c.object-meta.xml
<CustomObject>
    <label>Hero Assessment</label>
    <nameField>
        <displayFormat>HA-{0000}</displayFormat>
        <label>Hero Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Hero_Assessment__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <description>Relating Hero Assessment to Assessment</description>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Hero Assessments</relationshipLabel>
    <relationshipName>Hero_Assessments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrainerHubPackage/main/default/objects/Hero_Assessment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <label>Hero</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hero Assessments</relationshipLabel>
    <relationshipName>Hero_Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrainerHubPackage/main/default/classes/HeroAssessmentListControllerTest.cls
@isTest
public class HeroAssessmentListControllerTest {
	
	@isTest
    static void testHeroAssessmentTable(){
        
		List<Cohort__c> newCohorts = new List<Cohort__c>();

		Cohort__c newcohort = new Cohort__c(Name = 'Testcohort', Active__c = true);
		newCohorts.add(newcohort);

		Cohort__c newcohortTwo = new Cohort__c(Name = 'TestcohortTwo', Active__c = false);
		newCohorts.add(newcohortTwo);
		
        for(Integer i = 0 ; i <5 ; i++){
            Cohort__c pastCohort = new Cohort__c(Name = 'Testcohort' + i, Active__c = false);
		newCohorts.add(pastCohort);
        }

        database.insert(newCohorts);

		List<Account> accountsToAdd = new List<Account>();
		Account heroTest = new Account(Name = 'TestHero', Cohort__c = newcohort.Id);
		accountsToAdd.add(heroTest);
        
		Account heroTestTwo = new Account(Name = 'TestHeroTwo', Cohort__c = newcohortTwo.Id);
		accountsToAdd.add(heroTestTwo);

		database.insert(accountsToAdd);
        
		Assessment__c assessmentTest = new Assessment__c(Name = 'Test Assessment');
        database.insert(assessmentTest);
		
		List<Hero_Assessment__c> heroAssessmentsToAdd = new List<Hero_Assessment__c>();
		Hero_Assessment__c heroAssessmentTest = new Hero_Assessment__c( Hero__c = heroTest.Id, Assessment__c = assessmentTest.Id);
		Hero_Assessment__c heroAssessmentTestTwo = new Hero_Assessment__c( Hero__c = heroTestTwo.Id, Assessment__c = assessmentTest.Id);
		heroAssessmentsToAdd.add(heroAssessmentTest);
		heroAssessmentsToAdd.add(heroAssessmentTestTwo);
		database.insert(heroAssessmentsToAdd);

		System.assert(HeroAssessmentListController.HeroListAllCohorts().size() == 2,'Total list Not two hero assessment');
		System.assert(HeroAssessmentListController.HeroListAllCohorts().size() == [SELECT Id FROM Hero_Assessment__c].size(),'Total list doesnt match hero assessment soql statement');
		System.assert(HeroAssessmentListController.HeroList(newcohort.Id).size() == 1,'With cohort id not one hero assessment');

		System.assert(HeroAssessmentListController.SearchHeroList('TestHe', newcohort.Id).size() == 1,'With cohort id and search key not one hero assessment');
		System.assert(HeroAssessmentListController.SearchHeroList('Billy', newcohort.Id).size() == 0,'Billy should not have an hero assessment');	
    
		
	}

}