TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Account/fields/Squad__c.field-meta.xml
<CustomField>
    <fullName>Squad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The squad of the hero from The Trial of The Titans</description>
    <label>Squad</label>
    <referenceTo>Squad__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hero&apos;s Team in The Trial of The Titans</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Curriculum__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technology</label>
    <referenceTo>Technology__c</referenceTo>
    <relationshipLabel>Curricula</relationshipLabel>
    <relationshipName>Curricula</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam__c/fields/Default_Passing_Grade__c.field-meta.xml
<CustomField>
    <fullName>Default_Passing_Grade__c</fullName>
    <label>Default Passing Grade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/Exam_Question__c.object-meta.xml
<CustomObject>
    <!---->
    <label>Exam Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

P3/force-app/main/default/objects/Exam_Question__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <formula>TEXT( Titan__r.Technology__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Technology</label>
    <type>Text</type>
</CustomField>

P3/force-app/main/default/objects/Exam_Question__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

P3/force-app/main/default/objects/Exam_Result__c/fields/Graded__c.field-meta.xml
<CustomField>
    <fullName>Graded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Graded</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Answer__c/Hero_Answer__c.object-meta.xml
<CustomObject>
    <label>Hero Answer</label>
    <nameField>
        <displayFormat>HA-{0}</displayFormat>
        <label>Hero Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P3/force-app/main/default/objects/Hero_Answer__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Correct</label>
    <type>Checkbox</type>
</CustomField>

ExamPackage/main/default/objects/Hero_Answer__c/fields/Exam_Question__c.field-meta.xml
<CustomField>
    <fullName>Exam_Question__c</fullName>
    <label>Exam Question</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Hero Answers</relationshipLabel>
    <relationshipName>Hero_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Answer__c/fields/Exam_Result__c.field-meta.xml
<CustomField>
    <fullName>Exam_Result__c</fullName>
    <label>Exam Result</label>
    <referenceTo>Exam_Result__c</referenceTo>
    <relationshipLabel>Hero Answers</relationshipLabel>
    <relationshipName>Hero_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Squad__c/Squad__c.object-meta.xml
<CustomObject>
    <label>Squad</label>
    <nameField>
        <label>Squad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Squads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Squad__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Squads</relationshipLabel>
    <relationshipName>Squads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanPage/Main/default/objects/Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Team a User belongs to.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Titan__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Titans</relationshipLabel>
    <relationshipName>Titans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CorePackage/main/default/objects/Titan__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Technology for the Titan in Trial of The Titan</description>
    <label>Technology</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <description>Technologies in the Trial of The Titans</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

TitanPage/main/default/classes/TitanPageTestUtilities.cls
@isTest
public class TitanPageTestUtilities {
    
    
    @isTest
    public static void fullSetup(){

        createTitans();
        createExams();
        createQuestions();
        createExamResults();
        createAnswers();
        
    }
    
    @isTest
    public static void createUsers(){
        
        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        
        UserRole customerManager = [SELECT Id FROM UserRole WHERE Name = 'Customer Manager' LIMIT 1];
        
		User adminUser = new User( profileId = adminProfile.Id,
						   		 username = 'admin' + Crypto.getRandomInteger() + '@yahoo.com',
						   		 email = 'test@test.com',
								 emailencodingkey = 'UTF-8',
								 localesidkey = 'en_US',
								 languagelocalekey = 'en_US',
								 timezonesidkey = 'America/Los_Angeles',
								 alias = 'testAd',
								 lastname = 'testAdmin',
                                 userRoleId = customerManager.Id
                               );
        // created a new admin user to use in a runAs to create a new transaction.
        User user1 = [SELECT Id, Name FROM USER WHERE ProfileId = :adminProfile.Id Limit 1];
        System.runAs(user1) {


           Database.insert(adminUser);
        } 
        // The above prevents a Mixed DML error.

        Team__c newTeam = new Team__c(Name = 'TestTeam');
        database.insert(newTeam);
         
        
            
        Cohort__c newcohort = new Cohort__c(Name = 'Testcohort');
        database.insert(newcohort);
            
        Account newAccount = new Account(name='User', Team__c = newTeam.Id);
        database.insert(newAccount);       
     
        Contact newContact = new Contact(lastName='User', AccountId = newAccount.id);
        database.insert(newContact);
        
       
        
        System.runAs(adminUser){
        
       // Get Hero profile from database to use for Users
       Profile heroProfile = [SELECT Id FROM Profile WHERE Name = 'Hero' LIMIT 1];
        
        
       
       User testUser = new User( profileId = heroProfile.id,
                                   username = newContact.lastName + Crypto.getRandomInteger() + '@yahoo.com',
                                   email = 'test@test.com',
                                emailencodingkey = 'UTF-8',
                                localesidkey = 'en_US',
                                languagelocalekey = 'en_US',
                                timezonesidkey = 'America/Los_Angeles',
                                alias = 'testUser',
                                lastname = newContact.lastName,
                                contactId = newContact.id
                              );
     
       database.insert(testUser);
       Id groupID = [SELECT Id FROM PermissionSetGroup WHERE DeveloperName = 'TrialOfTheTitansHeroPermissions' Limit 1].Id;
      PermissionSetAssignment assignment = new PermissionSetAssignment(PermissionSetGroupId = groupId, AssigneeId = testUser.Id);

      Database.insert(assignment);
       
        
        
        
        }

         
         
        
        	
    }
    
    @isTest
    public static void createWrongUser(){
        
        Account newAccount = new Account(name='Trainer' );
        insert newAccount;
        
        // Get Hero profile from database to use for Users
        Profile trainerProfile = [SELECT Id FROM Profile WHERE Name = 'TitanTrainer' LIMIT 1];
            
		User newUser = new User( profileId = trainerProfile.id,
						   		 username = 'Trainer' + Crypto.getRandomInteger() + '@yahoo.com',
						   		 email = 'test@test.com',
								 emailencodingkey = 'UTF-8',
								 localesidkey = 'en_US',
								 languagelocalekey = 'en_US',
								 timezonesidkey = 'America/Los_Angeles',
								 alias = 'TTrain',
                                 lastName = 'Trainer'
								 );
        insert newUser; 
     
    }
    @isTest
    public static void createTitans(){
        
        // Create curriculum and Titans for Exams
        Curriculum__c newCurriculum = new Curriculum__c(Name='Salesforce');
        insert newCurriculum;
        
        List<Titan__c> newTitans = new List<Titan__c>();
        
        List<String> titanNames = new List<String>{'Process Automation', 'Data Modeling', 'Apex'};
        
        for(String name : titanNames){
        	
            Titan__c newTitan = new Titan__c(Name = name, Technology__c = newCurriculum.Name,  Curriculum__c = newCurriculum.Id);
            newTitans.add(newTitan);
            
        }
        
        database.insert(newTitans);
        
    }
    
    @isTest
    public static void createExams(){
        List<Titan__c> titans = [SELECT Id, Name From Titan__c];
        List<Exam__c> newExams = new List<Exam__c>();
        
        for(Titan__c titan : titans){
            
            for(Integer i = 0; i < 3; i++){
                
                Exam__C newExam = new Exam__c( Name='testExam'+ i, Default_Passing_Grade__c = 65.0, Titan__c = titan.Id );            	
                newExams.add(newExam);
            
            }    
        
        }
        
        database.insert(newExams);
    }
    
    @isTest
    public static void createQuestions(){
  
		List<Exam_Question__c> newQuestions = new List<Exam_Question__C>();
                    
        for(Integer i = 0; i < 5; i++){
                
                Exam_Question__C newQuestion = new Exam_Question__c( Name = 'Test' + i );
                newQuestions.add(newQuestion);
            
        }
        
        database.insert(newQuestions);
    }
     
    @isTest
    public static void createExamResults(){
        
        Account testAccount = [SELECT Id FROM Account WHERE Name = 'User'Limit 1];
       	List<Exam__c> testExams = [SELECT Id FROM Exam__c];
        List<Exam_Result__c> newResults = new List<Exam_Result__c>();
        
        for(Exam__c exam: testExams){
                
            	Exam_Result__c newResult = new Exam_Result__c(Exam__c = exam.Id, Account__c = testAccount.Id);
                newResult.Graded__c = true;
                newResults.add(newResult);
            
        }
        
        for(Exam__c exam: testExams){
                
            	Exam_Result__c newResult = new Exam_Result__c(Exam__c = exam.Id, Account__c = testAccount.Id);
                newResult.Graded__c = false;
                newResults.add(newResult);
            
        }
    
        database.insert(newResults);
        
        system.debug(newResults);
    }
    
    
    @isTest
    public static void createAnswers(){
        
        List<Exam_Question__c> newQuestions = [SELECT Id FROM Exam_Question__c];
        List<Exam_Result__c> newResults = [SELECT Id from Exam_Result__c];
        List<Hero_Answer__c> newAnswers = new List<Hero_Answer__c>();
        
        
        for(Exam_Question__c question : newQuestions){
            
            for(Exam_Result__c result : newResults){
            	
            	Hero_Answer__c newAnswer = new Hero_Answer__c(Exam_Question__c = question.id, Exam_Result__c = result.id, Correct__c = true);
                newAnswers.add(newAnswer);
                
            }	
       	}
        
        database.insert(newAnswers);
        
    }
    
    @isTest
    public static void createTeams(){
        List<Team__c> teamList = new List<Team__c>();
        
        Team__c Amplifire = new Team__c(Name='Amplifire');
        Team__c Alchemy = new Team__c(Name='Alchemy');
        Team__c Synergy = new Team__c(Name='Synergy');
        Team__c Vanquish = new Team__c(Name='Vanquish');
        
        teamList.add(Amplifire);
        teamList.add(Alchemy);
        teamList.add(Synergy);
        teamList.add(Vanquish);
        
        database.insert(teamList);
        
    }
    /*
    @isTest
    public static void createSquads(){
        List<Squad__c> squadList = new List<Squad__c>();
        List<Team__c> teamList = [SELECT Id, Name FROM Team__c];
        
        for(Team__c team: teamList){
            if(team.Name == 'Synergy'){
                squadList.add(new Squad__C(Name='TPS Reports', Team__c = team.Id));
            }
            if(team.Name == 'Amplifire'){
                squadList.add(new Squad__C(Name='This is Fire', Team__c = team.Id));
                squadList.add(new Squad__C(Name='Fire is This', Team__c = team.Id));
                squadList.add(new Squad__C(Name='Fire Fire Fire', Team__c = team.Id));
                squadList.add(new Squad__C(Name='FIRE sale', Team__c = team.Id));
            }
            if(team.Name == 'Alchemy'){
                squadList.add(new Squad__C(Name='Wizard_People', Team__c = team.Id));
            }
            if(team.Name == 'Synergy'){
                squadList.add(new Squad__C(Name='Angry Aardvarks', Team__c = team.Id));
            }
        }
        
        database.insert( squadList );
    }
    */
}