TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Account/fields/Squad__c.field-meta.xml
<CustomField>
    <fullName>Squad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The squad of the hero from The Trial of The Titans</description>
    <label>Squad</label>
    <referenceTo>Squad__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hero&apos;s Team in The Trial of The Titans</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/Certification__c.object-meta.xml
<CustomObject>
    <label>Certification</label>
    <nameField>
        <label>Certification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Assessor__c.field-meta.xml
<CustomField>
    <fullName>Assessor__c</fullName>
    <label>Assessor</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Certification_Exam__c.field-meta.xml
<CustomField>
    <fullName>Certification_Exam__c</fullName>
    <label>Certification Exam</label>
    <referenceTo>Certification_Exam__c</referenceTo>
    <relationshipLabel>Certifications</relationshipLabel>
    <relationshipName>Certifications</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Date_Issued__c.field-meta.xml
<CustomField>
    <fullName>Date_Issued__c</fullName>
    <label>Date Issued</label>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <label>Image URL</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Certification__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Certifications</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Certification__c/fields/Verification_Site__c.field-meta.xml
<CustomField>
    <fullName>Verification_Site__c</fullName>
    <label>Verification Site</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Educations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Educations</relationshipLabel>
    <relationshipName>Educations</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <label>Image URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Portfolio_Status__c.field-meta.xml
<CustomField>
    <fullName>Portfolio_Status__c</fullName>
    <label>Portfolio Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Created</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Educations</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/Exam_Question__c.object-meta.xml
<CustomObject>
    <!---->
    <label>Exam Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

P3/force-app/main/default/objects/Exam_Question__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>Total_Correct__c / Total_Answers__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Answer__c/Hero_Answer__c.object-meta.xml
<CustomObject>
    <label>Hero Answer</label>
    <nameField>
        <displayFormat>HA-{0}</displayFormat>
        <label>Hero Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Hero_Answer__c/fields/Exam_Result__c.field-meta.xml
<CustomField>
    <fullName>Exam_Result__c</fullName>
    <label>Exam Result</label>
    <referenceTo>Exam_Result__c</referenceTo>
    <relationshipLabel>Hero Answers</relationshipLabel>
    <relationshipName>Hero_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

HeroHubPackage/main/default/objects/Squad__c/Squad__c.object-meta.xml
<CustomObject>
    <label>Squad</label>
    <nameField>
        <label>Squad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Squads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P3/force-app/main/default/objects/Squad__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

HeroHubPackage/main/default/objects/Squad__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Squads</relationshipLabel>
    <relationshipName>Squads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanPage/Main/default/objects/Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Team a User belongs to.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Titan__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Titans</relationshipLabel>
    <relationshipName>Titans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

HeroHubPackage/main/default/classes/SidebarControllerTest.cls
///////////////////////////////////////////////////////////////////////////////// 
// 
// Name: SidebarControllerTest
// Author: Alan Huang, Andrew Emond
// Created: 01/25/2022
// Updated: 01/25/2022
// Description: Test class for Apex Sidebar
// 
/////////////////////////////////////////////////////////////////////////////////

@isTest
class SidebarControllerTest {
    
    @isTest
    static void getContactTest() {
        Contact soqlContact = [SELECT AccountId FROM Contact WHERE Name='John Smith'];
        Contact contact = SidebarController.getContact();
        System.assertEquals(contact, soqlContact);
    }
    
    @isTest
    static void getAccountTest() {
        Account soqlAccount = [SELECT Name, Squad__c, Team__c, Cohort__c FROM Account WHERE Name='Registrants'];
        Account account = SidebarController.getAccount();
        System.assertEquals(account, soqlAccount);
    }
    
    @isTest
    static void getSquadTest() {
        Squad__c soqlSquad = [SELECT Name FROM Squad__c WHERE Name='Fullmetal'];
        Squad__c squad = SidebarController.getSquad();
        System.assertEquals(squad, soqlSquad);
    }
    
    @isTest
    static void getCertTest() {
        List<Certification__c> soqlCert = [SELECT Name, Assessor__c, Date_Issued__c, Image_URL__c, User__c, Verification_Site__c FROM Certification__c];
        List<Certification__c> cert = SidebarController.getCert();
        System.assertEquals(cert, soqlCert);
    }
    
    @isTest
    static void getPortfolioStatusTest() {
        List<Education__c> soqlEdu = [SELECT Name, Portfolio_Status__c FROM Education__c WHERE Name='State Military'];
        List<Education__c> edu = SidebarController.getPortfolioStatus();
        System.debug(edu);
        System.assertEquals(edu, soqlEdu);
    }
    
    @isTest
    static void getAvgScorePerTitanTest() {
        Id accountId = SidebarController.getAccount().Id;
        List<Titan__c> titans = [SELECT Name FROM Titan__c
                                 WHERE Curriculum__c IN (SELECT Curriculum__c FROM Account WHERE Id=:accountId)];
        List<Id> titanIds = new List<Id>();
        for (Titan__c titan : titans) {
            titanIds.add(titan.Id);
        }
        List<AggregateResult> avgScores = [SELECT AVG(Score__c) AvgScore, Exam__r.Titan__c Id FROM Exam_Result__c
                                           WHERE Exam__r.Titan__c=:titanIds  AND Account__c=:accountId 
                                           GROUP BY Exam__r.Titan__c];
        List<Map<String, Object>> soqlAvgScore = Utils.combineByIds(titans, avgScores);
        
        List<Map<String, Object>> avgScore = SidebarController.getAvgScorePerTitan();
        
        System.assertEquals(avgScore, soqlAvgScore);
    }
    
    @testSetup
    static void testSetup() {
        Curriculum__c curriculum = new Curriculum__c(Name='Salesforce v5.1.1');
        insert curriculum;
        Cohort__c cohort = new Cohort__c(Name='Jan 20');
        insert cohort;
        Team__c team = new Team__c(Name='Alchemy');
        insert team;
        Squad__c squad = new Squad__c(Name='Fullmetal', Team__c=team.Id);
        insert squad;
        Account account = new Account(
            Name='Registrants',
            Squad__c=squad.Id,
            Team__c=team.Id,
            Cohort__c=cohort.Id,
            Curriculum__c=curriculum.Id
        );
        insert account;
        Contact contact = new Contact(
            FirstName='John',
            LastName='Smith',
            AccountId=account.Id
        );
        insert contact;
        
        List<Certification_Exam__c> certExams = new List<Certification_Exam__c>{
        	new Certification_Exam__c(Name='State Alchemist License')
        };
		insert certExams;
        
        Certification__c cert = new Certification__c(
            Certification_Exam__c=certExams[0].Id,
            Date_Issued__c=Date.newInstance(2022, 1, 20),
            Image_URL__c='https://example.com/image.png',
            Verification_Site__c='https://example.com',
            Assessor__c='Amestria',
            Candidate__c = contact.Id,
            User__c=UserInfo.getUserId()
        );
        insert cert;
        
        Education__c edu = new Education__c(
            Name='State Military',
            Portfolio_Status__c='In Progress',
            User__c=UserInfo.getUserId()
        );
        insert edu;
        
        List<Titan__c> titans = new List<Titan__c>{
            new Titan__c(Name='00 - Misc - Lesson 0', Curriculum__c=curriculum.Id, Technology__c='Salesforce'),
            new Titan__c(Name='01 - Declarative - Lesson 1', Curriculum__c=curriculum.Id, Technology__c='Salesforce'),
            new Titan__c(Name='02 - Programmatic - Lesson 2', Curriculum__c=curriculum.Id, Technology__c='Salesforce')    
        };
        insert titans;
        
        List<Exam__c> exams = new List<Exam__c>{
            new Exam__c(Name='Exam 0', Titan__c=titans[0].Id),
            new Exam__c(Name='Exam 1', Titan__c=titans[1].Id),
            new Exam__c(Name='Exam 2', Titan__c=titans[2].Id)
        };
        insert exams;
            
        List<Exam_Result__c> results = new List<Exam_Result__c>{
            new Exam_Result__c(Account__c=account.Id, Exam__c=exams[0].Id),
            new Exam_Result__c(Account__c=account.Id, Exam__c=exams[0].Id),
            new Exam_Result__c(Account__c=account.Id, Exam__c=exams[0].Id)
        };
        insert results;
        
        Exam_Question__c question = new Exam_Question__c(Name='Question 0');
        insert question;
        
        List<Hero_Answer__c> answers = new List<Hero_Answer__c>{
            new Hero_Answer__c(Exam_Result__c=results[0].Id, Exam_Question__c=question.Id, Correct__c=false),
            new Hero_Answer__c(Exam_Result__c=results[0].Id, Exam_Question__c=question.Id, Correct__c=false),
            new Hero_Answer__c(Exam_Result__c=results[1].Id, Exam_Question__c=question.Id, Correct__c=true),
            new Hero_Answer__c(Exam_Result__c=results[1].Id, Exam_Question__c=question.Id, Correct__c=false),
            new Hero_Answer__c(Exam_Result__c=results[2].Id, Exam_Question__c=question.Id, Correct__c=true),
            new Hero_Answer__c(Exam_Result__c=results[2].Id, Exam_Question__c=question.Id, Correct__c=true)    
        };
        insert answers;
    }
    
}