TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/Account/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

TrialoftheTitansPackage/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Assessment object for 1-on-1s, projects, and misc.</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Assessment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Assessment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Misc</fullName>
                <default>true</default>
                <label>Misc</label>
            </value>
            <value>
                <fullName>1-on-1</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>a check box indicating if a cohort is active or not</description>
    <label>Currently Active</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>Total_Correct__c / Total_Answers__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

TrainerHubPackage/main/default/objects/Hero_Assessment__c/Hero_Assessment__c.object-meta.xml
<CustomObject>
    <label>Hero Assessment</label>
    <nameField>
        <displayFormat>HA-{0000}</displayFormat>
        <label>Hero Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Hero_Assessment__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <description>Relating Hero Assessment to Assessment</description>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Hero Assessments</relationshipLabel>
    <relationshipName>Hero_Assessments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrainerHubPackage/main/default/objects/Hero_Assessment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <label>Hero</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hero Assessments</relationshipLabel>
    <relationshipName>Hero_Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Assessment__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <description>Score for assessment.</description>
    <label>Overall Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The hero this QC Interview was for.</description>
    <inlineHelpText>The hero this QC Interview was for.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>QC Interviews can only be associated with a &quot;hero&quot;-type account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Hero</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/QC_Question_Answer__c.object-meta.xml
<CustomObject>
    <label>QC Question Answer</label>
    <nameField>
        <displayFormat>QCA-{000000}</displayFormat>
        <label>QC Question Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QC Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <description>The QC interview this question/answer data were a part of.</description>
    <inlineHelpText>The QC interview this set of questions and answers are a part of.</inlineHelpText>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>QC Question Answers</relationshipLabel>
    <relationshipName>QC_Question_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Score assigned by the interviewer to the hero&apos;s answer.</description>
    <inlineHelpText>Score assigned by the interviewer to the hero&apos;s answer.</inlineHelpText>
    <label>Score</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

TrainerHubPackage/main/default/classes/CurrentCohortController.cls
/////////////////////////////////////////////////////
//
//  Name: CurrentCohortController
//  Author: Kameron Fincher
//  Description: Controller used to grab data for  
//	QC Scores, Exams, and Hero Assessments. It only 
//	grabs the active cohort of the running user/trainer
//	
///////////////////////////////////////////////////
public class CurrentCohortController {
	@AuraEnabled
    public static List<Pair> getData(){
        List<Pair> pr = new List<Pair>();
        
        Id owner = UserInfo.getUserId();
        
        Cohort__c cohort = [SELECT Id, Name, Active__c, OwnerID FROM Cohort__c WHERE Active__c = true AND OwnerID = :owner LIMIT 1];
        Map<Id,Account> accountIds = new Map<ID, Account>([SELECT Id, Cohort__c FROM Account WHERE Cohort__r.Id = :cohort.id]);
        
        Map<String,Decimal> overallScores = new Map<String,Decimal>{'QC'=>0,'Exams'=>0,'Misc'=>0,'1-on-1'=>0,'Project'=>0};
        Map<String,Decimal> assessmentSize = new Map<String,Decimal>{'QC'=>0,'Exams'=>0,'Misc'=>0,'1-on-1'=>0,'Project'=>0};
            
        for(Exam_Result__c ex:[SELECT Exam__r.name, Score__c, Account__r.id FROM Exam_Result__c WHERE Account__r.id IN :accountIds.keySet()]){
            overallScores.put('Exams',overallScores.get('Exams')+ex.Score__c);
            assessmentSize.put('Exams',assessmentSize.get('Exams')+1);
        }
        
        for(Hero_Assessment__c ex:[SELECT Overall_Score__c, Assessment__r.Type__c, Hero__r.Id FROM Hero_Assessment__c WHERE Hero__r.Id IN :accountIds.keySet()]){
            overallScores.put(ex.Assessment__r.Type__c,overallScores.get(ex.Assessment__r.Type__c)+ex.Overall_Score__c);
            assessmentSize.put(ex.Assessment__r.Type__c,assessmentSize.get(ex.Assessment__r.Type__c)+1);
        }
        
        Integer QCMaxScore = 5; // using this to scale scores to 100
        
        // Using QC_Question_Answer__c until the QC_Interview__c has score calculated
        for(QC_Question_Answer__c ex:[SELECT Score__c, QC_Interview__r.Account__r.id FROM QC_Question_Answer__c WHERE QC_Interview__r.Account__r.id IN :accountIds.keySet()]){
            overallScores.put('QC',overallScores.get('QC')+(ex.Score__c*100/QCMaxScore));
            assessmentSize.put('QC',assessmentSize.get('QC')+1);
        }
        
        
        for(String oS : overallScores.keySet()){
            if(assessmentSize.get(oS)!=0){
                overallScores.put(oS,((overallScores.get(oS)/assessmentSize.get(oS)).setScale(2))); // set scale rounds
                pr.add(new Pair(oS,overallScores.get(oS)));
            }
        }

        return pr;
    }
    // Class used for mapping data retrieved into the right format for charts
    public class Pair{
        @AuraEnabled public String name;
        @AuraEnabled public Decimal value;
        public Pair(String name, Decimal value){
            this.name = name;
            this.value = value;
        }
    }
}