TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrainerHubPackage/main/default/objects/Hero_Assessment__c/Hero_Assessment__c.object-meta.xml
<CustomObject>
    <label>Hero Assessment</label>
    <nameField>
        <displayFormat>HA-{0000}</displayFormat>
        <label>Hero Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrainerHubPackage/main/default/objects/Hero_Assessment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <label>Hero</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hero Assessments</relationshipLabel>
    <relationshipName>Hero_Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Assessment__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <description>Score for assessment.</description>
    <label>Overall Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

TrainerHubPackage/main/default/classes/D3GrpChartController.cls
global without sharing class D3GrpChartController {
    @AuraEnabled
    public static Map<String, list<grpBarChart>> getDataMap() {
       Map<String, list<grpBarChart>> groupData=new Map<string, List<grpBarChart>>();
      
        List<Cohort__c> batchList=new List<Cohort__c>([Select Id, Name, Curriculum__r.Name from Cohort__c]);
        List<Hero_Assessment__c> heroAssessmentList=new List<Hero_Assessment__c>([SELECT Id, Hero__r.cohort__r.Name, Hero__r.cohort__r.curriculum__r.name, Overall_Score__c FROM Hero_Assessment__c]);
        Set<String> filteredbatch=new Set<String>();
        
                             
        for(Cohort__c c: batchList){
           filteredbatch.add(c.Name);  
        }
        for(String c: filteredbatch){
            List<grpBarChart> grpList=new List<grpBarChart>();
            
            
            for(Cohort__c cohort: batchList){
                Integer num=0;
                Decimal total=0;
                if(cohort.Name==c){
                    String Name= cohort.Curriculum__r.Name;
                    for (Hero_Assessment__c ha : heroAssessmentList){
                        if (ha.Hero__r.cohort__r.Name==c && ha.Hero__r.cohort__r.curriculum__r.name==Name){
                            num++;
                            total+=ha.Overall_Score__c;
                        }
                    }
                    if(num!=0){
                    Decimal avg=total/num;
                    grpList.add(new grpBarChart(Name, avg));  
                    }else{
                      grpList.add(new grpBarChart(Name, 0));   
                    }
                     
                }
            }
            groupData.put(c, grpList); 
        }
        return groupData;
      }
       
    //Wrapper class
     public class grpBarChart {
        @AuraEnabled public String grpName;
        @AuraEnabled public Decimal grpValue;
         
        public grpBarChart( String grpName, Decimal grpValue ) {
            this.grpName = grpName;
            this.grpValue = grpValue;
        }
   }
}