TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hero&apos;s Team in The Trial of The Titans</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Account/fields/Weekly_Arete_Number__c.field-meta.xml
<CustomField>
    <fullName>Weekly_Arete_Number__c</fullName>
    <label>Weekly Arete Number</label>
    <summarizedField>Weekly_Arete__c.Arete_Amount__c</summarizedField>
    <summaryForeignKey>Weekly_Arete__c.Weekly_Arete_Number__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanPage/Main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanPage/Main/default/objects/Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Team a User belongs to.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/classes/updatedCohortLeaderboardHandler.cls
public with sharing class updatedCohortLeaderboardHandler {
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getUpdatedCohortScore() 
    {
        Contact con = [SELECT AccountId FROM Contact WHERE Email = :UserInfo.getUserEmail()];

        Account objAccount = new Account();
        objAccount = [SELECT Name, Cohort__r.Name, Id FROM Account WHERE Id = :con.AccountId];

        return [SELECT Team__r.Name, AVG(Weekly_Arete_Number__c) FROM Account 
        WHERE Cohort__r.Name = :objAccount.Cohort__r.Name GROUP BY Team__r.Name 
        ORDER BY AVG(Weekly_Arete_Number__c) DESC LIMIT 3];
    }
}