TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Account/fields/Squad__c.field-meta.xml
<CustomField>
    <fullName>Squad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The squad of the hero from The Trial of The Titans</description>
    <label>Squad</label>
    <referenceTo>Squad__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hero&apos;s Team in The Trial of The Titans</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P3/force-app/main/default/objects/Exam__c/fields/Next_Exam__c.field-meta.xml
<CustomField>
    <fullName>Next_Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Next Exam</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The next exam must be within the same Titan!</errorMessage>
        <filterItems>
            <field>Exam__c.Titan__c</field>
            <operation>equals</operation>
            <valueField>$Source.Titan__c</valueField>
        </filterItems>
        <filterItems>
            <field>Exam__c.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Previous Exam</relationshipLabel>
    <relationshipName>Next_Exam</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <formula>IF( ISBLANK( Passing_Grade_Override__c ), ( Total_Correct__c / Total_Answers__c ) &gt;=  Exam__r.Default_Passing_Grade__c, ( Total_Correct__c / Total_Answers__c ) &gt;=  Passing_Grade_Override__c )</formula>
    <label>Pass</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>Total_Correct__c / Total_Answers__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Total_Answers__c.field-meta.xml
<CustomField>
    <fullName>Total_Answers__c</fullName>
    <label>Total Answers</label>
    <summaryForeignKey>Hero_Answer__c.Exam_Result__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Total_Correct__c.field-meta.xml
<CustomField>
    <fullName>Total_Correct__c</fullName>
    <label>Total Correct</label>
    <summaryFilterItems>
        <field>Hero_Answer__c.Correct__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Hero_Answer__c.Exam_Result__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Squad__c/Squad__c.object-meta.xml
<CustomObject>
    <label>Squad</label>
    <nameField>
        <label>Squad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Squads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P3/force-app/main/default/objects/Squad__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Squad__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Squads</relationshipLabel>
    <relationshipName>Squads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HeroHubPackage/main/default/objects/Team__c/fields/In_Lead__c.field-meta.xml
<CustomField>
    <fullName>In_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Lead?</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Team__c/fields/Primary_Color__c.field-meta.xml
<CustomField>
    <fullName>Primary_Color__c</fullName>
    <label>Primary Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

P3/force-app/main/default/objects/Team__c/fields/Secondary_Color__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Color__c</fullName>
    <label>Secondary Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Team__c/fields/Slogan__c.field-meta.xml
<CustomField>
    <fullName>Slogan__c</fullName>
    <label>Slogan</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Team a User belongs to.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Titan__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Titans</relationshipLabel>
    <relationshipName>Titans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/classes/UserContextInfo.cls
/////////////////////////////////////////////////////
//
//  Name: UserContextInfo
//  Author: Josh Miccolo
//  Created: 5/24/2021
//  Updated: 5/25/2021
//  Description: User Context to be return to JavaScript
//  controller in the PageContainer
// 
//
///////////////////////////////////////////////////

public class UserContextInfo {
    
    //account Info
    @auraEnabled 
    public Account acc{get; set;}
    
    //squad Info
    @auraEnabled 
    public Squad__c squad{get; set;}
    
    //Team Info
    @auraEnabled 
    public Team__c team{get; set;}
    
    //Map of Exam Info by Titan and then Exam Name
    @auraEnabled 
    public Map<String, List<ExamList>> userExams {get; set;} 

    //Constructor
    public UserContextInfo( Id userId ){

        acc = getUserAccount( userId );
        
        system.debug('acc' + acc);
        
        squad = getSquad( acc.Squad__c );
        
        System.debug('squad' + squad);
        
        team = getTeam( squad.Team__c );
        
        System.debug('team' + team);
		
        List<Titan__c> allTitans = getAllTitans();
        
        System.debug('allTitans' + allTitans);
        
        List<Exam__c> examList = getExamsWithResults( acc.Id );
        
        System.debug(examList);

        Map<String, List<Exam__c>> sortedExams = sortExams( examList, allTitans );
        
        System.debug('sortedExams' + sortedExams);
        
        userExams = createExamLists( sortedExams );
        
        System.debug('userExams' + userExams);
    }

   	public static Account getUserAccount(Id userId) {
		
        // To be added when user is live
        try{
            User user = [SELECT Id, contactId FROM User WHERE Id = :userId];
        	Contact userContact = [SELECT Id, AccountId FROM Contact WHERE Id = :user.ContactId];
        	Account userAccount = [SELECT Id, Name, Curriculum__c, Squad__c, Team__c, Cohort__c FROM Account WHERE Id = :userContact.AccountId];
            
            //Hard Coded Account for now
        	//Account userAccount = [SELECT Id, Name, Curriculum__c, Squad__c, Cohort__c, Team__c FROM Account WHERE Name = 'User0'];
            
            system.debug(userAccount);
			return userAccount;
        }
        catch(Exception e){
           return [SELECT Id, Name, Curriculum__c, Squad__c, Cohort__c, Team__c FROM Account WHERE Name = 'Gladius Maximus'];
        }
        

        
    }

    private Squad__c getSquad(Id squadId){
        
        system.debug(squadId);

        Squad__c userSquad = [SELECT Id, Name, Team__c FROM Squad__c WHERE id = :squadId LIMIT 1];
        
        system.debug(userSquad);

        return userSquad;

    }

    private Team__c getTeam(Id teamId){

        Team__c userTeam = [SELECT Id, 
                            Name, 
                            Slogan__c, 
                            In_Lead__c, 
                            Primary_Color__c, 
                            Secondary_Color__c 
                            FROM Team__c 
                            WHERE Id = :teamId];

        return userTeam;

    }

    @testVisible
    private List<Titan__C> getAllTitans(){

        List<Titan__c> allTitans = [SELECT Id, Name FROM Titan__C];

        return allTitans;
    
    }

    // Returns a list of exams with a nest list of results
    @testVisible
    private List<Exam__c> getExamsWithResults(Id accId){
        
        List<Exam__c> examsList = [SELECT Id, 
                                    Titan__r.Name, 
                                    Name,
                                    Next_Exam__c,
                                    (SELECT Pass__c, 
                                            Total_Answers__c, 
                                            Total_Correct__C,
                                     		Status__c,
                                            CreatedDate
                                            FROM Exam_Results__r 
                                            WHERE Account__c = :accId 
                                 			ORDER BY Score__c DESC NULLS LAST
                                            )
                                    FROM Exam__c];
    
        return examsList;
    }

    //Maps the Exam Results and other fields to a Titan by Exam Name and sort by prerequisites. 
    private Map<String, List<Exam__c>> sortExams(List<Exam__c> exams, List<Titan__c> allTitans){
		System.debug('In sorting ' + exams + allTitans);
        // Custom DataType to mape names, lists, and numbers in one object
        Map<String, List<Exam__c>> examMap = new Map<String, List<Exam__C>>();
        
        // create all keys
        for(Titan__c titan: allTitans){

            if(examMap.containsKey(titan.Name) != true){

                List<Exam__c> newTitanExams = new List<Exam__c>();
                examMap.put(titan.Name, newTitanExams);
            	System.debug(titan.Name + ' ' +  newTitanExams);
            }
        
        }
        
        // add too key we are populating
        for(Exam__c exam : exams){
         	examMap.get(exam.Titan__R.Name).add(exam);   
        }

        //Sorting algorithm to be added in the future or done with numbers on Exam-Results.
        // Done by James Patton 6/07/2021 baised on insertion sort with first looking at next exam and inserting there without regard for other exams that may have the same next exam
        //   This will cause if a, b, and, c exams have all the same next exam called d in a titan the first exam evaluated in sort will have that has the next exam so could end up as 
        //   a, b, c, d | b, a, c, d | a, d, c, b | b, d, c, a really anything other then d being first
        
        
        for (String key : examMap.keySet()) {
            List<Exam__c> examsToSort = examMap.get(key);
            List<Exam__c> sortedExams = new List<Exam__c>();
            
            //Insertion sort baised on nextExam
            for (Exam__c exam : examsToSort){
                if (sortedExams.size() == 0){
                    sortedExams.add(exam);
                }
                else {
                    boolean spotFound = False;
                    for (Integer sortedExamIndex = 0; sortedExamIndex < sortedExams.size() && spotFound == False; sortedExamIndex++) {
                        if (sortedExams[sortedExamIndex].next_Exam__c == exam.id) {
                            if (sortedExamIndex < sortedExams.size() - 1) {
                                // at end of list so must use .add
                                sortedExams.add(exam);
                            }
                            else{
                                try {
                                	// in the middle so insert at next spot
                                	sortedExams.add(sortedExamIndex + 1, exam);
                                } catch (Exception ex) {
                                    System.debug('Problem here' + sortedExamIndex + sortedExams );
                                }
                            }
                            
                        }
                    }
                    if (spotFound == False){
                        // insert at front or back
                        if (exam.Next_Exam__c == sortedExams[0].Id) {
                            //Insert at front
                            sortedExams.add(0, exam);
                        }
                        else {
                            sortedExams.add(exam);
                        }
                    }
                }
            }
            // set values for map to sorted list
            examMap.put(key, sortedExams);
        }
        
        
        System.debug('End sorting ' + examMap);
        return examMap;
    }
    
    // Creates a custom class object to prepare exams to be mapped to titans. 
    private Map<String, List<ExamList>> createExamLists(Map<String, List<Exam__c>> titanExams){
        //System.debug('In cereateExam List createExamLists');
        Map<String, List<ExamList>> examList = new Map<String, List<ExamList>>();
        //System.debug('In cereateExam examList1 ' + examList);
        for( String key: titanExams.keySet()){
            //System.debug('In cereateExam List key' + key);
            examList.put(key, new List<ExamList>());
            List<ExamList> titanExamList = examList.get(key);
            //System.debug('In cereateExam titanExamList1 ' + titanExamList);
            List<Exam__C> exams = titanExams.get(key);
            //System.debug('In cereateExam exams' + exams);
            for(Exam__C exam: exams){
                //system.debug('In cereateExam exam ' + exam);
               titanExamList.add(new ExamList(exam));
                //system.debug('In cereateExam titanExamList2' + titanExamList);
            }
        }
        //system.debug('In cereateExam List + examList' + examList);
        return examList;
    }
}