TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/Account/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Account/fields/Squad__c.field-meta.xml
<CustomField>
    <fullName>Squad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The squad of the hero from The Trial of The Titans</description>
    <label>Squad</label>
    <referenceTo>Squad__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hero&apos;s Team in The Trial of The Titans</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/Cohort__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>a check box indicating if a cohort is active or not</description>
    <label>Currently Active</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/QC_Interview_Count__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview_Count__c</fullName>
    <description>Total number of QC Interviews this cohort has had, for calculating this cohort&apos;s average QC score (across all weeks)</description>
    <label>QC Interview Count</label>
    <summaryForeignKey>QC_Interview__c.Cohort__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

QCHubPackage/main/default/objects/Cohort__c/fields/QC_Interview_Sum__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview_Sum__c</fullName>
    <description>Sum of QC Interview scores (across all weeks) for calculating average QC score for this cohort (across all weeks)</description>
    <label>QC Interview Sum</label>
    <summarizedField>QC_Interview__c.QC_Score__c</summarizedField>
    <summaryForeignKey>QC_Interview__c.Cohort__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <description>The week for which this interview is conducted.</description>
    <inlineHelpText>The week for which the interview is conducted.</inlineHelpText>
    <label>Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Picklist</valueSetName>
    </valueSet>
</CustomField>

Trial of the Titans/CorePackage/objects/Squad__c/Squad__c.object-meta.xml
<CustomObject>
    <label>Squad</label>
    <nameField>
        <label>Squad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Squads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Squad__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Squads</relationshipLabel>
    <relationshipName>Squads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanPage/Main/default/objects/Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Team a User belongs to.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/globalValueSets/Week_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Week 1</fullName>
    </customValue>
    <customValue>
        <fullName>Week 2</fullName>
    </customValue>
    <customValue>
        <fullName>Week 3</fullName>
    </customValue>
    <customValue>
        <fullName>Week 4</fullName>
    </customValue>
    <customValue>
        <fullName>Week 5</fullName>
    </customValue>
    <customValue>
        <fullName>Week 6</fullName>
    </customValue>
    <customValue>
        <fullName>Week 7</fullName>
    </customValue>
    <customValue>
        <fullName>Week 8</fullName>
    </customValue>
    <customValue>
        <fullName>Week 9</fullName>
    </customValue>
    <customValue>
        <fullName>Week 10</fullName>
    </customValue>
    <customValue>
        <fullName>Week 11</fullName>
    </customValue>
    <customValue>
        <fullName>Week 12</fullName>
    </customValue>
    <masterLabel>Week Picklist</masterLabel>
</GlobalValueSet>

QCHubPackage/main/default/classes/lwcQCHubHomeAuraController.cls
//////////////////////////////////////////////////////////////////////
//
//  Name: QCHubHomeAuraController
//  Author: Alexander Dzhitenov
//  Description: Controller for the QCHubHome Aura Component
//
//////////////////////////////////////////////////////////////////////


public with sharing class lwcQCHubHomeAuraController {


    // Apex controller method fired from QCHubHome Init event - retrieves data about active cohorts
    @AuraEnabled(cacheable=true)
    public static List<Cohort__c> retrieveCohorts(){
        
        return [SELECT Id, Name, QC_Interview_Sum__c, QC_Interview_Count__c FROM Cohort__c WHERE Active__c = true];

    }

    // Return the global picklist value set of weeks used in the org
    @AuraEnabled(cacheable=true)
    public static List<String> retrieveWeeks(){
        System.debug(QC_Interview__c.Week__c.getDescribe().getPicklistValues());

        List<String> weekList = new List<String>();
        List<Schema.PicklistEntry> pickValues = QC_Interview__c.Week__c.getDescribe().getPicklistValues();
        for (Schema.PicklistEntry pickVal : pickValues){
            System.debug(pickVal.getValue());
            weekList.add(pickVal.getValue());
        }
        System.debug(weekList);
        return weekList;
    }

    
    // Apex controller method fired from QCHubHome UpdateCohortEvent event - retrieves detailed data about a
    // single cohort.
    
    @AuraEnabled(cacheable=true)
    public static QCCohortWrapper retrieveCohortData(String cohortStr){
    // QCCohortWrapper contains the following properties: Cohort__c cohort, Map<String, List<Account>> squadMap, and
    // List<QCSquadWrapper> squadList. squadMap (initialized with the above map) probably will not be necessary in the
    // aura component, but is included for now.
    // QCSquadWrapper contains: Squad__c squad, and List<Account> heroes.
    // Overall, cohortData is a QCCohortWrapper type object that stores the cohort that is currently selected,
    // and a list of QCSquadWrapper objects to store each squad in the cohort, and a list of heroes in that squad.
    // It is initialized below.

        Schema.DescribeSObjectResult acctDesc = Account.SObjectType.getDescribe();
		Map<String, Schema.RecordTypeInfo> acctRecTypeMap = acctDesc.getRecordTypeInfosByName();
		Id heroTypeId = acctRecTypeMap.get('Hero').getRecordTypeId();

        Cohort__c cohort = (Cohort__c) JSON.deserialize(cohortStr, Cohort__c.class);

        List<Account> heroList = [SELECT Name, Squad__r.Name, Squad__r.Id, Team__r.Name FROM Account WHERE RecordTypeId=:heroTypeId AND Cohort__r.Name=:cohort.Name];

        Map<String, List<Account>> squadMap = new Map<String, List<Account>>();

        for (Account hero : heroList){
            String currentHeroSquad = hero.Squad__r.Name;
            if (squadMap.containsKey(currentHeroSquad)){
                squadMap.get(currentHeroSquad).add(hero);

            }
            else (squadMap.put(hero.Squad__r.Name, new List<Account>{hero}));

        }

        QCCohortWrapper cohortData = new QCCohortWrapper();
        cohortData.cohort = cohort;
        cohortData.squadMap = squadMap;
        cohortData.heroList = heroList;

        List<Squad__c> squads = [SELECT Id, Name, Team__r.Name FROM Squad__c WHERE Name IN :squadMap.keySet()];

        cohortData.squadList = new List<QCSquadWrapper>();

        for (Squad__c s : squads){
            cohortData.squadList.add(new QCSquadWrapper(s));
        }

        for (QCSquadWrapper squadListElement : cohortData.squadList){
            squadListElement.heroes = squadMap.get(squadListElement.squad.Name);
        }
        
        return cohortData;

    }
}