TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Body_Language__c.field-meta.xml
<CustomField>
    <fullName>Body_Language__c</fullName>
    <label>Body Language</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Confidence__c.field-meta.xml
<CustomField>
    <fullName>Confidence__c</fullName>
    <label>Confidence</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Eye_Contact__c.field-meta.xml
<CustomField>
    <fullName>Eye_Contact__c</fullName>
    <label>Eye Contact</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Feedback__c/fields/Fluency__c.field-meta.xml
<CustomField>
    <fullName>Fluency__c</fullName>
    <label>Fluency</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Mock_Interview_Self__c.field-meta.xml
<CustomField>
    <fullName>Mock_Interview_Self__c</fullName>
    <label>Mock Interview Self</label>
    <referenceTo>Mock_Interview_Self__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Peer</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/objects/MI_Question_Pool__c/MI_Question_Pool__c.object-meta.xml
<CustomObject>
    <label>MI Question Pool</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MI Question Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/MI_Question_Pool__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/MI_Question_Pool__c/fields/Suggested_Answer__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Answer__c</fullName>
    <label>Suggested Answer</label>
    <type>TextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/MI_Question_Pool__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Soft skill</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Mock_Interview_Self__c/Mock_Interview_Self__c.object-meta.xml
<CustomObject>
    <label>Mock Interview Self</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mock Interview Selves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P3/force-app/main/default/objects/Mock_Interview_Self__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mock Interview Selves</relationshipLabel>
    <relationshipName>Mock_Interview_Selves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Mock_Interview_Self__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <formula>Account__r.Cohort__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cohort</label>
    <type>Text</type>
</CustomField>

P3/force-app/main/default/objects/Mock_Interview_Self__c/fields/MI_Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>MI_Question_Pool__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MI Question Pool</label>
    <referenceTo>MI_Question_Pool__c</referenceTo>
    <relationshipLabel>Mock Interview Selves</relationshipLabel>
    <relationshipName>Mock_Interview_Selves3</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Mock_Interview_Self__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Do you want to allow public to see this?</inlineHelpText>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/classes/TrainerResultsTest.cls
/////////////////////////////////////////////////////
//
//  Name: TrainerResultsTest
//  Author: Frank Berni
//  Description: Testing methods for the TrainerResultsAccController which is used by TrainerResultsAccordion Component and its nested components.
//
///////////////////////////////////////////////////

@IsTest
public class TrainerResultsTest {
    
    @TestSetup
    public static void createData(){
        List<Cohort__c> ch = new List<Cohort__c>();
        List<Account> hl = new List<Account>();
        List<MI_Question_Pool__c> qp = new List<MI_Question_Pool__c>();
        List<Mock_Interview_Self__c> mk = new List<Mock_Interview_Self__c>();
        List<Feedback__c> fb = new List<Feedback__c>();
        
        Cohort__c c = new Cohort__c(Name='Test Cohort');
        ch.add(c);
        insert ch;
        
        Account a = new Account(Name='Test Hero',Cohort__c=c.Id);
        hl.add(a);
        insert hl;
        
        MI_Question_Pool__c q = new MI_Question_Pool__c(Type__c='Soft Skill',
                                                         Question__c='Test Question', 
                                                         Suggested_Answer__c='Test Answer');
        qp.add(q);
        insert qp;
        
        Mock_Interview_Self__c m = new Mock_Interview_Self__c(Account__c=a.ID, MI_Question_Pool__c=q.Id, Public__c=true);
        mk.add(m);
        insert m;
        
        Feedback__c f1 = new Feedback__c(Mock_Interview_Self__c=m.Id, 
                                        Type__c='Self',
                                        Confidence__c=3,
                                        Eye_Contact__c=4,
                                        Fluency__c=2,
                                        Body_Language__c=4,
                                        Comments__c='Test Comment');
        Feedback__c f2 = new Feedback__c(Mock_Interview_Self__c=m.Id, 
                                        Type__c='Peer',
                                        Confidence__c=2,
                                        Eye_Contact__c=5,
                                        Fluency__c=3,
                                        Body_Language__c=5,
                                        Comments__c='Test Comment 2');
        fb.add(f1);
        fb.add(f2);
        insert fb;
           
    }
    
    @IsTest
    public static void testGrabHeroes(){
        Test.startTest();
            List<Account> acc = TrainerResultsAccController.grabHeroes();
        Test.stopTest();
        system.assertEquals(acc.size(),1);    
    }
    
    @IsTest
    public static void testGrabCohorts(){
        Test.startTest();
            List<Cohort__c> coh = TrainerResultsAccController.grabCohorts();
        Test.stopTest();
        system.assertEquals(coh.size(),1);    
    }
    
    @IsTest
    public static void testGrabFeedback(){
        String name = 'Test Hero';
        Test.startTest();
            List<Feedback__c> feedback = TrainerResultsAccController.grabFeedback(name);
        Test.stopTest();
        system.assertEquals(feedback.size(),2);    
    }
    
    @IsTest
    public static void testGrabAggHero(){
        String name = 'Test Hero';
        Test.startTest();
            List<aggregateResult> aggH = TrainerResultsAccController.grabAggHero(name);
        Test.stopTest();
        system.assertNotEquals(aggH,Null);
        system.assertEquals(aggH.size(),1);    
    }
    
    @IsTest
    public static void testGrabAggCohort(){
        String name = 'Test Cohort';
        Test.startTest();
            List<aggregateResult> aggC = TrainerResultsAccController.grabAggCohort(name);
        Test.stopTest();
        system.assertNotEquals(aggC,Null);
        system.assertEquals(aggC.size(),1);    
    }

}