TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

CorePackage/main/default/objects/Account/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CorePackage/main/default/objects/Cohort__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Projects listed in the Portfolio.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Project_Review__c/Project_Review__c.object-meta.xml
<CustomObject>
    <label>Project Review</label>
    <nameField>
        <label>Project Review Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Project_Review__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Project Reviews</relationshipLabel>
    <relationshipName>Project_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project_Review__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Project Reviews</relationshipLabel>
    <relationshipName>Project_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project_Review__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Project Reviews</relationshipLabel>
    <relationshipName>Project_Reviews</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/classes/AssignProjectController.cls
/////////////////////////////////////////////////////
//
//  Name: AssignProjectController.cls
//  Author: Jonathan Neilan
//  Description: Initial loading of Accounts (for individual heroes) and Cohorts.
//               On Submit button clicked, assign the Project to all chosen Accounts or Cohorts.
//
///////////////////////////////////////////////////
public with sharing class AssignProjectController {
    
    @AuraEnabled
    public static List<Account> getAccounts(){
        try {
            List<Account> listAccs = [SELECT Id,Name FROM Account];
            return listAccs;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }
    
    @AuraEnabled
    public static List<Cohort__c> getCohorts(){
        try {
            List<Cohort__c> listCohs = [SELECT Id,Name FROM Cohort__c];
            return listCohs;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }
    
    @AuraEnabled
    public static void assignProject(String grouping, String[] namesToAssign, String projectIdToAssign){
            
            if (grouping == 'individual') {
                List <Account> accs = [SELECT Id, Name FROM Account WHERE Name IN :namesToAssign];
                List <Project_Review__c> proRev = new List <Project_Review__c>();
                for (Integer i = 0; i < accs.size(); i++) {
                    Project_Review__c p = new Project_Review__c(Name = accs[i].name + ' Project Assignment');
                    p.Project__c = projectIdToAssign;
                    p.Account__c = accs[i].Id;
                    proRev.add(p);
                }
                try{
                update proRev;
            } catch(Exception e){
                throw new AuraHandledException(e.getMessage());
            }
        }
            else if (grouping == 'cohort') {
                List <Cohort__c> cohs = [SELECT Name,Id FROM Cohort__c WHERE Name IN :namesToAssign];
                List <Project_Review__c> proRev = new List <Project_Review__c>();
                for (Integer i = 0; i < cohs.size(); i++) {
                    Project_Review__c p = new Project_Review__c(Name = cohs[i].name + ' Project Assignment');
                    p.Project__c = projectIdToAssign;
                    p.Account__c = cohs[i].Id;
                    proRev.add(p);
                }
                try{
                    update proRev;
                }catch(Exception e){
                    throw new AuraHandledException(e.getMessage());
                }
            }
            else {
                //error
            }
        } 
    }