TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Account/fields/Squad__c.field-meta.xml
<CustomField>
    <fullName>Squad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The squad of the hero from The Trial of The Titans</description>
    <label>Squad</label>
    <referenceTo>Squad__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hero&apos;s Team in The Trial of The Titans</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>a check box indicating if a cohort is active or not</description>
    <label>Currently Active</label>
    <type>Checkbox</type>
</CustomField>

QCHubPackage/main/default/objects/Cohort__c/fields/Average_Score__c.field-meta.xml
<CustomField>
    <fullName>Average_Score__c</fullName>
    <formula>QC_Interview_Sum__c  /   QC_Interview_Count__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Average Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/QC_Interview_Count__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview_Count__c</fullName>
    <description>Total number of QC Interviews this cohort has had, for calculating this cohort&apos;s average QC score (across all weeks)</description>
    <label>QC Interview Count</label>
    <summaryForeignKey>QC_Interview__c.Cohort__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

QCHubPackage/main/default/objects/Cohort__c/fields/QC_Interview_Sum__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview_Sum__c</fullName>
    <description>Sum of QC Interview scores (across all weeks) for calculating average QC score for this cohort (across all weeks)</description>
    <label>QC Interview Sum</label>
    <summarizedField>QC_Interview__c.QC_Score__c</summarizedField>
    <summaryForeignKey>QC_Interview__c.Cohort__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Curriculum__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technology</label>
    <referenceTo>Technology__c</referenceTo>
    <relationshipLabel>Curricula</relationshipLabel>
    <relationshipName>Curricula</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The hero this QC Interview was for.</description>
    <inlineHelpText>The hero this QC Interview was for.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>QC Interviews can only be associated with a &quot;hero&quot;-type account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Hero</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/Finalized__c.field-meta.xml
<CustomField>
    <fullName>Finalized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this interview has been finalized; determines whether or not it shows up in statistics and analytics.</description>
    <inlineHelpText>Whether or not this interview has been finalized.</inlineHelpText>
    <label>Finalized</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/QC_Score__c.field-meta.xml
<CustomField>
    <fullName>QC_Score__c</fullName>
    <description>Overall score for this hero&apos;s QC. The value is calculated automatically, but can be overridden (a reason must also be provided).</description>
    <inlineHelpText>The overall score for this hero&apos;s QC; the value is calculated automatically, but can be overridden (a reason must also be provided).</inlineHelpText>
    <label>QC Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Assigments__c.field-meta.xml
<CustomField>
    <fullName>Assigments__c</fullName>
    <description>Assignments for the Skills in Trial of the Titans</description>
    <label>Assigments</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Skill_Breakdown__c.field-meta.xml
<CustomField>
    <fullName>Skill_Breakdown__c</fullName>
    <description>Text to describe the skill of a Titan in Trial of the Titans</description>
    <label>Skill Breakdown</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

P3/force-app/main/default/objects/Skill__c/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <description>Type of skill for Skills in Trial of The Titans</description>
    <label>Skill Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coding</fullName>
            </value>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
            <value>
                <fullName>Exams</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Skills</relationshipLabel>
    <relationshipName>Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Squad__c/Squad__c.object-meta.xml
<CustomObject>
    <label>Squad</label>
    <nameField>
        <label>Squad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Squads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

P3/force-app/main/default/objects/Squad__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Squad__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Squads</relationshipLabel>
    <relationshipName>Squads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HeroHubPackage/main/default/objects/Team__c/fields/In_Lead__c.field-meta.xml
<CustomField>
    <fullName>In_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Lead?</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Team__c/fields/Primary_Color__c.field-meta.xml
<CustomField>
    <fullName>Primary_Color__c</fullName>
    <label>Primary Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

P3/force-app/main/default/objects/Team__c/fields/Secondary_Color__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Color__c</fullName>
    <label>Secondary Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Team__c/fields/Slogan__c.field-meta.xml
<CustomField>
    <fullName>Slogan__c</fullName>
    <label>Slogan</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Team__c/fields/Squad_Sum__c.field-meta.xml
<CustomField>
    <fullName>Squad_Sum__c</fullName>
    <label>Squad Sum</label>
    <summarizedField>Squad__c.Score__c</summarizedField>
    <summaryForeignKey>Squad__c.Team__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Team a User belongs to.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Titan__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Titans</relationshipLabel>
    <relationshipName>Titans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CorePackage/main/default/objects/Titan__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Technology for the Titan in Trial of The Titan</description>
    <label>Technology</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <description>Technologies in the Trial of The Titans</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

TrialoftheTitansPackage/main/default/classes/ApexDataFactory.cls
public with sharing class ApexDataFactory {
    static final String HeroTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Hero').getRecordTypeId();
    public static void CreateTeam() {
        //teams variable list
        // Name
        // Squad_Sum__c – Roll up Summary (SUM) of Squad Score__c
        // In_Lead__c – Checkbox

        String[] primaryColors = new List<String>{'red','yellow','blue'};
        String[] secondaryColors = new List<String>{'orange','purple','green'};
        List<String> slogans = new List<String>();
        for(integer i=0; i<100; i++){
            slogans.add('Slogan '+(i+1));
        }
        //////////////////////////////////////
        List<Team__c> teams = new List<Team__c>();
        // create a team

        List<Team__c> comparedTeam = [SELECT Name FROM Team__c];
        Team__c newTeam = new Team__c();
        newTeam.name = 'Team ' + (comparedTeam.size() +1);

        Integer primaryColorsSelection = Integer.valueOf((Math.random()*(primaryColors.size()-1)));
        newTeam.Primary_Color__c = primaryColors[primaryColorsSelection];

        Integer secondaryColorsSelection = Integer.valueOf((Math.random()*(secondaryColors.size()-1)));
        newTeam.Secondary_Color__c = secondaryColors[secondaryColorsSelection];

        Integer sloganSelection = Integer.valueOf((Math.random()*(slogans.size()-1)));
        newTeam.Slogan__c = slogans[sloganSelection];

        Boolean nameTaken = false;
        for (Team__c t : comparedTeam){
            if (t.name == newTeam.name){
                nameTaken = true;
            }
        } 
        if (nameTaken == false){
            teams.add(newTeam);
            insert teams;
        }
        

        /////////////////////////////////////
    }

    public static void CreateSquad(){
        
        //Squad Variables
        //Name
        //Score__c – Number
        //Team__c -  Master detail reference to Team__c Object
        ////////////////////////////////////
        List<Squad__c> squads = new List<Squad__c>();
        List<Team__c> teamIds = [SELECT Id FROM Team__c];
        Integer teamAssignment = Integer.valueOf((Math.random()*(TeamIds.size()-1)));
        // create a squad

        Squad__c newSquad = new Squad__c();
        List<Squad__c> comparedSquad = [SELECT Name FROM Squad__c];
       	newSquad.Name = 'Squad ' + (comparedSquad.size() +1);
        newSquad.Score__c = Integer.valueOf((Math.random()*1000));
     	newSquad.Team__c = teamIds[teamAssignment].Id;
 		
        squads.add(newSquad);
        insert squads;
         //////////////////////////////////
    }

    public static void CreateCurriculum(){
        //curriculum variables list
        // Name
        String[] technology = new List<String> {'Java','Salesforce'};

        //////////////////////////////////////////
        List<Curriculum__c> curriculum = new List<Curriculum__c>();
        
        //create a curriculum
        List<Curriculum__c> comparedCurriculum = [SELECT Name FROM Curriculum__c];
        
        if (comparedCurriculum.size() == 0){
            
            for (integer i=0; i<2; i++){
                Curriculum__c cur = new Curriculum__c();
                cur.Technology__c = technology[i];                
                cur.Name = cur.Technology__c;
                curriculum.add(cur);
            } 
            insert curriculum;
            
            
        }

        ////////////////////////////////
    }

    public static void CreateTitan(){
        /*titans variables list
        Name
        Curriculum__c – Lookup reference to Curriculum__c object
        Number_of_Skills – Roll up Summary (COUNT) of Skill__c
        Technology__c - Picklist 
        */

        ///////////////////////////////////////
        List<Titan__c> titans = new List<Titan__c>();
        List<Curriculum__c> curriculum = [Select Name, Id, Technology__c FROM Curriculum__c];
        //create a titan
        List<Titan__c> comparedTitan = [SELECT Name FROM Titan__c];
        Titan__c newTitan = new Titan__c();
        newTitan.Name = 'Titan ' + (comparedTitan.size() +1);

        Integer curNum = Integer.valueOf((Math.random()*(curriculum.size())));
        newTitan.Curriculum__c = curriculum[curNum].Id;
        newTitan.Technology__c = curriculum[curNum].Technology__c;
		
        titans.add(newTitan);
        insert titans;

        /////////////////////////////
    }

    public static void CreateSkill(){
        // skills variable list
        // using Assigments__c field with typo instead of Assignments__c
        // Name
        // Titan__c – Master Detail Reference to Titan__c Object
        List<String> assignments = new List<String>();
        for(integer i=0; i<100; i++){
            assignments.add('Assignments '+ (i+1));
        }
        List<String> skillsBreakDown = new List<String>();
        for(integer i=0; i<100; i++){
            skillsBreakDown.add('Skills '+(i+1));
        }
        String[] skillTypes = new List<String>{'Coding','Soft Skills', 'Exams', 'Data Management','Design'};

		///////////////////////////////////////
        List<Skill__c> skills = new List<Skill__c>();
        List<Titan__c> titans = [SELECT Id FROM Titan__c];
        // create a skill
        List<Skill__c> comparedSkill = [SELECT Name FROM Skill__c];
        Skill__c newSkill = new Skill__c();
        newSkill.Name = 'Skill ' + (comparedSkill.size() +1);
        newSkill.Assigments__c = 'Assignment ' + (comparedSkill.size() +1);
        newSkill.Skill_Breakdown__c = 'Skill Break Down ' + (comparedSkill.size() +1);
        newSkill.Skill_Type__c = skillTypes[Integer.valueOf((Math.random()*skillTypes.size()))];
        newSkill.Titan__c = titans[0].Id;

        skills.add(newSkill);
        insert skills;

        /////////////////////////////
    }

    public static void CreateCohort(){
        //cohort variables list
        //Name
        //Active__c – checkbox
        //Average_Score__c – Number (QC_Interview_Sum__c/QC_Interview_Count__c)
        //Curriculum__c – reference to Curriculum__c Object
        //QC_Interview_Count__c – Roll Up Summary (COUNT)
        //QC_Interview_Sum__c – Roll Up Summary
		///////////////////////////////////////
		List<Curriculum__c> curriculum = [SELECT Id from Curriculum__c];
        List<Cohort__c> cohorts = new List<Cohort__C>();
        // create a cohort
        List<Cohort__c> comparedCohort = [SELECT Name FROM Cohort__c];
        Cohort__c newCohort = new Cohort__c();
        newCohort.Name = 'Cohort ' + (comparedCohort.size() +1);
        Integer active = Integer.valueOf((Math.random()*99));
        if (active < 75){
            newCohort.Active__c = true;
        }
        newCohort.Curriculum__c = curriculum[Integer.valueOf((Math.random() * (curriculum.size())))].Id;
        
        cohorts.add(newCohort);
        insert cohorts;

        ///////////////////////////////
    }

    public static void CreateAccount(){
        /* accounts variables list
        
        Name
        Email
        Phone
        Cohort__c – Lookup to Cohort__c Object
        Curriculum__c – Lookup to Curriculum__c Object
        Squad__c – Lookup to Squad__c Object
        Team__c –  Lookup to Team__c Object
        */

        ////////////////////////
        List<Account> accounts = new List<Account>(); 
        List<Cohort__c> cohorts = [SELECT Id, Curriculum__c FROM Cohort__c];
        List<Squad__c> squads = [SELECT Id, Team__c FROM Squad__c];
        
        
        //create an account
        List<Account> comparedAcc = [SELECT Name FROM Account];
        Account acc = new Account();
        acc.Phone = '123-456-7890';
        //Account does not have email field
        //acc.Email = 'email ' + (comparedAcc.size() +1);
        acc.Name = 'Account ' + (comparedAcc.size() +1);
        Integer cohortNum = Integer.valueOf((Math.random() * (cohorts.size())));
        acc.Cohort__c = cohorts[cohortNum].Id;
        Integer squadNum = Integer.valueOf((Math.random() * (squads.size())));
        acc.Squad__c = squads[squadNum].Id;
        acc.Team__c = squads[squadNum].Team__c;
        acc.Curriculum__c = cohorts[cohortNum].Curriculum__c;
        acc.RecordTypeId = HeroTypeId;
		
        accounts.add(acc);
        insert accounts;
        /////////////////////////////////////////
    }

    public static void CreateQCInterview(){
        /*qcInterviews variables list
        Name
        Account__c – Lookup reference to Account__c
        Cohort__c – Master detail reference to Cohort__c Object
        Finalized__c – Checkbox
        QC_Score__c - Number
        */
        List<String> weeks = new List<String>();
        for(integer i=0; i<12; i++){
            weeks.add('Week '+(i+1));
        }
        ///////////////////////////////////////////
        List<Account> accounts = [SELECT Id, Cohort__C FROM Account WHERE RecordTypeId =: HeroTypeId];
        system.debug(accounts[0].RecordTypeId);
        List<QC_Interview__c> qcInterviews = new List<QC_Interview__c>();
        
        // create a qc
        List<QC_Interview__c> comparedQC = [SELECT Name FROM QC_Interview__c];
        QC_Interview__c newQC = new QC_Interview__c();
        newQC.Name = 'QC ' + (comparedQC.size() +1); 
        Integer accNum = Integer.valueOf((Math.random() * (accounts.size()-1)));
        newQC.Account__c = accounts[accNum].Id;
        newQC.Cohort__c = accounts[accNum].Cohort__c;
        Integer finalized = Integer.valueOf((Math.random()*99));
        if (finalized < 75){
            newQC.Finalized__c = true;
        }
        newQC.QC_Score__c = Integer.valueOf((Math.random()*100));

        Integer weekSelection = Integer.valueOf((Math.random()*(weeks.size()-1)));
        newQC.Week__c = weeks[weekSelection];

        qcInterviews.add(newQC);
        insert qcInterviews;
        /////////////////////////////////
    }
}