TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/Account/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>a check box indicating if a cohort is active or not</description>
    <label>Currently Active</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Answer__c/Hero_Answer__c.object-meta.xml
<CustomObject>
    <label>Hero Answer</label>
    <nameField>
        <displayFormat>HA-{0}</displayFormat>
        <label>Hero Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The hero this QC Interview was for.</description>
    <inlineHelpText>The hero this QC Interview was for.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>QC Interviews can only be associated with a &quot;hero&quot;-type account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Hero</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/QC_Score__c.field-meta.xml
<CustomField>
    <fullName>QC_Score__c</fullName>
    <description>Overall score for this hero&apos;s QC. The value is calculated automatically, but can be overridden (a reason must also be provided).</description>
    <inlineHelpText>The overall score for this hero&apos;s QC; the value is calculated automatically, but can be overridden (a reason must also be provided).</inlineHelpText>
    <label>QC Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question__c/QC_Question__c.object-meta.xml
<CustomObject>
    <description>Pre-made question for QC Interviews.</description>
    <label>QC Question</label>
    <nameField>
        <label>QC Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Question__c/fields/Question_Body__c.field-meta.xml
<CustomField>
    <fullName>Question_Body__c</fullName>
    <label>Question Body</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/QC_Question_Answer__c.object-meta.xml
<CustomObject>
    <label>QC Question Answer</label>
    <nameField>
        <displayFormat>QCA-{000000}</displayFormat>
        <label>QC Question Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QC Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/Hero_Answer__c.field-meta.xml
<CustomField>
    <fullName>Hero_Answer__c</fullName>
    <description>The answer that was given by the hero.</description>
    <inlineHelpText>The answer that was given by the hero.</inlineHelpText>
    <label>Hero Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <description>The QC interview this question/answer data were a part of.</description>
    <inlineHelpText>The QC interview this set of questions and answers are a part of.</inlineHelpText>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>QC Question Answers</relationshipLabel>
    <relationshipName>QC_Question_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Question_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>The question that was asked during the interview; it could either be from the question deck, or provided directly by the QC Interviewer.</description>
    <inlineHelpText>The question that was asked during the interview.</inlineHelpText>
    <label>Question</label>
    <type>TextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Score assigned by the interviewer to the hero&apos;s answer.</description>
    <inlineHelpText>Score assigned by the interviewer to the hero&apos;s answer.</inlineHelpText>
    <label>Score</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

P3/force-app/main/default/classes/QCHubDataFactory.cls
/////////////////////////////////////////////////////////////////////////////
//
//	Name: QCHubDataFactory
//	Author: Alexander Dzhitenov
//	Additions By: Omer Sade
//  Description: Creates data for testing functionality related to the
//				 QC App.
//  
/////////////////////////////////////////////////////////////////////////////

public class QCHubDataFactory {
    
    // Create a cohort of 20 heroes. Create a QC Interview for each hero, and create 5 questions scored from 0-4 for
    // each interview.
    // cohortName: Name of the cohort.
    // namePrefix: Each hero created has a name from 0-19, prefixed with namePrefix.
    
    public static void dataFactory(String cohortName, String namePrefix){
        Cohort__c testCohort = new Cohort__c(Name=cohortName, Active__c=true);
        insert testCohort;
        
        Schema.DescribeSObjectResult acctDesc = Account.SObjectType.getDescribe();
		Map<String, Schema.RecordTypeInfo> acctRecTypeMap = acctDesc.getRecordTypeInfosByName();
		Id heroTypeId = acctRecTypeMap.get('Hero').getRecordTypeId();
        
        List<Account> testAcct = new List<Account>();
        
        for (integer acctNum=0; acctNum<20; ++acctNum){
            Account a = new Account(Name=namePrefix+String.valueOf(acctNum), RecordTypeId=heroTypeId, Cohort__c=testCohort.Id);
            testAcct.add(a);
            
        }
        
        insert testAcct;
        
        List<QC_Interview__c> QCInterviewList = new List<QC_Interview__c>();
        for (Account a : testAcct){
        	QC_Interview__c newInterview = new QC_Interview__c(Name=a.Name+'QC '+namePrefix,
                                                               Cohort__c=testCohort.Id, Account__c=a.Id, QC_Score__c = Math.random() * 5);
            QCInterviewList.add(newInterview);
            
        }
        
		insert QCInterviewList;
        
        List<QC_Question__c> QCQuestionsList = new List<QC_Question__c>();
        for (QC_Interview__c QCInt : QCInterviewList){
            for (integer qcQstCount=0; qcQstCount<5; ++qcQstCount){
                QC_Question__c qcQst = new QC_Question__c(Name='Question' + qcQstCount, Question_Body__c='The question ');
                QCQuestionsList.add(qcQst);
                
            }
            
        }
        
        insert QCQuestionsList;

        List<QC_Question_Answer__c> QCAnswersList = new List<QC_Question_Answer__c>();
        for (QC_Interview__c QCInt : QCInterviewList){
            for (integer qcAnsCount=0; qcAnsCount<5; ++qcAnsCount){
                QC_Question_Answer__c qcAns = new QC_Question_Answer__c(Question__c='Question: ',Hero_Answer__c='Answer: ',
                                                                        Score__c=qcAnsCount, QC_Interview__c=QCInt.Id);
                QCAnswersList.add(qcAns);
                
            }
            
        }
        
        insert QCAnswersList;
        
    }
    
}