TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/Account/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Account/fields/Squad__c.field-meta.xml
<CustomField>
    <fullName>Squad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The squad of the hero from The Trial of The Titans</description>
    <label>Squad</label>
    <referenceTo>Squad__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Flag__c/QC_Flag__c.object-meta.xml
<CustomObject>
    <description>Added to a hero&apos;s QC Interview to note comments about the interview.</description>
    <label>QC Flag</label>
    <nameField>
        <label>QC Flag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Flags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Flag__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Flags can only be placed on a hero.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Hero</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QC Flags</relationshipLabel>
    <relationshipName>QC_Flags</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Flag__c/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>QC Flags</relationshipLabel>
    <relationshipName>QC_Flags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The hero this QC Interview was for.</description>
    <inlineHelpText>The hero this QC Interview was for.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>QC Interviews can only be associated with a &quot;hero&quot;-type account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Hero</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Finalized__c.field-meta.xml
<CustomField>
    <fullName>Finalized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this interview has been finalized; determines whether or not it shows up in statistics and analytics.</description>
    <inlineHelpText>Whether or not this interview has been finalized.</inlineHelpText>
    <label>Finalized</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/QC_Score__c.field-meta.xml
<CustomField>
    <fullName>QC_Score__c</fullName>
    <description>Overall score for this hero&apos;s QC. The value is calculated automatically, but can be overridden (a reason must also be provided).</description>
    <inlineHelpText>The overall score for this hero&apos;s QC; the value is calculated automatically, but can be overridden (a reason must also be provided).</inlineHelpText>
    <label>QC Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Squad__c/Squad__c.object-meta.xml
<CustomObject>
    <label>Squad</label>
    <nameField>
        <label>Squad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Squads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/classes/QCInterviewHeroReviewAuraController.cls
public with sharing class QCInterviewHeroReviewAuraController {

    //init to load score for hero in order to finalize
    @AuraEnabled
    public static QC_Interview__c getInterview(Cohort__c cohort, Account hero){
        try {
            String id = cohort.id;
            String id2 = hero.id;
            List<QC_Interview__c> qci = [SELECT Name, Cohort__r.Name, Account__r.Squad__r.Name, Finalized__c, Account__r.Name, QC_Score__c 
                                        FROM QC_Interview__c
                                        WHERE Finalized__c=false AND Cohort__c=:id AND Account__c=:id2
                                        LIMIT 1];
            return qci[0];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void setFlags(List<QC_Flag__c> flags){
        try {
            insert flags;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled
    public static void setInterview(QC_Interview__c interview){
        try {
            upsert interview;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    // @AuraEnabled
    // public static void set(){
    //     try {
            
    //     } catch (Exception e) {
    //         throw new AuraHandledException(e.getMessage());
    //     }
    // }

}