TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Body_Language__c.field-meta.xml
<CustomField>
    <fullName>Body_Language__c</fullName>
    <label>Body Language</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <type>TextArea</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Confidence__c.field-meta.xml
<CustomField>
    <fullName>Confidence__c</fullName>
    <label>Confidence</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Eye_Contact__c.field-meta.xml
<CustomField>
    <fullName>Eye_Contact__c</fullName>
    <label>Eye Contact</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Feedback__c/fields/Fluency__c.field-meta.xml
<CustomField>
    <fullName>Fluency__c</fullName>
    <label>Fluency</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Mock_Interview_Self__c.field-meta.xml
<CustomField>
    <fullName>Mock_Interview_Self__c</fullName>
    <label>Mock Interview Self</label>
    <referenceTo>Mock_Interview_Self__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Peer</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Mock_Interview_Self__c/Mock_Interview_Self__c.object-meta.xml
<CustomObject>
    <label>Mock Interview Self</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mock Interview Selves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P3/force-app/main/default/objects/Mock_Interview_Self__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mock Interview Selves</relationshipLabel>
    <relationshipName>Mock_Interview_Selves</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Mock_Interview_Self__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <formula>Account__r.Cohort__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cohort</label>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/classes/TrainerResultsAccController.cls
/////////////////////////////////////////////////////
//
//  Name: TrainerResultsAccController
//  Author: Frank Berni
//  Description: AuraEnabled Methods for querying feedback and heros as well as aggregate averages for Hero and Cohort 
//  				
//
///////////////////////////////////////////////////

public class TrainerResultsAccController {
    
    
    //Relationships in Package (child to parent): Feedback > Mock Interview > Account > Cohort
    @AuraEnabled
    public static List<Feedback__c> grabFeedback(String name){
        List<Feedback__c> h = [SELECT Id, Name, Confidence__c, Body_Language__c, Eye_Contact__c, Fluency__c, Comments__c, Type__c, Mock_Interview_Self__r.Account__r.Name  FROM Feedback__c 
                               WHERE Mock_Interview_Self__r.Account__r.Name =:name];
        //system.debug(h);
        return h;
    }
    
    //Grabbing a list of Heroes
     @AuraEnabled
    public static List<Account> grabHeroes(){
        List<Account> h = [SELECT Id, Name, Cohort__r.Name FROM Account];
        //system.debug(h);
        return h;
    }
    
    //Grabbing a list of Cohorts
     @AuraEnabled
    public static List<Cohort__c> grabCohorts(){
        List<Cohort__c> c = [SELECT Id, Name FROM Cohort__c];
        return c;
    }
    
    //Enter name of a Hero as the parameter
    @AuraEnabled
    public static List<aggregateResult> grabAggHero(String name){
        //Pulling Average of all Feedback scores from a Hero
        List<aggregateResult> hero = [SELECT Mock_Interview_Self__r.Account__r.Name, 
                                      Avg(Body_Language__c), Avg(Confidence__c), Avg(Eye_Contact__c), Avg(Fluency__c)
                                     FROM Feedback__c 
                                     WHERE Mock_Interview_Self__r.Account__r.Name =:name 
                                     GROUP BY Mock_Interview_Self__r.Account__r.Name];
        
        return hero;
    }
    
    //Enter name of the Cohort as the parameter
    @AuraEnabled
    public static List<aggregateResult> grabAggCohort(String name){
        //Pulling Average of all scores from everyone in a cohort
        List<aggregateResult> cohTotal = [SELECT Mock_Interview_Self__r.Account__r.Cohort__r.Name, 
                                          Avg(Body_Language__c), Avg(Confidence__c), Avg(Eye_Contact__c), Avg(Fluency__c) 
                                         FROM Feedback__c 
                                         WHERE Mock_Interview_Self__r.Account__r.Cohort__r.Name =:name
                                         GROUP BY Mock_Interview_Self__r.Account__r.Cohort__r.Name];
        
        //system.debug(cohTotal);
        Return cohTotal;     
    }

}