TrialoftheTitansPackage/main/default/objects/Account/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cohort for the Account</description>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

QCHubPackage/main/default/objects/Account/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Curriculum__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technology</label>
    <referenceTo>Technology__c</referenceTo>
    <relationshipLabel>Curricula</relationshipLabel>
    <relationshipName>Curricula</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Answer__c/Hero_Answer__c.object-meta.xml
<CustomObject>
    <label>Hero Answer</label>
    <nameField>
        <displayFormat>HA-{0}</displayFormat>
        <label>Hero Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The hero this QC Interview was for.</description>
    <inlineHelpText>The hero this QC Interview was for.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>QC Interviews can only be associated with a &quot;hero&quot;-type account.</errorMessage>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Hero</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/Finalized__c.field-meta.xml
<CustomField>
    <fullName>Finalized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not this interview has been finalized; determines whether or not it shows up in statistics and analytics.</description>
    <inlineHelpText>Whether or not this interview has been finalized.</inlineHelpText>
    <label>Finalized</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/QC_Score__c.field-meta.xml
<CustomField>
    <fullName>QC_Score__c</fullName>
    <description>Overall score for this hero&apos;s QC. The value is calculated automatically, but can be overridden (a reason must also be provided).</description>
    <inlineHelpText>The overall score for this hero&apos;s QC; the value is calculated automatically, but can be overridden (a reason must also be provided).</inlineHelpText>
    <label>QC Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <description>The week for which this interview is conducted.</description>
    <inlineHelpText>The week for which the interview is conducted.</inlineHelpText>
    <label>Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Picklist</valueSetName>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question__c/QC_Question__c.object-meta.xml
<CustomObject>
    <description>Pre-made question for QC Interviews.</description>
    <label>QC Question</label>
    <nameField>
        <label>QC Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Question__c/fields/Expected_Answer__c.field-meta.xml
<CustomField>
    <fullName>Expected_Answer__c</fullName>
    <label>Expected Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question__c/fields/Question_Body__c.field-meta.xml
<CustomField>
    <fullName>Question_Body__c</fullName>
    <label>Question Body</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/QC_Question_Answer__c.object-meta.xml
<CustomObject>
    <label>QC Question Answer</label>
    <nameField>
        <displayFormat>QCA-{000000}</displayFormat>
        <label>QC Question Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QC Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/Expected_Answer__c.field-meta.xml
<CustomField>
    <fullName>Expected_Answer__c</fullName>
    <description>Answer that was expected, based on the question given.</description>
    <inlineHelpText>Answer that was expected, based on the question given.</inlineHelpText>
    <label>Expected Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/Hero_Answer__c.field-meta.xml
<CustomField>
    <fullName>Hero_Answer__c</fullName>
    <description>The answer that was given by the hero.</description>
    <inlineHelpText>The answer that was given by the hero.</inlineHelpText>
    <label>Hero Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <description>The QC interview this question/answer data were a part of.</description>
    <inlineHelpText>The QC interview this set of questions and answers are a part of.</inlineHelpText>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>QC Question Answers</relationshipLabel>
    <relationshipName>QC_Question_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Question_Answer__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <description>The question that was asked during the interview; it could either be from the question deck, or provided directly by the QC Interviewer.</description>
    <inlineHelpText>The question that was asked during the interview.</inlineHelpText>
    <label>Question</label>
    <type>TextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <description>Score assigned by the interviewer to the hero&apos;s answer.</description>
    <inlineHelpText>Score assigned by the interviewer to the hero&apos;s answer.</inlineHelpText>
    <label>Score</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Titan__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Titans</relationshipLabel>
    <relationshipName>Titans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CorePackage/main/default/objects/Titan__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Technology for the Titan in Trial of The Titan</description>
    <label>Technology</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <description>Technologies in the Trial of The Titans</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

QCHubPackage/main/default/globalValueSets/Week_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Week 1</fullName>
    </customValue>
    <customValue>
        <fullName>Week 2</fullName>
    </customValue>
    <customValue>
        <fullName>Week 3</fullName>
    </customValue>
    <customValue>
        <fullName>Week 4</fullName>
    </customValue>
    <customValue>
        <fullName>Week 5</fullName>
    </customValue>
    <customValue>
        <fullName>Week 6</fullName>
    </customValue>
    <customValue>
        <fullName>Week 7</fullName>
    </customValue>
    <customValue>
        <fullName>Week 8</fullName>
    </customValue>
    <customValue>
        <fullName>Week 9</fullName>
    </customValue>
    <customValue>
        <fullName>Week 10</fullName>
    </customValue>
    <customValue>
        <fullName>Week 11</fullName>
    </customValue>
    <customValue>
        <fullName>Week 12</fullName>
    </customValue>
    <masterLabel>Week Picklist</masterLabel>
</GlobalValueSet>

PortfolioPackage/main/default/classes/IterationElevenTestCoverageFill2Test.cls
@isTest 
public with sharing class IterationElevenTestCoverageFill2Test {
    
    @TestSetup
    static void makeData(){
        List<QC_Question__c> myQC = new List<QC_Question__c>();
        for(Integer i = 0; i < 5; i++)
        {
            QC_Question__c q = new QC_Question__c(Name=('QCQuestion'+i), Question_Body__c='Lorem Ipsum Dolor');
            myQC.add(q);
        }

        insert myQC;

        Curriculum__c cuc = new Curriculum__c(Name='ApexTesting');
        insert cuc;

        Account a = new Account(Name='Faker', RecordTypeId=Schema.SObjectType.account.getRecordTypeInfosByName().get('Hero').getRecordTypeId());
        insert a;

        Titan__c tc = new Titan__c(Name='Salesforce', Technology__c='Salesforce', Curriculum__c=cuc.Id);
        insert tc;

        Cohort__c coc = new Cohort__c(Name='Jan18');
        insert coc;
        
        QC_Interview__c qcic = new QC_Interview__c(Account__c=a.Id, Cohort__c=coc.id,
        Finalized__c=true, Name='Interview 1', QC_Score__c=100, Week__c='Week 12');
        insert qcic;
        
        QC_Question_Answer__c qcqac = new QC_Question_Answer__c(Expected_Answer__c='Frogs',
        Hero_Answer__c='Frogs', QC_Interview__c=qcic.Id, Question__c='Hops, Was A Biblical Plague', Score__c=100);
        
        insert qcqac;
    }

    @isTest 
    public static void uploadInterviewDataTest()
    {
        List<Id> listIds = new List<Id>();

        try 
        {
            QCQuestionEditController.getQuestion();
        }
        catch (Exception e)
        {
            System.assert(e.getMessage()!=null);
        }

        for(QC_Question__c q : [SELECT Id FROM QC_Question__c])
        {
            listIds.add(q.Id);
        }

        try 
        {
            QCQuestionEditController.deleteQuestions(listIds);
        }
        catch (Exception e)
        {
            System.assert(e.getMessage()!=null);
        }

        try 
        {
            Id temp = (Id) '123456789123456798';
            listIds = new List<Id>{temp};
            QCQuestionEditController.deleteQuestions(listIds);
        }
        catch (Exception e)
        {
            System.assert(true, 'Error handled properly');
        }

    }

    @isTest 
    public static void lightningLoginFormTest()
    {
        System.assert(LightningLoginFormController.getForgotPasswordUrl()==null);

        try 
        {
            LightningLoginFormController.setExperienceId(null);
        }
        catch (Exception e)
        {
            System.assert(e.getMessage()!=null);
        }

        System.assertEquals('This method can be invoked only from within a community.', LightningLoginFormController.setExperienceId('Testing'));

        try 
        {
            LightningForgotPasswordController.setExperienceId(null);
        }
        catch (Exception e)
        {
            System.assert(e.getMessage()!=null);
        }

        System.assertEquals('This method can be invoked only from within a community.', LightningForgotPasswordController.setExperienceId('Testing'));

    }

    @isTest 
    public static void TitanPageApexTest()
    {
        Titan__c tc = [SELECT Id FROM Titan__c WHERE Name='Salesforce'];

        List<Exam__c> lec = TitanPageApexController.getExams(tc.Id);
        List<Titan__c> ltc = TitanPageApexController.getTitansList();

    }

    @isTest 
    public static void QCInterviewHeroReviewTest()
    {
        Cohort__c coc = new Cohort__c(Name='Jan18');
        insert coc;
        Account a = new Account(Name='TestUser',RecordTypeId=Schema.SObjectType.account.getRecordTypeInfosByName().get('Hero').getRecordTypeId());
        insert a;
        String week = 'Week 2';
        List<String> fakeList = new List<String>();
        QC_Question_Answer__c qcqc = [SELECT Id,Expected_Answer__c, Hero_Answer__c,
        QC_Interview__c, Question__c, Score__c FROM QC_Question_Answer__c wHERE Question__c = 'Hops, Was A Biblical Plague'];
        qcqc.id = null;
        fakeList.add(JSON.serialize(qcqc));
        String fname = 'Ferris';
        String descr = 'Idk A Problem';
        String ftype = 'Dress Code';

        String interviewId = QCInterviewHeroReviewAuraController.UploadInterviewData(coc.Id, a.Id, a.Name, week, fakeList, fname, descr, ftype);
    }
}