TrialoftheTitansPackage/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hero&apos;s Team in The Trial of The Titans</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

TrialoftheTitansPackage/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Assessment object for 1-on-1s, projects, and misc.</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Assessment__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>General description of assessment</description>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Assessment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Assessment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Misc</fullName>
                <default>true</default>
                <label>Misc</label>
            </value>
            <value>
                <fullName>1-on-1</fullName>
            </value>
            <value>
                <fullName>Project</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrainerHubPackage/main/default/objects/Hero_Assessment__c/Hero_Assessment__c.object-meta.xml
<CustomObject>
    <label>Hero Assessment</label>
    <nameField>
        <displayFormat>HA-{0000}</displayFormat>
        <label>Hero Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Hero_Assessment__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <description>Relating Hero Assessment to Assessment</description>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Hero Assessments</relationshipLabel>
    <relationshipName>Hero_Assessments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrainerHubPackage/main/default/objects/Hero_Assessment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <label>Hero</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hero Assessments</relationshipLabel>
    <relationshipName>Hero_Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Assessment__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <description>Score for assessment.</description>
    <label>Overall Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanPage/Main/default/objects/Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Team a User belongs to.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrainerHubPackage/main/default/classes/AssessmentSetup.cls
/////////////////////////////////////////////////////
//
//  Name: AssessmentSetup
//  Author: Kameron Fincher
//  Description: Utility class to create new data for 
//	the Cohort Page and Trainer Hub. It is ideal to 
//	run UserAccountSetup.UserSetup prior to this.
//	
///////////////////////////////////////////////////
public class AssessmentSetup {
    // Creates assement and hero assessment objects, associating them with existing heroes (accounts)
    public static void Setup(){
        List<Assessment__c> assessmentList = new List<Assessment__c>();
        
        assessmentList.add(new Assessment__c(Name = 'One on One', Type__c='1-on-1', Description__c='A check-in and mock interview with Heroes'));
        assessmentList.add(new Assessment__c(Name = 'Project 0', Type__c='Project', Description__c='Heroes will model a business of their choosing with a Lightning app'));
        assessmentList.add(new Assessment__c(Name = 'Project 1', Type__c='Project', Description__c='Heroes will create an experience cloud site using Visualforce Pages'));
        assessmentList.add(new Assessment__c(Name = 'Project 2', Type__c='Project', Description__c='Heroes will create an experience cloud site using Aura Components, while implementing Sales Cloud and Service Cloud solutions'));
        assessmentList.add(new Assessment__c(Name = 'Coding Challenge', Type__c='Misc', Description__c='A general coding challenge to see where Heroes are programming-wise'));
        
        insert assessmentList;
        
        List<Account> userAccount = [SELECT Name, Team__c from Account]; 
        List<Hero_Assessment__c> heroAssessmentList = new List<Hero_Assessment__c>();
        
        for(Assessment__c a : assessmentList){
            for(Account acc : userAccount){
                if(acc.Team__c!=null){
                    Hero_Assessment__c tempHeroAssessment = new Hero_Assessment__c(Hero__c=acc.id,Assessment__c=a.id);
                    tempHeroAssessment.Overall_Score__c = (Math.random()*50)+50;
                    heroAssessmentList.add(tempHeroAssessment);
                }
            }
        }
        
       insert heroAssessmentList;
        
    }
}