TrainerHubPackage/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrainerHubPackage/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrainerHubPackage/main/default/classes/ProjectHomeController.cls
/////////////////////////////////////////////////////
//
//  Name: Project Home Controller
//  Author: Laurent Sanou
//  Description: this controller pulls all the project  
//  			 records from the database for the list
//  			 to be displayed on the project home page
//  			 
///////////////////////////////////////////////////


public with sharing class ProjectHomeController {
    
    //retrieveProjects() function fetches all Project__c records to be displayed
    //on the projects home page
    
    @Auraenabled
    public static List<Project__c> retrieveProjects(){
        try{
            final List<Project__c> projects = [SELECT Name, Description__c FROM Project__c ORDER BY Name];
            return projects;
        }catch(Exception ex){
            CalloutException e = new CalloutException();
            e.setMessage('Unexpected error: we were unable to retrive the list of projects');
            throw e;
        }

    }
}