TrainerHubPackage/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrainerHubPackage/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrainerHubPackage/main/default/classes/ProjectHomeControllerTest.cls
@isTest
public class ProjectHomeControllerTest {

    @testSetup static void setup() {
        // Create common test accounts
        List<Project__c> testAccts = new List<Project__c>();
        for(Integer i=0 ; i < 2; i++) {
            Project__c project =  new Project__c(Name = 'Test ${i} ');
            project.Description__c = 'description ${i}';
        }
        insert testAccts;        
    }
}