TrialoftheTitansPackage/main/default/objects/One_on_One__c/One_on_One__c.object-meta.xml
<CustomObject>
    <label>One on One</label>
    <nameField>
        <label>One on One Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>One on Ones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/One_on_One__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <label>Hero</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>One on Ones</relationshipLabel>
    <relationshipName>One_on_Ones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

TrialoftheTitansPackage/main/default/objects/One_on_One__c/fields/Internal_Comments__c.field-meta.xml
<CustomField>
    <fullName>Internal_Comments__c</fullName>
    <label>Internal Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

P3/force-app/main/default/objects/One_on_One__c/fields/Personal_Comments__c.field-meta.xml
<CustomField>
    <fullName>Personal_Comments__c</fullName>
    <label>Personal Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/One_on_One__c/fields/Professionalism__c.field-meta.xml
<CustomField>
    <fullName>Professionalism__c</fullName>
    <inlineHelpText>Ability to act and present a professional demeanor and appearance.</inlineHelpText>
    <label>Professionalism</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrainerHubPackage/main/default/objects/One_on_One__c/fields/Soft_Skill_Confidence__c.field-meta.xml
<CustomField>
    <fullName>Soft_Skill_Confidence__c</fullName>
    <inlineHelpText>Ability to project a sense of being a subject matter expert.</inlineHelpText>
    <label>Soft Skill Confidence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/One_on_One__c/fields/Soft_Skill_Fluency__c.field-meta.xml
<CustomField>
    <fullName>Soft_Skill_Fluency__c</fullName>
    <inlineHelpText>Ability to speak effectively with minimal disfluency or other factors.</inlineHelpText>
    <label>Soft Skill Fluency</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrainerHubPackage/main/default/objects/One_on_One__c/fields/Technical_Accuracy__c.field-meta.xml
<CustomField>
    <fullName>Technical_Accuracy__c</fullName>
    <inlineHelpText>Ability to accurately explain and describe things related to the technology.</inlineHelpText>
    <label>Technical Accuracy</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/One_on_One__c/fields/Technical_Fluency__c.field-meta.xml
<CustomField>
    <fullName>Technical_Fluency__c</fullName>
    <inlineHelpText>Ability to use correct technical terminology when discussing the technology.</inlineHelpText>
    <label>Technical Fluency</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

P3/force-app/main/default/objects/One_on_One__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <label>Week</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
            </value>
            <value>
                <fullName>B</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/classes/HeroOneOnOneControllerTest.cls
@IsTest
private class HeroOneOnOneControllerTest {
    @TestSetup
    static void makeData(){
        Account a = new Account(Name='Perseus Eurymedon');
        insert a;
        One_On_One__c testHero = new One_On_One__c(Hero__c = a.id, Week__c = '2', 	Professionalism__c = 6, 
                                                   Soft_Skill_Confidence__c = 8, Soft_Skill_Fluency__c	= 7, Technical_Accuracy__c = 8,
                                                  Technical_Fluency__c = 7, Internal_Comments__c = 'Bad', Personal_Comments__c = 'Bene');
        insert testHero;
    }
    @IsTest
    public static void HeroOneOnOneControllerTest() { 
        test.startTest();
        Account a = [SELECT Id FROM Account WHERE Name = 'Perseus Eurymedon' LIMIT 1];

        Contact c = new Contact(lastname='Fake', firstname='Definitely', AccountId=a.Id);
        insert c;
        Profile p = [SELECT Id FROM Profile WHERE Name='Customer Community User'];
        User u = new User(Alias = 'faker', Email='fakeUser@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='fakeUser@testorg.com',
            ContactId = c.id);
        insert u;


        One_On_One__c testQuery = HeroOneOnOneController.getOneOnOneId(u.Id, '2');
        test.stopTest();
		String testId = testQuery.Id;
        
        System.assertEquals(testId, testQuery.Id);
        System.assertNotEquals('a0T5f000000FDtTEAW', testQuery.Id);
    }
}