MockInterviewPackage/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Body_Language__c.field-meta.xml
<CustomField>
    <fullName>Body_Language__c</fullName>
    <label>Body Language</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Confidence__c.field-meta.xml
<CustomField>
    <fullName>Confidence__c</fullName>
    <label>Confidence</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Eye_Contact__c.field-meta.xml
<CustomField>
    <fullName>Eye_Contact__c</fullName>
    <label>Eye Contact</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Feedback__c/fields/Fluency__c.field-meta.xml
<CustomField>
    <fullName>Fluency__c</fullName>
    <label>Fluency</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Mock_Interview_Self__c.field-meta.xml
<CustomField>
    <fullName>Mock_Interview_Self__c</fullName>
    <label>Mock Interview Self</label>
    <referenceTo>Mock_Interview_Self__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Peer</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MockInterviewPackage/main/default/objects/MI_Question_Pool__c/MI_Question_Pool__c.object-meta.xml
<CustomObject>
    <label>MI Question Pool</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MI Question Pools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MockInterviewPackage/main/default/objects/MI_Question_Pool__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MockInterviewPackage/main/default/objects/MI_Question_Pool__c/fields/Suggested_Answer__c.field-meta.xml
<CustomField>
    <fullName>Suggested_Answer__c</fullName>
    <label>Suggested Answer</label>
    <type>TextArea</type>
</CustomField>

MockInterviewPackage/main/default/objects/MI_Question_Pool__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Soft Skill</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MockInterviewPackage/main/default/objects/Mock_Interview_Self__c/Mock_Interview_Self__c.object-meta.xml
<CustomObject>
    <label>Mock Interview Self</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mock_Interview_Selfs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MockInterviewPackage/main/default/objects/Mock_Interview_Self__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Mock_Interview_Selfs</relationshipLabel>
    <relationshipName>Mock_Interview_Selfs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MockInterviewPackage/main/default/objects/Mock_Interview_Self__c/fields/MI_Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>MI_Question_Pool__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MI Question Pool</label>
    <referenceTo>MI_Question_Pool__c</referenceTo>
    <relationshipLabel>Mock_Interview_Selfs</relationshipLabel>
    <relationshipName>Mock_Interview_Selfs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Mock_Interview_Self__c/fields/MI_Question_Pool_Other__c.field-meta.xml
<CustomField>
    <fullName>MI_Question_Pool_Other__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MI Question Pool Other</label>
    <referenceTo>MI_Question_Pool__c</referenceTo>
    <relationshipLabel>Mock Interview Selves (MI Question Pool Other)</relationshipLabel>
    <relationshipName>Mock_Interview_Selves2</relationshipName>
    <type>Lookup</type>
</CustomField>

MockInterviewPackage/main/default/objects/Mock_Interview_Self__c/fields/MI_Question_Pool_Soft_Skill__c.field-meta.xml
<CustomField>
    <fullName>MI_Question_Pool_Soft_Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MI Question Pool Soft Skill</label>
    <referenceTo>MI_Question_Pool__c</referenceTo>
    <relationshipLabel>Mock Interview Selves</relationshipLabel>
    <relationshipName>Mock_Interview_Selves</relationshipName>
    <type>Lookup</type>
</CustomField>

MockInterviewPackage/main/default/objects/Mock_Interview_Self__c/fields/MI_Question_Pool_Tech_Skill__c.field-meta.xml
<CustomField>
    <fullName>MI_Question_Pool_Tech_Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MI Question Pool Tech Skill</label>
    <referenceTo>MI_Question_Pool__c</referenceTo>
    <relationshipLabel>Mock Interview Selves (MI Question Pool Tech Skill)</relationshipLabel>
    <relationshipName>Mock_Interview_Selves1</relationshipName>
    <type>Lookup</type>
</CustomField>

MockInterviewPackage/main/default/objects/Mock_Interview_Self__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Do you want to public this?</inlineHelpText>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

MockInterviewPackage/main/default/classes/interviewQuestionClass.cls
/////////////////////////////////////////////////////
//
//  Name: interviewQuestionClass.apxc
//  Author: An Huynh
//  Description: grab questions depending on their type and save the mockinterview record, also create a new feedback for the new mock interview
//
///////////////////////////////////////////////////

public class interviewQuestionClass {
    private static Id currentID = null;
    
    //return MI_Question_Pool__c records filtered by soft skill
    //return: List<MI_Question_Pool__c>
    @auraEnabled
    public static List<MI_Question_Pool__c> getSoftSkillQuestions(){
        List<MI_Question_Pool__c> questions = [SELECT Question__c, Type__c, Suggested_Answer__c FROM MI_Question_Pool__c WHERE Type__c = 'Soft skill'];
        return questions;
    }
    
    //return MI_Question_Pool__c records filtered by technical skill
    //return: List<MI_Question_Pool__c>
    @auraEnabled
    public static List<MI_Question_Pool__c> getTechSkillQuestions(){
        List<MI_Question_Pool__c> questions = [SELECT Question__c, Type__c, Suggested_Answer__c FROM MI_Question_Pool__c WHERE Type__c = 'Technical'];
        return questions;
    }
	
    //return MI_Question_Pool__c records filtered by other skill
    //return: List<MI_Question_Pool__c>
    @auraEnabled
    public static List<MI_Question_Pool__c> getOtherSkillQuestions(){
        List<MI_Question_Pool__c> questions = [SELECT Question__c, Type__c, Suggested_Answer__c FROM MI_Question_Pool__c WHERE Type__c = 'Other'];
        return questions;
    }
    
    //create a new Mock_Interview_Self__c record and return its ID after the insertion
    //question: the list of 3 questions that used to create the interview
    //isPub: indicate public field on the Mock_Interview_Self__c object
    //video: video reference
    //return the interview ID
    @AuraEnabled
    public static Id saveInterview(List<MI_Question_Pool__c> question, Boolean isPub, String video){
        Account acc = [SELECT Name, (SELECT Name FROM Contacts WHERE Name=:UserInfo.GetName()) FROM Account WHERE Name=:UserInfo.GetName()  LIMIT 1];
        Mock_Interview_Self__c moc = new Mock_Interview_Self__c(Account__c=acc.Id, MI_Question_Pool_Soft_Skill__c=question[0].Id, 
                                                                MI_Question_Pool_Tech_Skill__c=question[1].Id, MI_Question_Pool_Other__c=question[2].Id, Public__c=isPub);
        insert moc;
        System.debug('THIS IS WRONG');
        System.debug(moc.Id);
        return moc.Id;
        
    }
    
    //create a new feedback for a given mock interview ID
    //interviewID: the interview ID which being provided feedback
    //myFeedback: the feedback Object with all the information
    @AuraEnabled
    public static void saveSelfFeedback(Id interviewID, Feedback__c myFeedback){
        myFeedback.Mock_Interview_Self__c = interviewID;
        myFeedback.Type__c = 'Self';
        insert myFeedback;
    }
    
    //retrieve a list of the user's interview list
    //return: List<Mock_Interview_Self__c>
    @AuraEnabled
    public static List<Mock_Interview_Self__c> getMyInterview(){
        Account acc = [SELECT Name, (SELECT Name FROM Contacts WHERE Name=:UserInfo.GetName()) FROM Account WHERE Name=:UserInfo.GetName()  LIMIT 1];
        List<Mock_Interview_Self__c> temp = [SELECT Name, CreatedDate, Public__c FROM Mock_Interview_Self__c WHERE Account__c=:acc.Id];
        System.debug(temp);
        return temp;
    }
    
    //retrieve all mockinterview
    @AuraEnabled
    public static List<Feedback__c> getAllFeedback(){
        List<Feedback__c> temp = [SELECT Confidence__c, Fluency__c, Type__c, Eye_Contact__c, Body_Language__c, Mock_Interview_Self__r.Account__r.Name FROM Feedback__c];
    	return temp;
    }
    
}