MockInterviewPackage/main/default/objects/Feedback__c/Feedback__c.object-meta.xml
<CustomObject>
    <label>Feedback</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedbacks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Body_Language__c.field-meta.xml
<CustomField>
    <fullName>Body_Language__c</fullName>
    <label>Body Language</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Confidence__c.field-meta.xml
<CustomField>
    <fullName>Confidence__c</fullName>
    <label>Confidence</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Eye_Contact__c.field-meta.xml
<CustomField>
    <fullName>Eye_Contact__c</fullName>
    <label>Eye Contact</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Feedback__c/fields/Fluency__c.field-meta.xml
<CustomField>
    <fullName>Fluency__c</fullName>
    <label>Fluency</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Mock_Interview_Self__c.field-meta.xml
<CustomField>
    <fullName>Mock_Interview_Self__c</fullName>
    <label>Mock Interview Self</label>
    <referenceTo>Mock_Interview_Self__c</referenceTo>
    <relationshipLabel>Feedbacks</relationshipLabel>
    <relationshipName>Feedbacks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

MockInterviewPackage/main/default/objects/Feedback__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Peer</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MockInterviewPackage/main/default/objects/MI_Question_Pool__c/MI_Question_Pool__c.object-meta.xml
<CustomObject>
    <label>MI Question Pool</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MI Question Pools</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

MockInterviewPackage/main/default/objects/MI_Question_Pool__c/fields/Question__c.field-meta.xml
<CustomField>
    <fullName>Question__c</fullName>
    <label>Question</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

MockInterviewPackage/main/default/objects/MI_Question_Pool__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Soft Skill</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

MockInterviewPackage/main/default/objects/Mock_Interview_Self__c/Mock_Interview_Self__c.object-meta.xml
<CustomObject>
    <label>Mock Interview Self</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mock_Interview_Selfs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

MockInterviewPackage/main/default/objects/Mock_Interview_Self__c/fields/MI_Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>MI_Question_Pool__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>MI Question Pool</label>
    <referenceTo>MI_Question_Pool__c</referenceTo>
    <relationshipLabel>Mock_Interview_Selfs</relationshipLabel>
    <relationshipName>Mock_Interview_Selfs</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

MockInterviewPackage/main/default/classes/interviewQuestionClassTest.cls
/////////////////////////////////////////////////////
//
//  Name: interviewQuestionClassTest.apxc
//  Author: An Huynh
//  Description: testing class for selfInterviewClass
//
///////////////////////////////////////////////////
@isTest
public class interviewQuestionClassTest {
    //set up data for the test
	@testSetup
    public static void setup(){
        Account acc = new Account(Name='ZZ');
        insert acc;
        Contact con = new Contact(FirstName='ZZ', Email='ZZ@bb.com');
       
        
        
        
        List<MI_Question_Pool__c> ques = new List<MI_Question_Pool__c>();
       
        for(Integer i=0; i<3; i++){
            MI_Question_Pool__c temp = new MI_Question_Pool__c(Question__c='Question '+i, Type__c='Soft skill');
            ques.add(temp);
        }
        for(Integer i=0; i<3; i++){
            MI_Question_Pool__c temp = new MI_Question_Pool__c(Question__c='Question '+i, Type__c='Technical');
            ques.add(temp);
        }
        for(Integer i=0; i<3; i++){
            MI_Question_Pool__c temp = new MI_Question_Pool__c(Question__c='Question '+i, Type__c='Other');
            ques.add(temp);
        }
        insert ques;
    }
    
    //Test all methods for interviewQuestionClass
    @isTest
    public static void testGetQuestions(){
        Test.startTest();
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt', Email='ZZ@bb.com', 
            EmailEncodingKey='UTF-8', LastName='ZZ', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='anhuynhtesterbeta123@testorg.com');
        
        List<MI_Question_Pool__c> temp = interviewQuestionClass.getSoftSkillQuestions();
        List<MI_Question_Pool__c> temp1 = interviewQuestionClass.getTechSkillQuestions();
        List<MI_Question_Pool__c> temp2 = interviewQuestionClass.getOtherSkillQuestions();
        List<MI_Question_Pool__c> myQues = new List<MI_Question_Pool__c>();
        List<Mock_Interview_Self__c> mock = new List<Mock_Interview_Self__c>();
        List<Feedback__c> feed = new List<Feedback__c>();
        myQues.add(temp[0]);
        myQues.add(temp1[1]);
        myQues.add(temp2[2]);
        Id mocId = null;
        System.runAs(u){
        mocId = interviewQuestionClass.saveInterview(myQues, true, 'asd');
        Feedback__c myFeedback = new Feedback__c(Type__c='Self', Confidence__c=1, Fluency__c=2, Eye_Contact__c=3, Body_Language__c=4);
        interviewQuestionClass.saveSelfFeedback(mocId, myFeedback);
        mock = interviewQuestionClass.getMyInterview();
        feed = interviewQuestionClass.getAllFeedback();
        }
        
        
        Test.stopTest();
        System.assertEquals(temp.size(), 3);
        System.assertEquals(temp1.size(), 3);
        System.assertEquals(temp2.size(), 3);
        System.assertNotEquals(mocId, Null);
        System.assertEquals([SELECT Name FROM Feedback__c].size(), 1);
        System.assertEquals(mock.size(), 1);
        System.assertEquals(feed.size(), 1);
    }
    
    
}