CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Flag__c/QC_Flag__c.object-meta.xml
<CustomObject>
    <description>Added to a hero&apos;s QC Interview to note comments about the interview.</description>
    <label>QC Flag</label>
    <nameField>
        <label>QC Flag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Flags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Flag__c/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>QC Flags</relationshipLabel>
    <relationshipName>QC_Flags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Flag__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lack of Professionalism</fullName>
            </value>
            <value>
                <fullName>Disfluency</fullName>
            </value>
            <value>
                <fullName>Cursing</fullName>
            </value>
            <value>
                <fullName>Uncertainty</fullName>
            </value>
            <value>
                <fullName>Dress Code</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/QC_Score__c.field-meta.xml
<CustomField>
    <fullName>QC_Score__c</fullName>
    <description>Overall score for this hero&apos;s QC. The value is calculated automatically, but can be overridden (a reason must also be provided).</description>
    <inlineHelpText>The overall score for this hero&apos;s QC; the value is calculated automatically, but can be overridden (a reason must also be provided).</inlineHelpText>
    <label>QC Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <description>The week for which this interview is conducted.</description>
    <inlineHelpText>The week for which the interview is conducted.</inlineHelpText>
    <label>Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Picklist</valueSetName>
    </valueSet>
</CustomField>

QCHubPackage/main/default/globalValueSets/Week_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Week 1</fullName>
    </customValue>
    <customValue>
        <fullName>Week 2</fullName>
    </customValue>
    <customValue>
        <fullName>Week 3</fullName>
    </customValue>
    <customValue>
        <fullName>Week 4</fullName>
    </customValue>
    <customValue>
        <fullName>Week 5</fullName>
    </customValue>
    <customValue>
        <fullName>Week 6</fullName>
    </customValue>
    <customValue>
        <fullName>Week 7</fullName>
    </customValue>
    <customValue>
        <fullName>Week 8</fullName>
    </customValue>
    <customValue>
        <fullName>Week 9</fullName>
    </customValue>
    <customValue>
        <fullName>Week 10</fullName>
    </customValue>
    <customValue>
        <fullName>Week 11</fullName>
    </customValue>
    <customValue>
        <fullName>Week 12</fullName>
    </customValue>
    <masterLabel>Week Picklist</masterLabel>
</GlobalValueSet>

TrialoftheTitansPackage/main/default/classes/FlaggedHeroTestControllerTest.cls
////////////////////////////////////////////////////
//
// Name: Flagged Hero Apex Controller Test
// Author: Josue Cisneros
// Description: Test the SOQL server side controller
//              for retrieving QC Flag data
//
////////////////////////////////////////////////////

@isTest
private class FlaggedHeroTestControllerTest {
    @isTest
        private static void TestPositive(){
            List<QC_Flag__c> listOfFlags = new List<QC_Flag__c>();
            List<QC_Interview__c> listOfInterviews = new List<QC_Interview__c>();
            List<Cohort__c> listOfCohortRef = new List<Cohort__c>();
            QC_Flag__c f;
            QC_Interview__c q;
            Cohort__c c;
            for(Integer i=0;i<1;i++){
                c = new Cohort__c(Name='Cohort'+string.valueof(i));
                listOfCohortRef.add(c);
            }
            insert listOfCohortRef;

            for(Integer i=0;i<20;i++){
                q = new QC_Interview__c(Name='Interview'+string.valueof(i), Cohort__c=listOfCohortRef[0].Id, Week__c= 'Week 1', QC_Score__c = 70 + i);
                listOfInterviews.add(q);
            }
            insert listOfInterviews;

            for(Integer i=0; i<20;i++){
                f = new QC_Flag__c(Name='Flagged'+string.valueof(i), QC_Interview__c=listOfInterviews[i].Id, Type__c='Uncertainty');
            }
    
            List<QC_Flag__c> listOfFlagsTest = FlaggedHeroController.HeroList();
            System.assert( listOfFlagsTest != null); 
        }
    
        @isTest
        private static void TestNegative(){
    
            List<QC_Flag__c> listOfFlagsTest = FlaggedHeroController.HeroList();
            System.assert( listOfFlagsTest.isEmpty(), true); 
        }
}