CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MockInterviewPackage/main/default/objects/Mock_Interview_Self__c/Mock_Interview_Self__c.object-meta.xml
<CustomObject>
    <label>Mock Interview Self</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mock_Interview_Selfs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Mock_Interview_Self__c/fields/AccountName__c.field-meta.xml
<CustomField>
    <fullName>AccountName__c</fullName>
    <formula>Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AccountName</label>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Mock_Interview_Self__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <formula>Account__r.Cohort__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cohort</label>
    <type>Text</type>
</CustomField>

MockInterviewPackage/main/default/objects/Mock_Interview_Self__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Do you want to public this?</inlineHelpText>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

MockInterviewPackage/main/default/classes/PublicVideosAuraController.cls
/////////////////////////////////////////////////////
//
//  Name: Public Videos Aura Controller
//  Author: Alyssa Reed
//  Description: This class uses SOQL queries to
//  	 retrieve all of the videos that are marked 
//  	 as public and return them according to 
//  	 the chosen filter. The associated aura 
//  	 component uses the getPublicVideos query 
//  	 below.
//
////////////////////////////////////////////////////

public with sharing class PublicVideosAuraController {
	
    @auraEnabled //database results arranged in order of what was created most recently.
    public static list<Mock_Interview_Self__c> getPublicVideos(){ 
    list<Mock_Interview_Self__c> publicVids = [SELECT Id, Cohort__c, AccountName__c, Name FROM Mock_Interview_Self__c WHERE Public__c = true ORDER BY CreatedDate DESC];
    system.debug(publicVids);
    return publicVids;
    
    }
    
    @auraEnabled
    public static list<Mock_Interview_Self__c> filterByHeroName(){
       list<Mock_Interview_Self__c> heroNames = [SELECT Id, Cohort__c, AccountName__c, Name FROM Mock_Interview_Self__c WHERE Public__c = true ORDER BY AccountName__c];
       //system.debug(heroNames);    
       return heroNames;
    }
    
    @auraEnabled
    public static list<Mock_Interview_Self__c> filterByCohort(){
       list<Mock_Interview_Self__c> cohortGroups = [SELECT Id, Cohort__c, AccountName__c, Name FROM Mock_Interview_Self__c WHERE Public__c = true ORDER BY Cohort__c];
        //system.debug(cohortGroups);    
       return cohortGroups;
    }
    
    @auraEnabled
    public static String userProfile(){
        List<Profile> PROFILE = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
		String MyProfileName = PROFILE[0].Name;
        system.debug(MyProfileName);
        return MyProfileName;
    }
}