CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Cohorts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QCHubPackage/main/default/classes/QCHubController.cls
public class QCHubController {
    
    @AuraEnabled
    public static List<Cohort__c> getData(){
       
         List<Cohort__c> cohortData = [SELECT Id, Name, Curriculum__r.Name FROM Cohort__c];
       


        return cohortData;

    }
     
    // public class PieChart {
    //     @AuraEnabled public String name;
    //     @AuraEnabled public Integer curriculum;
         
    //     public PieChart( String name, Integer curriculum ) {
    //         this.name = name;
    //         this.curriculum = curriculum;
    //     }
    // }
        


}