CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>a check box indicating if a cohort is active or not</description>
    <label>Currently Active</label>
    <type>Checkbox</type>
</CustomField>

TrainerHubPackage/main/default/classes/TrainerHubPastCohortsTableAuraController.cls
public with sharing class TrainerHubPastCohortsTableAuraController {
	
	// For getting a list of previous cohorts, aka inactive cohorts
	@AuraEnabled
    public static List<Cohort__c> fetchPastCohorts() {
		String currentUser = UserInfo.getUserId();
        List<Cohort__c> pastCohorts = [SELECT Id, Name, Active__c FROM Cohort__c WHERE Active__c = false and OwnerId = :currentUser];
        return pastCohorts;
    }

	// For getting an individual record which is the active cohort
	@AuraEnabled
	public static Id fetchActiveCohort() {
		String currentUser = UserInfo.getUserId();
		Id activeCohortId;
        List<Cohort__c> activeCohort = [SELECT Id FROM Cohort__c WHERE Active__c = true and OwnerId = :currentUser];
        activeCohortId = activeCohort[0].Id;
        return activeCohortId;
    }
}