CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Cohort__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>a check box indicating if a cohort is active or not</description>
    <label>Currently Active</label>
    <type>Checkbox</type>
</CustomField>

TrainerHubPackage/main/default/classes/CohortPageController.cls
public with sharing class CohortPageController {
    @AuraEnabled
    public static String returnDomain(){
        String prefix = URL.getSalesforceBaseURL().toExternalForm().replace('https://', '').split('\\.')[0];
		prefix = prefix.removeEnd('--c');
 		return 'https://' + prefix.toLowerCase() + '.lightning.force.com';
    }
    @AuraEnabled
    public static List<Cohort__c> returnCohorts(){
        List<Cohort__c> cohorts = [SELECT Id, Name FROM Cohort__c ORDER BY Active__c DESC];
        return cohorts;
    }
}