CorePackage/main/default/objects/Cohort__c/Cohort__c.object-meta.xml
<CustomObject>
    <label>Cohort</label>
    <nameField>
        <label>Cohort Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohorts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <description>The cohort for which this interview was conducted (individual hero).</description>
    <inlineHelpText>The cohort that the hero this interview is conducted with belongs to.</inlineHelpText>
    <label>Cohort</label>
    <referenceTo>Cohort__c</referenceTo>
    <relationshipLabel>QC Interviews</relationshipLabel>
    <relationshipName>QC_Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Interview__c/fields/QC_Score__c.field-meta.xml
<CustomField>
    <fullName>QC_Score__c</fullName>
    <description>Overall score for this hero&apos;s QC. The value is calculated automatically, but can be overridden (a reason must also be provided).</description>
    <inlineHelpText>The overall score for this hero&apos;s QC; the value is calculated automatically, but can be overridden (a reason must also be provided).</inlineHelpText>
    <label>QC Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/fields/Week__c.field-meta.xml
<CustomField>
    <fullName>Week__c</fullName>
    <description>The week for which this interview is conducted.</description>
    <inlineHelpText>The week for which the interview is conducted.</inlineHelpText>
    <label>Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Week_Picklist</valueSetName>
    </valueSet>
</CustomField>

QCHubPackage/main/default/globalValueSets/Week_Picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Week 1</fullName>
    </customValue>
    <customValue>
        <fullName>Week 2</fullName>
    </customValue>
    <customValue>
        <fullName>Week 3</fullName>
    </customValue>
    <customValue>
        <fullName>Week 4</fullName>
    </customValue>
    <customValue>
        <fullName>Week 5</fullName>
    </customValue>
    <customValue>
        <fullName>Week 6</fullName>
    </customValue>
    <customValue>
        <fullName>Week 7</fullName>
    </customValue>
    <customValue>
        <fullName>Week 8</fullName>
    </customValue>
    <customValue>
        <fullName>Week 9</fullName>
    </customValue>
    <customValue>
        <fullName>Week 10</fullName>
    </customValue>
    <customValue>
        <fullName>Week 11</fullName>
    </customValue>
    <customValue>
        <fullName>Week 12</fullName>
    </customValue>
    <masterLabel>Week Picklist</masterLabel>
</GlobalValueSet>

TrainerHubPackage/main/default/classes/QCInterviewControllerTest.cls
////////////////////////////////////////////////////
//
// Name: QC Interview Apex Controller Test
// Author: Josue Cisneros
// Description: Test the SOQL server side controller
//              for retrieving QC Interview data
//
////////////////////////////////////////////////////

@isTest
private class QCInterviewControllerTest {
    
    @isTest
        private static void TestPositive(){
            List<QC_Interview__c> listOfInterviews= new List<QC_Interview__c>();
            List<Cohort__c> listOfCohortRef = new List<Cohort__c>();
            QC_Interview__c q;
            Cohort__c c;
            for(Integer i=0;i<4;i++){
                c = new Cohort__c(Name='Testing'+string.valueof(i));
                listOfCohortRef.add(c);
            }
            insert listOfCohortRef;

            for(Integer i=0;i<10;i++){
                q = new QC_Interview__c(Name='Testing'+string.valueof(i), Cohort__c=listOfCohortRef[0].Id, Week__c= 'Week 1', QC_Score__c = 86);
                listOfInterviews.add(q);
            } 
            
            for(Integer i=10;i<20;i++){
                q = new QC_Interview__c(Name='Testing'+string.valueof(i), Cohort__c=listOfCohortRef[1].Id, Week__c= 'Week 1', QC_Score__c = 70);
                listOfInterviews.add(q);
            }

            for(Integer i=20;i<30;i++){
                q = new QC_Interview__c(Name='Testing'+string.valueof(i), Cohort__c=listOfCohortRef[2].Id, Week__c= 'Week 1', QC_Score__c = 87);
                listOfInterviews.add(q);
            }

            for(Integer i=30;i<40;i++){
                q = new QC_Interview__c(Name='Testing'+string.valueof(i), Cohort__c=listOfCohortRef[3].Id, Week__c= 'Week 1', QC_Score__c = 86);
                listOfInterviews.add(q);
            }
    
            insert listOfInterviews;
    
            List<QC_Interview__c> listOfInterviewsTest = QCInterviewController.InterviewList(listOfCohortRef[3].Id);
            System.assert( listOfInterviewsTest != null); 
        }
    
        @isTest
        private static void TestNegative(){
    
            List<QC_Interview__c> listOfInterviewsTest = QCInterviewController.InterviewList('Test Cohort');
            System.assert( listOfInterviewsTest.isEmpty(), true); 
        }
        
}