HeroHubPackage/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Educations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/DateGraduate__c.field-meta.xml
<CustomField>
    <fullName>DateGraduate__c</fullName>
    <label>DateGraduate</label>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <label>Degree</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Gpa__c.field-meta.xml
<CustomField>
    <fullName>Gpa__c</fullName>
    <label>Gpa</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <label>Image URL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Major__c.field-meta.xml
<CustomField>
    <fullName>Major__c</fullName>
    <label>Major</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

HeroHubPackage/main/default/classes/getEducation.cls
/*
    Modified On: 10/26/2021
    Modified By: Iteration VI
    Description: we modified the query by adding "LIMIT 3" because
        we have data factories that populate a great deal of records,
        and because not all of the records need to be shown on the
        Experience site.
*/

public with sharing class getEducation {
    @AuraEnabled(cacheable=true)
    public static List<Education__c> getSchools() {
        //Returns all of the Schools from the database for the user
        return [SELECT Name, Image_URL__c, DateGraduate__c, Degree__c, Gpa__c, Major__c FROM Education__c LIMIT 3];

    }
}