TrialoftheTitansPackage/main/default/objects/Equivalency__c/Equivalency__c.object-meta.xml
<CustomObject>
    <label>Equivalency</label>
    <nameField>
        <label>Equivalency</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equivalencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Equivalencies</relationshipLabel>
    <relationshipName>Equivalencies</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Equivalencies</relationshipLabel>
    <relationshipName>Equivalencies</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/Skill_Equivalency__c.field-meta.xml
<CustomField>
    <fullName>Skill_Equivalency__c</fullName>
    <label>Skill Equivalency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Equivalencies</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

P3/force-app/main/default/objects/Exam_Result__c/fields/Graded__c.field-meta.xml
<CustomField>
    <fullName>Graded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Graded</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <formula>IF( ISBLANK( Passing_Grade_Override__c ), ( Total_Correct__c / Total_Answers__c ) &gt;=  Exam__r.Default_Passing_Grade__c, ( Total_Correct__c / Total_Answers__c ) &gt;=  Passing_Grade_Override__c )</formula>
    <label>Pass</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Projects listed in the Portfolio.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Project__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Assigments__c.field-meta.xml
<CustomField>
    <fullName>Assigments__c</fullName>
    <description>Assignments for the Skills in Trial of the Titans</description>
    <label>Assigments</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Skill_Breakdown__c.field-meta.xml
<CustomField>
    <fullName>Skill_Breakdown__c</fullName>
    <description>Text to describe the skill of a Titan in Trial of the Titans</description>
    <label>Skill Breakdown</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

P3/force-app/main/default/objects/Skill__c/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <description>Type of skill for Skills in Trial of The Titans</description>
    <label>Skill Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coding</fullName>
            </value>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
            <value>
                <fullName>Exams</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Skills</relationshipLabel>
    <relationshipName>Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanHubPackage/main/default/classes/titanPagePortDetailsHelper.cls
/*
Created by: Andrew Emond
Description: Apex class for Portfolio Details LWC (titanPagePortDetails)
Date: 1/25/2022
*/

public with sharing class titanPagePortDetailsHelper {              
   @AuraEnabled(cacheable=true)
   public static List<Skill__c> getSkillsInfo(id titanId){         //Pulls information on Skill from a titan. Just returns one at the moment.
    list<Skill__c> sList = [SELECT Assigments__c,Name,Titan__c, Skill_Breakdown__c,Skill_Type__c FROM Skill__c WHERE Titan__c=: titanId LIMIT 1];
    return sList;
   }
   @AuraEnabled(cacheable=true)
   public static List<Equivalency__c> getEquiv(id titanId){        //Returns a users self inputed Equivalency on a skill.
      list<Skill__c> sList = [SELECT Assigments__c,Name,Titan__c, Skill_Breakdown__c,Skill_Type__c,Id FROM Skill__c WHERE Titan__c=: titanId LIMIT 1];
      id titanSkill = sList[0].Id;
      id userId = UserInfo.getUserId();
      list<Equivalency__c> eList = [SELECT Skill__c,Name,Skill_Equivalency__c,Id,User__c FROM Equivalency__c WHERE Skill__c=: titanSkill AND User__c =: userId];
      return eList;
   }
   @AuraEnabled(cacheable=true)
   public static list<Exam_Result__c> getExamInfo(id titanId){      //Returns a users exam results (how many they have passed). For creating the automatic equivalency.
      id userId = UserInfo.getUserId();
      User conObj = [SELECT name,ContactId,Id FROM User WHERE Id=: userId LIMIT 1];
      id conId = conObj.ContactId;
      Contact accObj = [SELECT name,AccountId,Id FROM Contact WHERE Id=: conId LIMIT 1];
      id accId = accObj.AccountId;
    list<Exam__c> eList = [SELECT Name,Titan__c,Id FROM Exam__c WHERE Titan__c=: titanId];
    list<Exam_Result__c> eRList = [SELECT Pass__c,	Graded__c,Name,Exam__c,Account__c FROM Exam_Result__c WHERE Pass__c =: true AND Account__c=: accId];
    list<Exam_Result__c> emptyList= new list<Exam_Result__c>();
   for(Exam_Result__c eR: eRList){
      for(Exam__c e : eList){
         if(eR.Exam__c== e.Id){
            emptyList.add(eR);
         }
      }
    }
    return emptyList;
   }
   @AuraEnabled(cacheable=true)
   public static list<Project__c> getProjectInfo(){            //Returns a users projects. For creating the automatic equivalency.
      id userId = UserInfo.getUserId();
      list<Project__c> pList = [SELECT User__c,Name,Id From Project__c WHERE User__c =: userId];
      return pList;
   }
   /*@AuraEnabled(cacheable=true)                            Turns out you cant do this. I was wondering why 1 dml statement hit the limit.
   public static void obtainExperience(Integer i){
      system.debug(i);
      id userId = UserInfo.getUserId();
      list<Skill__c> sList = [SELECT Assigments__c,Name,Titan__c, Skill_Breakdown__c,Skill_Type__c,Id FROM Skill__c WHERE Titan__c=: 'a0X5f000001vStqEAE' LIMIT 1];
      id titanSkill = sList[0].Id;
      list<Equivalency__c> eList = [SELECT Skill__c,Name,Skill_Equivalency__c,Id,User__c FROM Equivalency__c WHERE Skill__c=: titanSkill AND User__c =: userId];
      list<Equivalency__c> eListNew = new list<Equivalency__c>();
      for(Equivalency__c eq: eList){
         eq.Skill_Equivalency__c=i;
         eq.Name='apex worked 3';
         eListNew.add(eq);
      }
      update eListNew;
   }*/
}