TrialoftheTitansPackage/main/default/objects/Equivalency__c/Equivalency__c.object-meta.xml
<CustomObject>
    <label>Equivalency</label>
    <nameField>
        <label>Equivalency</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equivalencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Equivalencies</relationshipLabel>
    <relationshipName>Equivalencies</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Equivalencies</relationshipLabel>
    <relationshipName>Equivalencies</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/Skill_Equivalency__c.field-meta.xml
<CustomField>
    <fullName>Skill_Equivalency__c</fullName>
    <label>Skill Equivalency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Equivalencies</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Projects listed in the Portfolio.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Project__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Assigments__c.field-meta.xml
<CustomField>
    <fullName>Assigments__c</fullName>
    <description>Assignments for the Skills in Trial of the Titans</description>
    <label>Assigments</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Skill_Breakdown__c.field-meta.xml
<CustomField>
    <fullName>Skill_Breakdown__c</fullName>
    <description>Text to describe the skill of a Titan in Trial of the Titans</description>
    <label>Skill Breakdown</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

P3/force-app/main/default/objects/Skill__c/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <description>Type of skill for Skills in Trial of The Titans</description>
    <label>Skill Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coding</fullName>
            </value>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
            <value>
                <fullName>Exams</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Skills</relationshipLabel>
    <relationshipName>Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CorePackage/main/default/objects/Titan__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Technology for the Titan in Trial of The Titan</description>
    <label>Technology</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <description>Technologies in the Trial of The Titans</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

TitanHubPackage/main/default/classes/titanPagePortDetailsTest.cls
/*

    Author: Andrew Emond
    Description: Test for porfolio section on titan page(Incomplete 48%). No test yet for the final method. I have not set up experience yet, so I cannot
    Date Created: 1/25/21                                             connect a user to a contact.

*/

@istest
public class titanPagePortDetailsTest {

    @istest
    private static void getSkillsInfoSingleTest(){               //Single Test
         list<titan__c> tList =new list<titan__c>();
        for(integer i=0;i<1;i++){
            titan__c t= new titan__c();
            t.name='testTitan';
            t.Technology__c='Salesforce';
            tList.add(t);      
        }
        insert tList;  
        list<titan__c> testSoql=[SELECT Name From titan__c];
        list<skill__c> sList = new list<skill__c>();
            for(titan__c t: testSoql){
                skill__c s= new skill__c();
                s.name='testskill';
                s.Titan__c=t.id;
                s.Skill_Breakdown__c= 'test breakdown';
                s.Assigments__c= 'test assig';
                s.Skill_Type__c='Coding';
                sList.add(s);
        	 }
        insert sList;
        id tId = testSoql[0].id;
        titanPagePortDetailsHelper.getSkillsInfo(tId);
        list<skill__c> sSoql = [SELECT Assigments__c,Name,Titan__c, Skill_Breakdown__c,Skill_Type__c FROM Skill__c];
        system.assertEquals(1, sSoql.size());
    }
      @istest
    private static void getSkillsInfoBulkTest(){                    //Bulk Test
         list<titan__c> tList =new list<titan__c>();
        for(integer i=0;i<100;i++){
            titan__c t= new titan__c();
            t.name='testTitan';
            t.Technology__c='Salesforce';
            tList.add(t);      
        }
        insert tList;  
        list<titan__c> testSoql=[SELECT Name From titan__c];
        list<skill__c> sList = new list<skill__c>();
            for(titan__c t: testSoql){
                skill__c s= new skill__c();
                s.name='testskill';
                s.Titan__c=t.id;
                s.Skill_Breakdown__c= 'test breakdown';
                s.Assigments__c= 'test assig';
                s.Skill_Type__c='Coding';
                sList.add(s);
        	 }
        insert sList;
        id tId = testSoql[0].id;
        titanPagePortDetailsHelper.getSkillsInfo(tId);
        list<skill__c> sSoql = [SELECT Assigments__c,Name,Titan__c, Skill_Breakdown__c,Skill_Type__c FROM Skill__c];
        system.assertEquals(100, sSoql.size());
    }
    @isTest
    private static void getEquivSingleTest(){                         //Single Test
           list<titan__c> tList =new list<titan__c>();
        for(integer i=0;i<1;i++){
            titan__c t= new titan__c();
            t.name='testTitan';
            t.Technology__c='Salesforce';
            tList.add(t);      
        }
        insert tList;  
        list<titan__c> testSoql=[SELECT Name From titan__c];
        list<skill__c> sList = new list<skill__c>();
            for(titan__c t: testSoql){
                skill__c s= new skill__c();
                s.name='testskill';
                s.Titan__c=t.id;
                s.Skill_Breakdown__c= 'test breakdown';
                s.Assigments__c= 'test assig';
                s.Skill_Type__c='Coding';
                sList.add(s);
        	 }
        insert sList;
        id tId = testSoql[0].id;
        id userId = UserInfo.getUserId();
        list<Equivalency__c> eList = new list<Equivalency__c>();
        for(skill__c s: slist){
            Equivalency__c e = new Equivalency__c();
            e.Name='equivtest';
            e.User__c=userId;
            e.Skill__c=s.Id;
            eList.add(e);
        }
        insert eList;
        list<Equivalency__c> eSoql = [SELECT Skill__c,Name,Skill_Equivalency__c,Id,User__c FROM Equivalency__c];
        titanPagePortDetailsHelper.getEquiv(tId);
        system.assertEquals(1, eSoql.size());
    }
     @isTest
    private static void getEquivBulkTest(){                       //Bulk Test
           list<titan__c> tList =new list<titan__c>();
        for(integer i=0;i<100;i++){
            titan__c t= new titan__c();
            t.name='testTitan';
            t.Technology__c='Salesforce';
            tList.add(t);      
        }
        insert tList;  
        list<titan__c> testSoql=[SELECT Name From titan__c];
        list<skill__c> sList = new list<skill__c>();
            for(titan__c t: testSoql){
                skill__c s= new skill__c();
                s.name='testskill';
                s.Titan__c=t.id;
                s.Skill_Breakdown__c= 'test breakdown';
                s.Assigments__c= 'test assig';
                s.Skill_Type__c='Coding';
                sList.add(s);
        	 }
        insert sList;
        id tId = testSoql[0].id;
        id userId = UserInfo.getUserId();
        list<Equivalency__c> eList = new list<Equivalency__c>();
        for(skill__c s: slist){
            Equivalency__c e = new Equivalency__c();
            e.Name='equivtest';
            e.User__c=userId;
            e.Skill__c=s.Id;
            eList.add(e);
        }
        insert eList;
        list<Equivalency__c> eSoql = [SELECT Skill__c,Name,Skill_Equivalency__c,Id,User__c FROM Equivalency__c];
        titanPagePortDetailsHelper.getEquiv(tId);
        system.assertEquals(100, eSoql.size());
    }
    @istest
    public static void getProjectInfoSingleTest(){                  //Single Test
        list<project__c> pList= new list<project__c>();
        for(integer i=0;i<1;i++){
            project__c p = new project__c();
            p.Name='test project';
            p.User__c=UserInfo.getUserId();
            pList.add(p);
        }
        insert pList;
        list<project__c> pSOQL = [SELECT User__c,Name,Id From Project__c];
        titanPagePortDetailsHelper.getProjectInfo();
        system.assertEquals(1, pSOQL.size());
    }
    @istest
    public static void getProjectInfoBulkTest(){                    //Bulk Test
        list<project__c> pList= new list<project__c>();
        for(integer i=0;i<100;i++){
            project__c p = new project__c();
            p.Name='test project';
            p.User__c=UserInfo.getUserId();
            pList.add(p);
        }
        insert pList;
        list<project__c> pSOQL = [SELECT User__c,Name,Id From Project__c];
        titanPagePortDetailsHelper.getProjectInfo();
        system.assertEquals(100, pSOQL.size());
    }                                                              //One method has not been tested yet.
        
}