TrainerHubPackage/main/default/objects/Equivalency__c/Equivalency__c.object-meta.xml
<CustomObject>
    <label>Equivalency</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Equivalency</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equivalencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Equivalencies</relationshipLabel>
    <relationshipName>Equivalencies</relationshipName>
    <type>Lookup</type>
</CustomField>

TrainerHubPackage/main/default/objects/Equivalency__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Equivalencies</relationshipLabel>
    <relationshipName>Equivalencies</relationshipName>
    <type>Lookup</type>
</CustomField>

TrainerHubPackage/main/default/objects/Equivalency__c/fields/Skill_Equivalency__c.field-meta.xml
<CustomField>
    <fullName>Skill_Equivalency__c</fullName>
    <label>Skill Equivalency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrainerHubPackage/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrainerHubPackage/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TitanHubPackage/main/default/objects/Project__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Assigments__c.field-meta.xml
<CustomField>
    <fullName>Assigments__c</fullName>
    <description>Assignments for the Skills in Trial of the Titans</description>
    <label>Assigments</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Skill_Breakdown__c.field-meta.xml
<CustomField>
    <fullName>Skill_Breakdown__c</fullName>
    <description>Text to describe the skill of a Titan in Trial of the Titans</description>
    <label>Skill Breakdown</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

P3/force-app/main/default/objects/Skill__c/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <description>Type of skill for Skills in Trial of The Titans</description>
    <label>Skill Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coding</fullName>
            </value>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
            <value>
                <fullName>Exams</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Skills</relationshipLabel>
    <relationshipName>Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CorePackage/main/default/objects/Titan__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Technology for the Titan in Trial of The Titan</description>
    <label>Technology</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <description>Technologies in the Trial of The Titans</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

TrainerHubPackage/main/default/classes/DynamicRowAuraControllerTest.cls
@isTest
public class DynamicRowAuraControllerTest{
    @TestSetup
    public static void makeData(){
        List<Titan__c> titanList = new List<Titan__c>();
        List<Project__c> projList = new List<Project__c>();
        List<Skill__c> skillList = new List<Skill__c>();

        titanList.add(new Titan__c(Name='Hercules', Technology__c='Java'));
        insert titanList;

        projList.add(new Project__c(Name='Test Project', Description__c='My test project'));
        insert projList;

        List<Titan__c> currTitans = [SELECT Name FROM Titan__c];
        skillList.add(new Skill__c(Name='Java', Titan__c= currTitans[0].id, Assigments__c='yeaaa', Skill_Breakdown__c='hahahahaha', Skill_Type__c='coding'));
        skillList.add(new Skill__c(Name='Python', Titan__c= currTitans[0].id, Assigments__c='yeaaa', Skill_Breakdown__c='hahahahaha', Skill_Type__c='coding'));
        skillList.add(new Skill__c(Name='Speaking', Titan__c= currTitans[0].id, Assigments__c='yeaaa', Skill_Breakdown__c='hahahahaha', Skill_Type__c='coding'));
        insert skillList;
    }

    @isTest
    public static void saveEquivalencyTest(){
        List<Equivalency__c> equivList = new List<Equivalency__c>();
        List<Equivalency__c> savedEquivList = new List<Equivalency__c>();
        
        List<Skill__c> skillList = [SELECT Name FROM Skill__c];
        List<Project__c> projList = [SELECT Name FROM Project__c];

        equivList.add(new Equivalency__c(Project__c=projList[0].id, Skill__c=skillList[0].id, Skill_Equivalency__c=2));
        equivList.add(new Equivalency__c(Project__c=projList[0].id, Skill__c=skillList[1].id, Skill_Equivalency__c=2));
        equivList.add(new Equivalency__c(Project__c=projList[0].id, Skill__c=skillList[2].id, Skill_Equivalency__c=2));

        dynamicRowAuraController.saveEquivalency(equivList);

        savedEquivList = [SELECT id FROM Equivalency__c];
        System.assertEquals(3, savedEquivList.size());
    }

    @isTest
    public static void retrieveCurrentEquivalenciesTest(){
        List<Equivalency__c> equivList = new List<Equivalency__c>();
        List<Project__c> projList = [SELECT Name FROM Project__c];
        List<Skill__c> skillList = [SELECT Name FROM Skill__c];

        equivList.add(new Equivalency__c(Project__c=projList[0].id, Skill__c=skillList[0].id, Skill_Equivalency__c=2));
        equivList.add(new Equivalency__c(Project__c=projList[0].id, Skill__c=skillList[1].id, Skill_Equivalency__c=2));
        equivList.add(new Equivalency__c(Project__c=projList[0].id, Skill__c=skillList[2].id, Skill_Equivalency__c=2));
        insert equivList;

        List<Equivalency__c> savedEquivList = dynamicRowAuraController.retrieveCurrentEquivalencies(projList[0].id);
        System.assertEquals(3, savedEquivList.size());
    }
}