PortfolioPackage/main/default/objects/Award__c/Award__c.object-meta.xml
<CustomObject>
    <label>Award</label>
    <nameField>
        <label>Award Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Awards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PortfolioPackage/main/default/objects/Award__c/fields/Date_Received__c.field-meta.xml
<CustomField>
    <fullName>Date_Received__c</fullName>
    <label>Date Received</label>
    <type>Date</type>
</CustomField>

PortfolioPackage/main/default/objects/Award__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Awards</relationshipName>
    <type>Lookup</type>
</CustomField>

PortfolioPackage/main/default/classes/honorsAwardsCardHelper.cls
/*
    Author: Drew Williams
    Description: Card container for Honors & Awards section in Portfolio
    Created Date: 3/24/22
*/

// 
public with sharing class honorsAwardsCardHelper {
    @AuraEnabled(cacheable=true)
    public static List<Award__c> getAwards() {
        id userID=UserInfo.getUserId();
        
        List <Award__c> Awards= [SELECT Name, Date_Received__c FROM Award__c WHERE User__c=:userId];
        system.debug(Awards);
        return Awards;
    }
}