PortfolioPackage/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PortfolioPackage/main/default/objects/Category__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Categories</relationshipName>
    <type>Lookup</type>
</CustomField>

PortfolioPackage/main/default/objects/Custom_Skill__c/Custom_Skill__c.object-meta.xml
<CustomObject>
    <label>Custom_Skill</label>
    <nameField>
        <label>Custom_Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom_Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PortfolioPackage/main/default/objects/Custom_Skill__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Custom_Skills</relationshipLabel>
    <relationshipName>Custom_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PortfolioPackage/main/default/objects/Custom_Skill__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Custom_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Educations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/DateGraduate__c.field-meta.xml
<CustomField>
    <fullName>DateGraduate__c</fullName>
    <label>DateGraduate</label>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <label>Degree</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Gpa__c.field-meta.xml
<CustomField>
    <fullName>Gpa__c</fullName>
    <label>Gpa</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Major__c.field-meta.xml
<CustomField>
    <fullName>Major__c</fullName>
    <label>Major</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Educations</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/Equivalency__c.object-meta.xml
<CustomObject>
    <label>Equivalency</label>
    <nameField>
        <label>Equivalency</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Equivalencies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/Skill_Equivalency__c.field-meta.xml
<CustomField>
    <fullName>Skill_Equivalency__c</fullName>
    <label>Skill Equivalency</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Equivalency__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Equivalencies</relationshipName>
    <type>Lookup</type>
</CustomField>

PortfolioPackage/main/default/classes/portfolioHelper.cls
public with sharing class portfolioHelper {
    /* I got rid of the hard-coded ID for this method, but this method 
    is not returning or changing anything, and a grep tells me it's not being
    used anywhere. Just leaving it here in case future iterations find a use for it. */
    public static void getSkillMatrix(){
    	Id uid = UserInfo.getUserId();
        
		List<Category__c> skills = [SELECT ID, (SELECT Name FROM Custom_Skills__r)
                                    FROM Category__c];
        
        List<String> skillNames = new List<String>{};                          
        for(Category__c req :skills){
            for(Custom_Skill__c a : req.Custom_Skills__r){               
                skillNames.add(a.Name);
            }
        }        
    }
    
    public static void getEduc(){
        Id uid = UserInfo.getUserId();
        List<Education__c> education = 
            [SELECT Degree__c, DateGraduate__c, Gpa__c, Major__c 
             FROM Education__c
             WHERE User__c = :uid];
        
        List<Map<String,String>> educationMap = new List<Map<String,String>>();
        for(Education__c e : education) {
            educationMap.add(new Map<String, String>{'Degree' => e.Degree__c, 'Major' => e.Major__c, 'GPA' => String.valueof(e.Gpa__c),'Date Graduated' => String.valueof(e.DateGraduate__c)});            
        }
    }
    
    
    public static List<Equivalency__c> getEq(){
        id uid = UserInfo.getUserId();
        
     	List<Equivalency__c> strengths = 
            [SELECT Name, Skill_Equivalency__c 
             FROM Equivalency__c
             WHERE User__c = :uid ORDER BY Skill_Equivalency__c DESC LIMIT 5];
        
        List<Map<String,String>> strengthsMap = new List<Map<String,String>>();
        for(Equivalency__c e : strengths) {
            strengthsMap.add(new Map<String, String>{'EquivalencyName' => e.Name, 'EquivalencyNum' => String.valueof(e.Skill_Equivalency__c)});            
        }        

        return strengths;
    }
}