PortfolioPackage/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PortfolioPackage/main/default/objects/Custom_Skill__c/Custom_Skill__c.object-meta.xml
<CustomObject>
    <label>Custom_Skill</label>
    <nameField>
        <label>Custom_Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom_Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PortfolioPackage/main/default/objects/Custom_Skill__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Custom_Skills</relationshipLabel>
    <relationshipName>Custom_Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PortfolioPackage/main/default/objects/Custom_Skill__c/fields/Skill_Number__c.field-meta.xml
<CustomField>
    <fullName>Skill_Number__c</fullName>
    <displayFormat>SKILL-{0000}</displayFormat>
    <label>Skill_Number</label>
    <type>AutoNumber</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Titan__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Programmatic</fullName>
            </value>
            <value>
                <fullName>Declarative</fullName>
            </value>
            <value>
                <fullName>Misc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Trial of the Titans/CorePackage/objects/Titan__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Titans</relationshipLabel>
    <relationshipName>Titans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PortfolioPackage/main/default/classes/TestDataClass.cls
public with sharing class TestDataClass {

    @AuraEnabled(cacheable=true)
    public static List<Titan__c> retrieveTitans() {

        
    
        return
        [SELECT Curriculum__c, Name, Curriculum__r.Name
        FROM Titan__c
        ];





    }

    @AuraEnabled(cacheable=true)
    public static List<Category__c> retrieveCategories() {
        
        return 
        [SELECT Name, 
        (SELECT Name, Skill_Number__c FROM Custom_Skills__r) 
        FROM Category__c];

    }

    
}