CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Curriculum__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technology</label>
    <referenceTo>Technology__c</referenceTo>
    <relationshipLabel>Curricula</relationshipLabel>
    <relationshipName>Curricula</relationshipName>
    <type>Lookup</type>
</CustomField>

ExamPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <!--actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>Exam_Record_Page1</content>
        <formFactor>Small</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
    </actionOverrides-->
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam__c/fields/Default_Passing_Grade__c.field-meta.xml
<CustomField>
    <fullName>Default_Passing_Grade__c</fullName>
    <label>Default Passing Grade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

ExamPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Pool_Assignment__c/Exam_Pool_Assignment__c.object-meta.xml
<CustomObject>
    <label>Exam Pool Assignment</label>
    <nameField>
        <displayFormat>EP-{0000}</displayFormat>
        <label>Exam Pool Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Pool Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Pool_Assignment__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipName>Exam_Pools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Pool_Assignment__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Question_Pool__c</referenceTo>
    <relationshipName>Exam_Pools</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/Exam_Question__c.object-meta.xml
<CustomObject>
    <label>Exam Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <formula>TEXT( Titan__r.Technology__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Technology</label>
    <type>Text</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Result__c/fields/Graded__c.field-meta.xml
<CustomField>
    <fullName>Graded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Graded</label>
    <type>Checkbox</type>
</CustomField>

ExamPackage/main/default/objects/Hero_Answer__c/Hero_Answer__c.object-meta.xml
<CustomObject>
    <label>Hero Answer</label>
    <nameField>
        <displayFormat>HA-{0}</displayFormat>
        <label>Hero Answer Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Hero_Answer__c/fields/Correct__c.field-meta.xml
<CustomField>
    <fullName>Correct__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Correct</label>
    <type>Checkbox</type>
</CustomField>

ExamPackage/main/default/objects/Hero_Answer__c/fields/Exam_Question__c.field-meta.xml
<CustomField>
    <fullName>Exam_Question__c</fullName>
    <label>Exam Question</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Hero Answers</relationshipLabel>
    <relationshipName>Hero_Answers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Hero_Answer__c/fields/Exam_Result__c.field-meta.xml
<CustomField>
    <fullName>Exam_Result__c</fullName>
    <label>Exam Result</label>
    <referenceTo>Exam_Result__c</referenceTo>
    <relationshipLabel>Hero Answers</relationshipLabel>
    <relationshipName>Hero_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Assignment__c/Question_Assignment__c.object-meta.xml
<CustomObject>
    <label>Question Assignment</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Question Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Question_Assignment__c/fields/Exam_Question__c.field-meta.xml
<CustomField>
    <fullName>Exam_Question__c</fullName>
    <label>Exam Question</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Question Assignments</relationshipLabel>
    <relationshipName>Question_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Assignment__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Question_Pool__c</referenceTo>
    <relationshipLabel>Question Assignments</relationshipLabel>
    <relationshipName>Question_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Pool__c/Question_Pool__c.object-meta.xml
<CustomObject>
    <label>Question Pool</label>
    <nameField>
        <label>Question Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Question_Pool__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Question Pool</relationshipLabel>
    <relationshipName>Question_Pools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Titan__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Titans</relationshipLabel>
    <relationshipName>Titans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CorePackage/main/default/objects/Titan__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Technology for the Titan in Trial of The Titan</description>
    <label>Technology</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <description>Technologies in the Trial of The Titans</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

ExamPackage/main/default/classes/ExamResultsPoolPageAuraController_Test.cls
//////////////////////////////////////////
//
//Name: ExamResultsPoolPageAuraController_Test
//Author: Miguel McCrary
//Date Created: 06/27/21
//Date Updated: 06/28/21
//Description: Test class for the ExamResultsPoolPageAuraController class
//
//////////////////////////////////////////
@isTest
public class ExamResultsPoolPageAuraController_Test {

    @testSetup
    static void setup(){
        // create a new curriculum
        Curriculum__c newCurriculum = new Curriculum__c(Name='Salesforce');
        insert newCurriculum;

        //create a new question pool
       Question_Pool__c newQuestionPool = new Question_Pool__c(Name = 'Apex Testing');
       insert newQuestionPool;

        //create new accounts
        List<Account> userAccounts = new List<Account>();
        for(Integer i = 0; i < 5; i++){
            Account newAccount = new Account(name='User'+i);
            userAccounts.add(newAccount);
        }
        insert userAccounts;

        //create new titans
        List<Titan__c> newTitans = new List<Titan__c>();
        List<String> titanNames = new List<String>{'Process Automation', 'Data Modeling', 'Apex'};
        for(String name : titanNames){
            Titan__c newTitan = new Titan__c(Name = name, Technology__c = newCurriculum.Name,  Curriculum__c = newCurriculum.Id);
            newTitans.add(newTitan);  
        }
        insert newTitans;

        //creat new exams
        List<Exam__c> newExams = new List<Exam__c>();
        for(Titan__c titan : newTitans){
            for(Integer i = 0; i < 3; i++){
                Exam__C newExam = new Exam__c( Name='testExam'+ i, Default_Passing_Grade__c = 65.0, Titan__c = titan.Id );
                newExams.add(newExam);
            }   
        }
        insert newExams;

        //Create new exam questions
        List<Exam_Question__c> newQuestions = new List<Exam_Question__C>();
            for(Integer i = 0; i < 5; i++){
                Exam_Question__C newQuestion = new Exam_Question__c( Name = 'Test' + i );
                newQuestions.add(newQuestion);
        }
        insert newQuestions;

        //create new question assignments
        List<Question_Assignment__c> newQuestionAssignmentList = new List<Question_Assignment__c>();
        for(Exam_Question__c examQuestions: newQuestions){
                Question_Assignment__c newQuestionAssignment = new Question_Assignment__c
                (Question_Pool__c = newQuestionPool.Id, Exam_Question__C = examQuestions.Id );
                
                newQuestionAssignmentList.add(newQuestionAssignment);
        }
        insert newQuestionAssignmentList;

        //create exam assignments
        List< Exam_Pool_Assignment__c> newExamAssignments = new List< Exam_Pool_Assignment__c>();
        for(Exam__c exam: newExams){
            for(Integer i = 0; i < 5; i++){
                Exam_Pool_Assignment__c newExAssign = new  Exam_Pool_Assignment__c
                (Exam__c = exam.id, question_Pool__c = newQuestionPool.id);

                newExamAssignments.add(newExAssign);
            }
        }
        insert newExamAssignments;
        
        //create new exam results
        List<Exam_Result__c> newResults = new List<Exam_Result__c>();
        
        for(Exam__c exam: newExams){
            for(Account acc: userAccounts){
                Exam_Result__c newResult = new Exam_Result__c(Exam__c = exam.Id, Account__c = acc.Id);
                if(Math.round(Math.random()) == 1){
                    newResult.Graded__c = true;
                }
               newResults.add(newResult);
            }
        }
        insert newResults;

        //generate hero answers based on exam results
        List<Hero_Answer__c> newAnswers = new List<Hero_Answer__c>();
        for(Exam_Question__c question : newQuestions){ 
            for(Exam_Result__c result : newResults){
            	Hero_Answer__c newAnswer = new Hero_Answer__c(Exam_Question__c = question.id, Exam_Result__c = result.id);
                if(Math.random() < .85){ 
                    newAnswer.Correct__c = true;
                }
                else{
                	newAnswer.Correct__c = false;
                }
                newAnswers.add(newAnswer);
            }
        }
        insert newAnswers;
    }

    @isTest
    public static void testPositive(){

        String ExamResultId = [SELECT Id FROM Exam_Result__c LIMIT 1].Id;
        List<String> getReturnAll =  ExamResultsPoolPageAuraController.GetAllExamResultPoolQuestions(ExamResultId);
  
        //first method positive        
        List<String> allExamResultPoolQuestions = new List<String>();

        for(Question_Assignment__c qa : [SELECT Exam_Question__c, Question_Pool__c, Question_Pool__r.Name 
        FROM Question_Assignment__c 
        WHERE Exam_Question__c IN (SELECT Exam_Question__c FROM Hero_Answer__c 
        WHERE Exam_Result__c = :examResultId)]){

        allExamResultPoolQuestions.add(qa.Question_Pool__r.Name);
        
        }
        System.debug('Pool Name for each Question: ' + allExamResultPoolQuestions);
        System.assert(allExamResultPoolQuestions == getReturnAll);

        //second method positive
        List<String> getReturnCorrect = ExamResultsPoolPageAuraController.GetCorrectExamResultPoolQuestions(ExamResultId);
        List<String> correctExamResultPoolQuestions = new List<String>();

        for(Question_Assignment__c qa : [SELECT Exam_Question__c, Question_Pool__c, Question_Pool__r.Name
        FROM Question_Assignment__c 
        WHERE Exam_Question__c IN 
        (SELECT Exam_Question__c FROM Hero_Answer__c 
        WHERE Exam_Result__c = :examResultId AND Correct__c = True)]){

        correctExamResultPoolQuestions.add(qa.Question_Pool__r.Name);
        
        }
        System.debug('Pool Name for each Correct Question: ' + correctExamResultPoolQuestions);
        System.assert(correctExamResultPoolQuestions == getReturnCorrect);

    }

    @isTest
    public static void testNegative(){

        String emptyString = '';
        List<String> getReturnAll =  ExamResultsPoolPageAuraController.GetAllExamResultPoolQuestions(emptyString);
  
        //first method negative     
        List<String> allExamResultPoolQuestions = new List<String>();

        for(Question_Assignment__c qa : [SELECT Exam_Question__c, Question_Pool__c, Question_Pool__r.Name 
        FROM Question_Assignment__c 
        WHERE Exam_Question__c IN (SELECT Exam_Question__c FROM Hero_Answer__c 
        WHERE Exam_Result__c = :emptyString)]){

            allExamResultPoolQuestions.add(qa.Question_Pool__r.Name);
        }
        System.debug('Pool Name for each Question: ' + allExamResultPoolQuestions);
        System.assert(getReturnAll == allExamResultPoolQuestions);

        //second method negative
        List<String> getReturnCorrect = ExamResultsPoolPageAuraController.GetCorrectExamResultPoolQuestions(emptyString);
        List<String> correctExamResultPoolQuestions = new List<String>();

        for(Question_Assignment__c qa : [SELECT Exam_Question__c, Question_Pool__c, Question_Pool__r.Name
        FROM Question_Assignment__c 
        WHERE Exam_Question__c IN 
        (SELECT Exam_Question__c FROM Hero_Answer__c 
        WHERE Exam_Result__c = :emptyString AND Correct__c = True)]){

            correctExamResultPoolQuestions.add(qa.Question_Pool__r.Name);
        }
        
        System.debug('Pool Name for each Correct Question: ' + correctExamResultPoolQuestions);
        System.assert(getReturnCorrect == correctExamResultPoolQuestions);
        
    }

}