CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Titan__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Titans</relationshipLabel>
    <relationshipName>Titans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

HeroHubPackage/main/default/classes/UserContextInfo.cls
public class UserContextInfo {
    User user;
    Account userAccount;
    Map<String, List<Exam__c>> examList;
    Team_c userTeam;
    Squad_c userSquad;
    Curriculum__c userCurriculum;


    public UserContextInfo( Id userId ){
        userAccount = HeroHubUtilities.getUserAccount( userId );
        userCurriculum = userAccount.Curriculum__c;        
        List<Titan__c> titanList = getTitans( userCurriculum );
        List<Exam__c> examList = getExams(titanList);
        List<Exam_results__c> resultList = getExamResults(userAccount.Id);
        
    }


    private List<Titan__c> getTitans(Id curriculum){

        List<Titan__c> titans = [SELECT Id, Name FROM Titan__c WHERE Curriculum__c = :curriculum];
        
        return titans;
    }

    private Map<String, List<Exam__c>> getExams(List<Titan__c> titanList){
        
        List<Exam__c> examList = [SELECT Id, Titan__c, Name FROM Exam__c WHERE Titan__C IN :titanList];
    
    }

}


Map<String, List<Exam__c>> examMap = new Map<String, List<Exam__c>>();
        
for(Titan__c titan : titanList){
    for(Exam__c exam : examList{ 
        if(exam.Titan__C == titan.Id){
            if(examMap.containsKey(titan.Name)){
                examMap.get(titan.Name).add(exam);
            }
            else{
                List<Exam__c> newList = new List<Exam__c>{exam};
                examMap.put(titan.Name, newList);
            }
        }
    }
}

return examMap;