CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Curriculum__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technology</label>
    <referenceTo>Technology__c</referenceTo>
    <relationshipLabel>Curricula</relationshipLabel>
    <relationshipName>Curricula</relationshipName>
    <type>Lookup</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EmployerPartnerPackage/main/default/classes/EmployerPartnerExperienceSiteHelper.cls
public with sharing class EmployerPartnerExperienceSiteHelper {
    @AuraEnabled(cacheable=true)

    public static List<String> getHeroInfo(){
        //BEFORE THIS IS WHERE WE DEFINE OUR SEARCH PARAMETERS 
        List<Account> AccountInfo= new List<Account>();

        //Get our account info
        if(true){
           AccountInfo=[SELECT Curriculum__r.Technology__c, (SELECT Name, Title, MailingCity FROM Contacts) FROM Account WHERE Id IN (SELECT AccountId FROM Contact)];
        }
        else{
             AccountInfo= [SELECT Curriculum__r.Technology__c, (SELECT Name, Title, MailingCity FROM Contacts) FROM Account WHERE Id IN (SELECT AccountId FROM Contact)];
        }
        //We want to get a list of users with hero profile so this grabs allusers who meet that requirement
        List<Contact> myContacts= new List<Contact>();
        for (Account acc : AccountInfo) {
            myContacts.addAll(acc.Contacts);
        }

        List<User> UserInfo= [SELECT ID, Contact.Id FROM User WHERE Profile.Name= 'Hero' AND ContactId IN :myContacts];

        List<String> listOfHeroes = new List<String>();
        for (User u : UserInfo) {
            
        
            for (Account acc : AccountInfo) {
            
            List<Contact> contacts = acc.Contacts;
            /**
            For all users that have a hero
            Create a map  that is converted to a list of JSON string with all values we need
            */
            for (Contact con : contacts) {
                if (u.ContactId==con.Id){
                    Map<String, String> heroMap = new Map<String, String>();
                    heroMap.put('Id',u.Id);
                    heroMap.put('Link','');//Need to get this from portfolio somehow
                    heroMap.put('Name', con.Name);
                    heroMap.put('Title', con.Title);
                    heroMap.put('Location', con.MailingCity);
                    heroMap.put('Technology', acc.Curriculum__r.Technology__c);
                    heroMap.put('Favorite', 'Favorite');
                    heroMap.put('Arete', '56');//NO IMPLEMENTAION
                    listOfHeroes.add(JSON.Serialize(heroMap));
                }
            }
            
            }
        }

        return listOfHeroes;
    }
}