CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

P3/force-app/main/default/objects/Exam_Result__c/fields/Graded__c.field-meta.xml
<CustomField>
    <fullName>Graded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Graded</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Titan__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Titans</relationshipLabel>
    <relationshipName>Titans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

HeroHubPackage/main/default/classes/UserTriggerHandler.cls
public class UserTriggerHandler {
    
    // Need to get the current curriculum to find the technology and filter exams by titans within the technology
    // Then you need to create an exam result for each of those exams

    public static void AssignExams( List<User> userList ) {

        Map<User, List<Exam__c> > examsMap = GetUserToExamMap( userList );
        Map<User, Account> accountMap = GetUserToAccountMap( userList );
        List<Exam_Result__c> createdResults = new List<Exam_Result__c>();

        for ( User u : userList ) {
            List<Exam__c> workingExamList = examsMap.get( u );

            for ( Exam__c currExam : workingExamList ) {
                Exam_Result__c newResult = new Exam_Result__c(
                    Exam__c = currExam.id,
                    Account__c = accountMap.get( u ).id,
                    Graded__c = false,
                    Status__c = 'Assigned'
                );
                createdResults.add( newResult );
            }
        }
        Insert createdResults;
    }

    private static Map< User, List<Exam__c> > GetUserToExamMap( List<User> userList ) {
        Map<User, Curriculum__c> curriculumMap = GetUserToCurriculumMap( userList );
        Set<id> curriculumSet = new Set<id>();
        for ( User u : userList ) {
            curriculumSet.add( curriculumMap.get( u ).id );
        }

        List<Exam__c> possibleExams = [SELECT id, Titan__r.Curriculum__c FROM Exam__c WHERE Titan__r.Curriculum__c IN :curriculumSet];

        Map< User, List<Exam__c> > examsMap = new Map< User, List<Exam__c> >();
        for ( User u : userList ) {
            examsMap.put( u, GetRelevantExams( curriculumMap.get( u ), possibleExams ) );
        }
        return examsMap;
    }

    private static Map<User, Curriculum__c> GetUserToCurriculumMap( List<User> userList ) {
        Map<User, Account> accountMap = GetUserToAccountMap( userList );
        Set<id> curriculumSet = new Set<id>();
        for ( User u : userList ) {
            curriculumSet.add( accountMap.get( u ).curriculum__c );
        }

        List<Curriculum__c> possibleCurrics = [SELECT id FROM Curriculum__c WHERE id IN :curriculumSet];
        Map<User, Curriculum__c> curricMap = new Map<User, Curriculum__c>();

        for ( User u : userList ) {
            for ( Curriculum__c curric : possibleCurrics ) {
                if ( accountMap.get( u ).curriculum__c == curric.id ) {
                    curricMap.put( u, curric );
                    break;
                }
            }
        }

        return curricMap;
    }

    private static Map<User, Account> GetUserToAccountMap( List<User> userList ) {
        Set<String> usernameSet = new Set<String>();
        for ( User u : userList ) {
            usernameSet.add( u.name );
        }

        List<Account> possibleAccounts = [SELECT name, curriculum__c FROM Account WHERE name IN :usernameSet];
        Map<User, Account> accountMap = new Map<User, Account>();

        for ( User u : userList ) {
            for ( Account acc : possibleAccounts ) {
                if ( acc.name == u.name ) {
                    accountMap.put( u, acc );
                    break;
                }
            }
        }

        return accountMap;
    }

    private static List<Exam__c> GetRelevantExams( Curriculum__c curriculum, List<Exam__c> possibleExams ) {
        List<Exam__c> relevantExamList = new List<Exam__c>();
        for ( Exam__c exam : possibleExams ) {
            if ( exam.Titan__r.Curriculum__c == curriculum.id )
                relevantExamList.add( exam );
        }

        return relevantExamList;
    }
}