CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hero&apos;s Team in The Trial of The Titans</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Curriculum__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technology</label>
    <referenceTo>Technology__c</referenceTo>
    <relationshipLabel>Curricula</relationshipLabel>
    <relationshipName>Curricula</relationshipName>
    <type>Lookup</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HeroHubPackage/main/default/objects/Team__c/fields/In_Lead__c.field-meta.xml
<CustomField>
    <fullName>In_Lead__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Lead?</label>
    <type>Checkbox</type>
</CustomField>

HeroHubPackage/main/default/objects/Team__c/fields/Primary_Color__c.field-meta.xml
<CustomField>
    <fullName>Primary_Color__c</fullName>
    <label>Primary Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

HeroHubPackage/main/default/objects/Team__c/fields/Secondary_Color__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Color__c</fullName>
    <label>Secondary Color</label>
    <length>7</length>
    <type>Text</type>
</CustomField>

HeroHubPackage/main/default/objects/Team__c/fields/Slogan__c.field-meta.xml
<CustomField>
    <fullName>Slogan__c</fullName>
    <label>Slogan</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Team a User belongs to.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HeroHubPackage/main/default/classes/headerHelper.cls
/*
Created by: Andrew Emond
Description: Apex class for Header LWC
Date Created: 1/21/2022
*/

public with sharing class headerHelper {
    @AuraEnabled(cacheable=true)
    public static list<Team__c> getTeamInfo(){                         //Used for pulling what team is in the lead to LWC Header. Based on which team has the In Lead Field Checked.
        return [SELECT Name,In_Lead__c,Primary_Color__c,Secondary_Color__c,Slogan__c FROM Team__c WHERE In_Lead__c=: true];
    }
    @AuraEnabled(cacheable=true)
    public static Curriculum__c getTechInfo(){                       //Used for pulling the current users tech to LWC. I had to jump through a lot of hoops to get to this point,
        id userId = UserInfo.getUserId();                            //hopefully a future iteration can refine the data model and make better relationships.
        User conObj = [SELECT name,ContactId,Id FROM User WHERE Id=: userId LIMIT 1];
        id conId = conObj.ContactId;
        Contact accObj = [SELECT name,AccountId,Id FROM Contact WHERE Id=: conId LIMIT 1];
        id accId = accObj.AccountId;
        Account curObj = [SELECT name,Curriculum__c,Id FROM Account WHERE Id=: accId LIMIT 1];
        id curId = curObj.Curriculum__c;
        return [ SELECT name,Technology__c,Id FROM Curriculum__c WHERE Id=: curId LIMIT 1];
    }
}