CorePackage/main/default/objects/Account/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Curriculum of the Hero</description>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Curriculum__c/Curriculum__c.object-meta.xml
<CustomObject>
    <label>Curriculum</label>
    <nameField>
        <label>Curriculum Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Curricula</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Curriculum__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Technology</label>
    <referenceTo>Technology__c</referenceTo>
    <relationshipLabel>Curricula</relationshipLabel>
    <relationshipName>Curricula</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam__c/fields/Default_Passing_Grade__c.field-meta.xml
<CustomField>
    <fullName>Default_Passing_Grade__c</fullName>
    <label>Default Passing Grade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Assigments__c.field-meta.xml
<CustomField>
    <fullName>Assigments__c</fullName>
    <description>Assignments for the Skills in Trial of the Titans</description>
    <label>Assigments</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Skill_Breakdown__c.field-meta.xml
<CustomField>
    <fullName>Skill_Breakdown__c</fullName>
    <description>Text to describe the skill of a Titan in Trial of the Titans</description>
    <label>Skill Breakdown</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

P3/force-app/main/default/objects/Skill__c/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <description>Type of skill for Skills in Trial of The Titans</description>
    <label>Skill Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coding</fullName>
            </value>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
            <value>
                <fullName>Exams</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Skills</relationshipLabel>
    <relationshipName>Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Titan__c/fields/Curriculum__c.field-meta.xml
<CustomField>
    <fullName>Curriculum__c</fullName>
    <label>Curriculum</label>
    <referenceTo>Curriculum__c</referenceTo>
    <relationshipLabel>Titans</relationshipLabel>
    <relationshipName>Titans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

CorePackage/main/default/objects/Titan__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Technology for the Titan in Trial of The Titan</description>
    <label>Technology</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <description>Technologies in the Trial of The Titans</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

TitanPage/main/default/classes/TitanPageControllerTest.cls
//This section is for testing getTitans
		@isTest
        public class TitanPageControllerTest {
                
 		@TestSetup
            static void testSetupMethod(){
                titanPageTestUtilities.createUsers();
                titanPageTestUtilities.fullSetup();
                
            }
    
            @isTest
            static void testFetchUser(){
                User testUser = [SELECT Id FROM USER WHERE alias = 'testUser' LIMIT 1];
    
       			 String info;
    
    			system.runAs(testUser){
        
           		 info = TitanPageApexController.fetchUser();
            
    	}
                
      //    System.AssertEquals(testUser.id; )
            }      
          
         @isTest
              static void getTitansPos(){
                   User testUser = [SELECT Id FROM USER WHERE alias = 'testUser' LIMIT 1];
                  List<Titan__c> listtitans = new List<Titan__c>();
                  system.runAs(testUser){
                      listtitans = titanpageapexcontroller.getTitans();
                  }
                  system.assertEquals(3, listtitans.size());
              }
            
            
           @isTest
              static void getSkillsPos(){
                  
                    List<Skill__c> newSkills = new List<Skill__c>();
                
                List<String> skillNames = new List<String>{'Test Skill1', 'Test Skill2', 'Test Skill3'};
                
                    for(Titan__c t : [SELECT Name FROM Titan__c]){   
                    
                		for(String name : skillNames){
                    
                    	Skill__c newSkill = new Skill__c(Name = name, Titan__c = t.ID, Skill_Breakdown__c = 'test', Skill_Type__c = 'coding', Assigments__c='Test');
                    	newSkills.add(newSkill);
                    
                }
                    }
                insert newSkills;
                  
                  
                  Titan__c testTitan = [SELECT ID FROM TITAN__C WHERE NAME='Apex'];
                  List<Skill__c> listSkills = new List<Skill__c>();
                 	
                   listSkills = titanpageapexcontroller.getSkills(testTitan.Id);
                  
                  system.assertEquals(3, listSkills.size());
              }   
            
            
          
          /*  static void getExamsPositiveTest(){
                List<Exam__c> examPositive = new List<Exam__c>();
                Id titanId = [SELECT Id FROM Titan__c WHERE Name = 'Test Titan1'];
                examPositive = TitanPageApexController.getExams(titanId);
           
            }
*/
         
        /*        
                 
                Curriculum__c newCurriculum = new Curriculum__c(Name='Salesforce');
                insert newCurriculum;
                
                List<Titan__c> newTitans = new List<Titan__c>();
                
                List<String> titanNames = new List<String>{'Test Titan1', 'Test Titan2', 'Test Titan3'};
                
                for(String name : titanNames){
                    
                    Titan__c newTitan = new Titan__c(Name = name, Technology__c = newCurriculum.Name,  Curriculum__c = newCurriculum.Id);
                    newTitans.add(newTitan);
                    
                }
                
                insert newTitans;
                 
                 
                List<Titan__c> titansGotten = TitanPageApexController.getTitans();
               
                 System.assertEquals([SELECT Name, Id FROM Titan__c], titansGotten);
            }
         public static List<Titan__c> getTitans() {
        //Method for retrieving list of titans
      
        
     	Account acc = [SELECT Curriculum__c FROM Account WHERE Name = :userInfo.getName()];
		List<Titan__c> titanList = [SELECT Name FROM Titan__c WHERE Curriculum__c = :acc.Curriculum__c];

        return titanList;
         }          
	//Now, the same thing for Exams
		@isTest
		static void ExamsTest(){
            List<Exam__c> testExams = new List<Exam__c>();
            List<Titan__c> titanList = [SELECT Name, Id FROM Titan__c];
            
            for(Titan__c t : titanList){
                for(Integer i=0; i<4; i++){
                    Exam__c createExam = new Exam__c(Name='Exam'+i, Default_Passing_Grade__c = 65.0, Titan__c = t.Id);
                    testExams.add(createExam);
                }
            }
        }
        }
    /*	insert testExams;
            List<Exam__c> examsGotten = TitanPageApexController.getExams(titanList[0].Id);
			Id titanId = titanList[0].Id;
            System.assertEquals([Select Exam__c FROM Exam__c WHERE Titan__r.iD = titanId], examsGotten);
        }
        } */
//I am unsure whether or not I need to do anything other than hardcode this indexed value titanList[0]
//this method takes only a single Id as its parameter and this only happens in the context of a specific titan being selected
//
//
//
//
//
 /*create a curriculum
                Curriculum__c newCurriculum = new Curriculum__c(Name='Salesforce');
                insert newCurriculum;
                
                //create a list of titans
                List<Titan__c> newTitans = new List<Titan__c>();
                
                List<String> titanNames = new List<String>{'Test Titan1', 'Test Titan2', 'Test Titan3'};
                
                for(String name : titanNames){
                    
                    Titan__c newTitan = new Titan__c(Name = name, Technology__c = newCurriculum.Name,  Curriculum__c = newCurriculum.Id);
                    newTitans.add(newTitan);
                    
                }
                insert newTitans;*/
            
            /*
                List<Skill__c> newSkills = new List<Skill__c>();
                
                List<String> skillNames = new List<String>{'Test Skill1', 'Test Skill2', 'Test Skill3'};
                
                    for(Titan__c t : [SELECT Name FROM Titan__c]){   
                    
                		for(String name : skillNames){
                    
                    	Skill__c newSkill = new Skill__c(Name = name, Titan__c = t.ID, Skill_Breakdown__c = 'test', Skill_Type__c = 'coding', Assigments__c='Test');
                    	newSkills.add(newSkill);
                    
                }
                    }
                insert newSkills;
                
                //create a list of exams
                List<Exam__c> testExams = new List<Exam__c>();
                
                for(Titan__c t : [SELECT Name FROM Titan__c]){
                	for(Integer i=0; i<4; i++){
                    	Exam__c createExam = new Exam__c(Name='Exam'+i, Default_Passing_Grade__c = 65.0, Titan__c = t.Id);
                    	testExams.add(createExam);
                }
            }
                insert testExams;
           }
            */
        }