HeroHubPackage/main/default/objects/Cohort_Week__c/Cohort_Week__c.object-meta.xml
<CustomObject>
    <description>For winning squads/Squad Leaderboard</description>
    <label>Cohort Week</label>
    <nameField>
        <label>Cohort Week Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cohort Weeks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HeroHubPackage/main/default/objects/Cohort_Week__c/fields/Winning_Squad__c.field-meta.xml
<CustomField>
    <fullName>Winning_Squad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Winning Squad</label>
    <referenceTo>Squad__c</referenceTo>
    <relationshipLabel>Cohort Weeks</relationshipLabel>
    <relationshipName>Cohort_Weeks</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Squad__c/Squad__c.object-meta.xml
<CustomObject>
    <label>Squad</label>
    <nameField>
        <label>Squad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Squads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HeroHubPackage/main/default/objects/Squad__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Squads</relationshipLabel>
    <relationshipName>Squads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HeroHubPackage/main/default/classes/updatedTeamLeaderboardHandler.cls
//////////////////////////////////////////////////////////////////////
//
// Name: updatedSquadLeaderboardHandler
// Author: Tobias Diaz, Raksha Jha
// Created: 1/20/22
// Last Updated: 1/25/22
// Description: The handler for our updatedTeamLeaderboard.
// 
//////////////////////////////////////////////////////////////////////

public without sharing class updatedTeamLeaderboardHandler {
    
    @AuraEnabled(cacheable=true)
    public static List<AggregateResult> getWeeksWon()
    {
        /*Unlike the other leaderboards, we don't care who the logged in user is for the team leaderboard.
        Here, we're making a query to a Cohort Week custom object That gets a name of the top 3 winning squads from
        all cohorts and arranges the results from highest to lowest winning squad score.*/
        return [SELECT Winning_Squad__r.Team__r.Name Team, COUNT(Winning_Squad__c) Weeks_Won FROM Cohort_Week__c 
        GROUP BY Winning_Squad__r.Team__r.Name ORDER BY COUNT(Winning_Squad__c) DESC LIMIT 3];
    }
}