HeroHubPackage/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Projects listed in the Portfolio.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/Roles_Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Roles_Responsibilities__c</fullName>
    <label>Roles and Responsibilities</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/Technologies__c.field-meta.xml
<CustomField>
    <fullName>Technologies__c</fullName>
    <label>Technologies</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

HeroHubPackage/main/default/objects/Project__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/classes/PortfolioProjectController.cls
/////////////////////////////////////////////////////
//
//  Name: PortfolioProjectController
//  Author: Murrai Scanlon
//  Description: This controller queries Project data needed to display on the Portfolio Project Aura component.
//  	It also allows the user to create a new project from the Portfolio Project Aura component. However, the
//  	Save functionality for a project Update is not currently working.
//  
//
///////////////////////////////////////////////////

public class PortfolioProjectController {
    

    
    @AuraEnabled
    // Get the Project data for the running user
    public static List<Project__c> getProjects(Id userIdFromPage){
        
        //Testing specific hero user: 0055f000000mwrOAAQ
        //Testing sys admin id: 0055f000000mn0YAAQ
        //Testing running user: :userIdFromPage
        
        List<Project__c> projects = new List<Project__c>();
        
        projects = [SELECT id, Name, Description__c, Roles_Responsibilities__c, Technologies__c, User__c 
                                 FROM Project__c
                                 WHERE User__r.Id = :userIdFromPage
                                 ORDER BY Name ASC
                                ];
        
        return projects;
    }
    
    @AuraEnabled
    // Create or update project information provided by the Portfolio Projects Aura component
    // The creation functionality is working, but the update functionality is not
    public static String createProject(Project__c projObj, Boolean updateParam){
        
        projObj.User__c = UserInfo.getUserId(); // Assign running user to new project
        
        if(updateParam){
            update projObj; // If the incoming parameter indicates and update, perform update DML
        } else {
            upsert projObj; // otherwise, create a new project
        }
        
        return projObj.Id; //return the new project Id for display in the Aura component
    }

}