TrialoftheTitansPackage/main/default/objects/Education__c/Education__c.object-meta.xml
<CustomObject>
    <label>Education</label>
    <nameField>
        <label>Education Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Educations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/DateGraduate__c.field-meta.xml
<CustomField>
    <fullName>DateGraduate__c</fullName>
    <label>DateGraduate</label>
    <type>Date</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <label>Degree</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Gpa__c.field-meta.xml
<CustomField>
    <fullName>Gpa__c</fullName>
    <label>Gpa</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/Major__c.field-meta.xml
<CustomField>
    <fullName>Major__c</fullName>
    <label>Major</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Education__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Educations</relationshipName>
    <type>Lookup</type>
</CustomField>

PortfolioPackage/main/default/classes/GetEducationInformation.cls
//Mohammed Azad
//Returns a list of the education object based on the user
public with sharing class GetEducationInformation {
    @AuraEnabled(cacheable=true)
    public static List<Education__c> returnEducationList() { 
        id userIdHolder = UserInfo.getUserId();
    	List <Education__c> EducationList = [SELECT Name, Degree__c, Gpa__c, Major__c,DateGraduate__c FROM Education__c WHERE  User__c =: userIdHolder];
        return EducationList;
    }
}