PortfolioPackage/main/default/objects/Custom_Skill__c/Custom_Skill__c.object-meta.xml
<CustomObject>
    <label>Custom_Skill</label>
    <nameField>
        <label>Custom_Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom_Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Custom_Skill__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Custom_Skills</relationshipLabel>
    <relationshipName>Custom_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Projects listed in the Portfolio.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Project__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

TitanHubPackage/main/default/objects/Responsibility__c/Responsibility__c.object-meta.xml
<CustomObject>
    <label>Responsibility</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Responsibility ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsibilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Responsibility__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Responsibilities</relationshipLabel>
    <relationshipName>Responsibilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TitanHubPackage/main/default/objects/Skill_Responsibility__c/Skill_Responsibility__c.object-meta.xml
<CustomObject>
    <label>Skill Responsibility</label>
    <nameField>
        <label>Skill Responsibility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skill Responsibilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Skill_Responsibility__c/fields/Responsibility__c.field-meta.xml
<CustomField>
    <fullName>Responsibility__c</fullName>
    <label>Responsibility</label>
    <referenceTo>Responsibility__c</referenceTo>
    <relationshipLabel>Skill Responsibilities</relationshipLabel>
    <relationshipName>Skill_Responsibilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TitanHubPackage/main/default/classes/ProjectController.cls
// Name: Project Controller
// Author: Rhys Kim
// Created: 6/1/2022
// Updated: TBA
// Descripton: Controller for a single project

public without sharing class ProjectController {

    // get responsibilities
    @AuraEnabled(cacheable=true)
    public static List<Responsibility__c> getResponsibilities(Id projectId) {
        return [SELECT Id, Name FROM Responsibility__c WHERE Project__c = :projectId];
    }

    // get skills
    @AuraEnabled(cacheable=true)
    public static List<Skill_Responsibility__c> getSkills(Id projectId) {
        List<Responsibility__c> proId = new List<Responsibility__c>();
        proId = [SELECT Id FROM Responsibility__c WHERE Project__c = :projectId limit 1];
        return [SELECT Id, Name FROM Skill_Responsibility__c WHERE Responsibility__c = :proId limit 1];
    }
    //get custom skills
    @AuraEnabled(cacheable=true)
    public static List<Custom_Skill__c> getCustomSkills(Id projectId){
        return [SELECT Id, Name, Project__c FROM Custom_Skill__c WHERE Project__c = :projectId];
    }

    // get role
    @AuraEnabled(cacheable=true)
    public static Project__c getRole(Id projectId){
        return [SELECT Role__c FROM Project__c WHERE Id = :projectId];
    }
}