PortfolioPackage/main/default/objects/Custom_Skill__c/Custom_Skill__c.object-meta.xml
<CustomObject>
    <label>Custom_Skill</label>
    <nameField>
        <label>Custom_Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom_Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Custom_Skill__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Custom_Skills</relationshipLabel>
    <relationshipName>Custom_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

TitanHubPackage/main/default/objects/Custom_Skill__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>Custom_Skills</relationshipLabel>
    <relationshipName>Custom_Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Projects listed in the Portfolio.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

TitanHubPackage/main/default/objects/Project__c/fields/Github__c.field-meta.xml
<CustomField>
    <fullName>Github__c</fullName>
    <label>Github</label>
    <type>Url</type>
</CustomField>

TitanHubPackage/main/default/objects/Project__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

TitanHubPackage/main/default/objects/Project__c/fields/Video__c.field-meta.xml
<CustomField>
    <fullName>Video__c</fullName>
    <label>Video</label>
    <type>Url</type>
</CustomField>

TitanHubPackage/main/default/objects/Project__c/fields/Wireframe__c.field-meta.xml
<CustomField>
    <fullName>Wireframe__c</fullName>
    <label>Wireframe</label>
    <type>Url</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/User_Story__c/User_Story__c.object-meta.xml
<CustomObject>
    <label>User Story</label>
    <nameField>
        <label>User Story Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Stories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/User_Story__c/fields/Github__c.field-meta.xml
<CustomField>
    <fullName>Github__c</fullName>
    <label>Github</label>
    <type>Url</type>
</CustomField>

TitanHubPackage/main/default/objects/User_Story__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>User Stories</relationshipLabel>
    <relationshipName>User_Stories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TitanHubPackage/main/default/objects/User_Story__c/fields/Video__c.field-meta.xml
<CustomField>
    <fullName>Video__c</fullName>
    <label>Video</label>
    <type>Url</type>
</CustomField>

TitanHubPackage/main/default/objects/User_Story__c/fields/Wireframe__c.field-meta.xml
<CustomField>
    <fullName>Wireframe__c</fullName>
    <label>Wireframe</label>
    <type>Url</type>
</CustomField>

TitanHubPackage/main/default/objects/User_Story_Skill_Junction__c/User_Story_Skill_Junction__c.object-meta.xml
<CustomObject>
    <label>User Story Skill Junction</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>User Story Skill Junction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Story Skill Junctions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/User_Story_Skill_Junction__c/fields/Custom_Skill__c.field-meta.xml
<CustomField>
    <fullName>Custom_Skill__c</fullName>
    <label>Custom Skill</label>
    <referenceTo>Custom_Skill__c</referenceTo>
    <relationshipLabel>User Story Skill Junctions</relationshipLabel>
    <relationshipName>User_Story_Skill_Junctions</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TitanHubPackage/main/default/objects/User_Story_Skill_Junction__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <referenceTo>User_Story__c</referenceTo>
    <relationshipLabel>User Story Skill Junctions</relationshipLabel>
    <relationshipName>User_Story_Skill_Junctions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TitanHubPackage/main/default/objects/Video__c/Video__c.object-meta.xml
<CustomObject>
    <label>Video</label>
    <nameField>
        <label>Video Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanHubPackage/main/default/classes/UserStoryController.cls
public without sharing class UserStoryController {
    @AuraEnabled(cacheable=true)
    public static List<User_Story__c> getUserStories(ID projectId) {
        return [SELECT Name, Description__c, Github__c, Wireframe__c, Video__c 
                FROM User_Story__c WHERE Project__r.Id = :projectId];
    }

    @AuraEnabled(cacheable=true)
    public static Project__c getProjectInfo(ID titanId){
       return [SELECT Name, Id FROM Project__c WHERE Titan__r.Id = :titanId LIMIT 1];
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, List<String>> getProjectSkill(ID projectId) {
        List<User_Story_Skill_Junction__c> storySkills =  [SELECT Name, Custom_Skill__r.name, User_Story__r.name 
                                                           FROM User_Story_Skill_Junction__c 
                                                           WHERE User_Story__r.Project__r.Id= :projectId];

        Map<String, List<String>> skillMap = new Map<String, List<String>>();

        for(User_Story_Skill_Junction__c item : storySkills){
            
            String skillName = item.Custom_Skill__r.name;
            String storyName = item.User_Story__r.name;

            //System.debug(skillName + ' ' + storyName);

            if(!skillMap.containsKey(skillName)){
                skillMap.put(skillName, new List<String>());
                
            }
            skillMap.get(skillName).add(storyName);
        }
    
        //System.debug(skillMap);

        return skillMap;
    }
}