Trial of the Titans/CorePackage/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Assigments__c.field-meta.xml
<CustomField>
    <fullName>Assigments__c</fullName>
    <description>Assignments for the Skills in Trial of the Titans</description>
    <label>Assigments</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Skill_Breakdown__c.field-meta.xml
<CustomField>
    <fullName>Skill_Breakdown__c</fullName>
    <description>Text to describe the skill of a Titan in Trial of the Titans</description>
    <label>Skill Breakdown</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

P3/force-app/main/default/objects/Skill__c/fields/Skill_Type__c.field-meta.xml
<CustomField>
    <fullName>Skill_Type__c</fullName>
    <description>Type of skill for Skills in Trial of The Titans</description>
    <label>Skill Type</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Coding</fullName>
            </value>
            <value>
                <fullName>Soft Skills</fullName>
            </value>
            <value>
                <fullName>Exams</fullName>
            </value>
            <value>
                <fullName>Data Management</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Skills</relationshipLabel>
    <relationshipName>Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CorePackage/main/default/objects/Titan__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Technology for the Titan in Trial of The Titan</description>
    <label>Technology</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <description>Technologies in the Trial of The Titans</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

TrainerHubPackage/main/default/classes/AddEquivalencyComponentTest.cls
@isTest
public class AddEquivalencyComponentTest {
    @TestSetup
    public static void makeData(){
        List<Titan__c> titanList = new List<Titan__c>();
        List<Titan__c> currTitans = new List<Titan__c>();
        titanList.add(new Titan__c(Name='Hercules', Technology__c='Java'));
        insert titanList;

        currTitans = [SELECT Name FROM Titan__c];
        List<Skill__c> skillList = new List<Skill__c>();
        skillList.add(new Skill__c(Name='Java', Titan__c= currTitans[0].id, Assigments__c='yeah', Skill_Breakdown__c='hahaha', Skill_Type__c='Coding'));
        skillList.add(new Skill__c(Name='Bootstrap', Titan__c= currTitans[0].id, Assigments__c='yeah', Skill_Breakdown__c='hahaha', Skill_Type__c='Coding'));
        skillList.add(new Skill__c(Name='Speaking', Titan__c= currTitans[0].id, Assigments__c='yeah', Skill_Breakdown__c='hahaha', Skill_Type__c='Coding'));
        insert skillList;
    }

    @isTest
    public static void getSkillsTest(){
        List<Skill__c> skillList = addEquivalencyComponentAuraController.getSkills();
        System.assertEquals(3, skillList.size());
        System.assertNotEquals(1, skillList.size());
    }
}