TitanHubPackage/main/default/objects/Video__c/Video__c.object-meta.xml
<CustomObject>
    <label>Video</label>
    <nameField>
        <label>Video Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Video__c/fields/Difficulty__c.field-meta.xml
<CustomField>
    <fullName>Difficulty__c</fullName>
    <label>Difficulty</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TitanHubPackage/main/default/objects/Video__c/fields/YoutubeThumbnailLink__c.field-meta.xml
<CustomField>
    <fullName>YoutubeThumbnailLink__c</fullName>
    <description>Follow this format &quot;http://img.youtube.com/vi/VideoUniqueCodeHere/hqdefault.jpg&quot;</description>
    <label>YoutubeThumbnailLink</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

TitanHubPackage/main/default/objects/Video__c/fields/YoutubeVideoLink__c.field-meta.xml
<CustomField>
    <fullName>YoutubeVideoLink__c</fullName>
    <description>Follow this format &quot;https://www.youtube.com/embed?v=UNIQUEYOUTUBEID&quot;</description>
    <label>YoutubeVideoLink</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

TitanHubPackage/main/default/classes/VideoControllerTest.cls
///////////////////////////////////////////////////////////////////////////////// 
// 
// Name: VideoControllerTest
// Author: Christopher Brennan
// Created: 01/26/2022
// Updated: 01/26/2022
// Description: Testing VideoController
// 
/////////////////////////////////////////////////////////////////////////////////

@isTest
public class VideoControllerTest {
    @isTest private static void testGetVideos()
    {
        // create the test video
        Video__c vid = new Video__c(Name = 'test1', YoutubeThumbnailLink__c = 'linkTest', YoutubeVideoLink__c = 'vidTest', Difficulty__c = 'Beginner');

        insert vid;
        
        List<Video__c> vidList = new List<Video__c>();
        // call to test the videoController function
        vidList = VideoController.getVideos();
        
        // test for pass
        System.assertEquals(vid.Name, vidList[0].Name);
        // test for failure
        System.assertNotEquals('failure', vidList[0].Name);
    }
}