TitanHubPackage/main/default/objects/Video__c/Video__c.object-meta.xml
<CustomObject>
    <label>Video</label>
    <nameField>
        <label>Video Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Videos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Video__c/fields/Difficulty__c.field-meta.xml
<CustomField>
    <fullName>Difficulty__c</fullName>
    <label>Difficulty</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beginner</fullName>
            </value>
            <value>
                <fullName>Intermediate</fullName>
            </value>
            <value>
                <fullName>Advanced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TitanHubPackage/main/default/objects/Video__c/fields/IsCurrentVideo__c.field-meta.xml
<CustomField>
    <fullName>IsCurrentVideo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCurrentVideo</label>
    <type>Checkbox</type>
</CustomField>

TitanHubPackage/main/default/objects/Video__c/fields/YoutubeThumbnailLink__c.field-meta.xml
<CustomField>
    <fullName>YoutubeThumbnailLink__c</fullName>
    <description>Follow this format &quot;http://img.youtube.com/vi/VideoUniqueCodeHere/hqdefault.jpg&quot;</description>
    <label>YoutubeThumbnailLink</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

TitanHubPackage/main/default/objects/Video__c/fields/YoutubeVideoLink__c.field-meta.xml
<CustomField>
    <fullName>YoutubeVideoLink__c</fullName>
    <description>Follow this format &quot;https://www.youtube.com/embed?v=UNIQUEYOUTUBEID&quot;</description>
    <label>YoutubeVideoLink</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

TitanHubPackage/main/default/classes/VideoController.cls
///////////////////////////////////////////////////////////////////////////////// 
// 
// Name: VideoController
// Author: Christopher Brennan
// Created: 01/25/2022
// Updated: 01/25/2022
// Description: Used to pull video records from the org to be used in the videoTutorial LWC
// 
/////////////////////////////////////////////////////////////////////////////////

public class VideoController {

	@AuraEnabled(cacheable=true)
    public static list<Video__c> getVideos()
    {
        List<Video__c> vids = new List<Video__c>();
        // collect all records from the video object
        vids = [SELECT Name, YoutubeVideoLink__c, YoutubeThumbnailLink__c, IsCurrentVideo__c, Difficulty__c FROM Video__c];
    
	    return vids;
    }
}