TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P3/force-app/main/default/objects/Exam__c/fields/Next_Exam__c.field-meta.xml
<CustomField>
    <fullName>Next_Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Next Exam</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The next exam must be within the same Titan!</errorMessage>
        <filterItems>
            <field>Exam__c.Titan__c</field>
            <operation>equals</operation>
            <valueField>$Source.Titan__c</valueField>
        </filterItems>
        <filterItems>
            <field>Exam__c.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Previous Exam</relationshipLabel>
    <relationshipName>Next_Exam</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/Exam_Question__c.object-meta.xml
<CustomObject>
    <!---->
    <label>Exam Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam_Question__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

P3/force-app/main/default/objects/Exam_Question__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <formula>IF( ISBLANK( Passing_Grade_Override__c ), ( Total_Correct__c / Total_Answers__c ) &gt;=  Exam__r.Default_Passing_Grade__c, ( Total_Correct__c / Total_Answers__c ) &gt;=  Passing_Grade_Override__c )</formula>
    <label>Pass</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Total_Answers__c.field-meta.xml
<CustomField>
    <fullName>Total_Answers__c</fullName>
    <label>Total Answers</label>
    <summaryForeignKey>Hero_Answer__c.Exam_Result__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Total_Correct__c.field-meta.xml
<CustomField>
    <fullName>Total_Correct__c</fullName>
    <label>Total Correct</label>
    <summaryFilterItems>
        <field>Hero_Answer__c.Correct__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Hero_Answer__c.Exam_Result__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P3/force-app/main/default/classes/ExamListTest.cls
@isTest
public class ExamListTest {
	@testSetup
    static void testSetup(){
        HeroHubTestUtilities.createUsers();
    }
    
    @isTest
    static void checkExams(){
        Exam__c newExam = new Exam__c(Name='testExam');
       	database.insert(newExam);
        Exam_Question__c newQuestion = new Exam_Question__C(Name='testQuestion');
        database.insert(newQuestion);
        Account userAcct = [SELECT Id FROM Account Where name = 'User' Limit 1];
        Exam_Result__c newResult = new Exam_Result__c(Status__c = 'Unassigned', Exam__c = newExam.Id, Account__c = userAcct.Id);
        database.insert(newResult);
        
        
       List<Exam__c> examsList = [SELECT Id, 
                                    Titan__r.Name, 
                                    Name,
                                    Next_Exam__c,
                                    (SELECT Pass__c, 
                                            Total_Answers__c, 
                                            Total_Correct__C,
                                     		Status__c,
                                            CreatedDate
                                            FROM Exam_Results__r 
                                     	       WHERE Account__c = :userAcct.Id 
                                            )
                                    FROM Exam__c];
        
        ExamList newList = new ExamList(examsList[0]);
        
        system.assert(newList.isPassed == false);
        system.assert(newList.assigned == false);
        
    }
    
    @isTest
    static void isAssigned() {
     	Exam__c newExam = new Exam__c(Name='testExam');
       	database.insert(newExam);
        Exam_Question__c newQuestion = new Exam_Question__C(Name='testQuestion');
        database.insert(newQuestion);
        Account userAcct = [SELECT Id FROM Account Where name = 'User' Limit 1];
        Exam_Result__c newResult = new Exam_Result__c(Status__c = 'Assigned', Exam__c = newExam.Id, Account__c = userAcct.Id);
        database.insert(newResult);
        
        
       List<Exam__c> examsList = [SELECT Id, 
                                    Titan__r.Name, 
                                    Name,
                                    Next_Exam__c,
                                    (SELECT Pass__c, 
                                            Total_Answers__c, 
                                            Total_Correct__C,
                                     		Status__c,
                                            CreatedDate
                                            FROM Exam_Results__r 
                                     	       WHERE Account__c = :userAcct.Id 
                                            )
                                    FROM Exam__c];
        
        ExamList newList = new ExamList(examsList[0]);
        
        system.assert(newList.assigned == true);
    }
}