TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrainerHubPackage/main/default/classes/ExamAssignmentControllerTest.cls
@istest
public with sharing class ExamAssignmentControllerTest {
    @IsTest
    static void singlePositiveTest() {
        //Populate Data
        Account acc = new Account(Name='test');
        insert acc;
        Exam__c ex = new Exam__c(Name='test');
        insert ex;
        Exam_Result__c exam = new Exam_Result__c(Status__c='Assigned', Account__c = acc.Id, Exam__c = ex.Id );
        insert exam;
        List<Exam_Result__c> result = ExamAssignmentController.getExams();
        System.assertEquals(1, result.size(), 'Return size is not equal to number inserted');
    }
    @IsTest
    static void bulkPositiveTest(){
        
        Test.startTest();
        Account acc = new Account(Name='test');
        insert acc;
        Exam__c ex = new Exam__c(Name='test');
        insert ex;
        
        List<Exam_Result__c> ExamList = new List<Exam_Result__c>();
        
        for(Integer i = 0; i<200; i++) {
            ExamList.add(new Exam_Result__c(Status__c='Assigned', Account__c = acc.Id, Exam__c = ex.Id ));
            
        }
        insert ExamLIst;

        List<Exam_Result__c> result = ExamAssignmentController.getExams();
        System.assertEquals(200, result.size(), 'return size is equal to number inserted');
        Test.stopTest();  
    }
    @IsTest
    static void negativeTest(){
        Exam_Result__c Exam = new Exam_Result__c();
        //populate no fields
        List<Exam_Result__c> result = ExamAssignmentController.getExams();
        system.assertEquals(0, result.size());
    }
}