TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam__c/fields/Default_Passing_Grade__c.field-meta.xml
<CustomField>
    <fullName>Default_Passing_Grade__c</fullName>
    <label>Default Passing Grade</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Skill__c/fields/Skill_Breakdown__c.field-meta.xml
<CustomField>
    <fullName>Skill_Breakdown__c</fullName>
    <description>Text to describe the skill of a Titan in Trial of the Titans</description>
    <label>Skill Breakdown</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Skills</relationshipLabel>
    <relationshipName>Skills</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanPage/Main/default/main/default/classes/TitanPageApexController.cls
public without sharing class TitanPageApexController {
    public TitanPageApexController() {
    }

    @AuraEnabled
    public static User fetchUser() {
        //Method for retrieving Current User information
        User oUser = [SELECT id,FirstName,LastName FROM User WHERE id =:UserInfo.getUserId()];
        return oUser; 
    }

    @AuraEnabled
    public static List<Titan__c> getTitans() {
        //Method for retrieving list of titans
        List<Titan__c> titanList = [SELECT Name, Id FROM Titan__c];
        return titanList;
    }

		//Id titanId = 'a041100000HhiF6AAJ';
    
    @AuraEnabled
    public static List<Exam__c> getExams(Id titanId) {
        //Method for retrieving list of associated exams
 
        List<Exam__c> examsList = [SELECT Name, Default_Passing_Grade__c, Titan__c FROM Exam__c WHERE Titan__r.Id = :titanId];
        return examsList; 
    }
    
    
    @AuraEnabled
    public static List<Skill__c> getSkills(Id titanId) {
        //Method for retrieving list of associated skills
        List<Skill__c> skillsList = [SELECT Name, Skill_Breakdown__c, Titan__c FROM Skill__c WHERE Titan__r.Id = :titanId];
        return skillsList; 
    }

    
}