TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Exams</relationshipLabel>
    <relationshipName>Exams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Result__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <formula>IF( ISBLANK( Passing_Grade_Override__c ), ( Total_Correct__c / Total_Answers__c ) &gt;=  Exam__r.Default_Passing_Grade__c, ( Total_Correct__c / Total_Answers__c ) &gt;=  Passing_Grade_Override__c )</formula>
    <label>Pass</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>Total_Correct__c / Total_Answers__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Total_Answers__c.field-meta.xml
<CustomField>
    <fullName>Total_Answers__c</fullName>
    <label>Total Answers</label>
    <summaryForeignKey>Hero_Answer__c.Exam_Result__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Total_Correct__c.field-meta.xml
<CustomField>
    <fullName>Total_Correct__c</fullName>
    <label>Total Correct</label>
    <summaryFilterItems>
        <field>Hero_Answer__c.Correct__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Hero_Answer__c.Exam_Result__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Apex_Test_Result__c/Hero_Apex_Test_Result__c.object-meta.xml
<CustomObject>
    <label>Hero Apex Test Result</label>
    <nameField>
        <displayFormat>Test-{0000}</displayFormat>
        <label>Hero Apex Test Result Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Apex Test Results</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrainerHubPackage/main/default/classes/HeroResultPageController.cls
/////////////////////////////////////////////////////
//
//  Name: HeroResultPageController.cls
//  Author: Wootae Yang
//  Description: Controller used in HeroHubPackage/aura/HeroResultPage
//
///////////////////////////////////////////////////


public with sharing class HeroResultPageController {
    @AuraEnabled
    public static List<Exam_Result__c> getResultList(){
        return [SELECT Id, Exam__r.Titan__r.Name, Account__r.Name, Exam__r.Name, Exam__r.Titan__c, Score__c, Total_Correct__c, Total_Answers__c, Pass__c FROM Exam_Result__c WHERE Account__r.Name = 'Gladius Maximus' ];
    }
    @AuraEnabled
    public static List<ID> retrieveResults(){
        List<Hero_Apex_Test_Result__c> myResults=[SELECT id FROM Hero_Apex_Test_Result__c] ;       
        List<ID> ids = new List<ID>();
        
          	for (Hero_Apex_Test_Result__c res : myResults) {
      		ids.add(res.ID);
    		}
        return ids;
    }
    @AuraEnabled
    public static List<String> getTitanList() {
        String[] result = new List<String>();
        for(Exam__c theExam : [SELECT Titan__r.Name FROM Exam__c WHERE Id IN (SELECT Exam__c FROM Exam_Result__c WHERE Account__r.Name = 'Gladius Maximus')]) {
            String name = theExam.Titan__r.Name;
            if(!result.contains(name))
            result.add(name);
        }
        return result;
    }
}