TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

P3/force-app/main/default/objects/Exam__c/fields/Next_Exam__c.field-meta.xml
<CustomField>
    <fullName>Next_Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Next Exam</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>The next exam must be within the same Titan!</errorMessage>
        <filterItems>
            <field>Exam__c.Titan__c</field>
            <operation>equals</operation>
            <valueField>$Source.Titan__c</valueField>
        </filterItems>
        <filterItems>
            <field>Exam__c.Id</field>
            <operation>notEqual</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Previous Exam</relationshipLabel>
    <relationshipName>Next_Exam</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

P3/force-app/main/default/objects/Exam_Result__c/fields/Graded__c.field-meta.xml
<CustomField>
    <fullName>Graded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Graded</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <formula>IF( ISBLANK( Passing_Grade_Override__c ), ( Total_Correct__c / Total_Answers__c ) &gt;=  Exam__r.Default_Passing_Grade__c, ( Total_Correct__c / Total_Answers__c ) &gt;=  Passing_Grade_Override__c )</formula>
    <label>Pass</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <formula>Total_Correct__c / Total_Answers__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Score</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unassigned</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Total_Answers__c.field-meta.xml
<CustomField>
    <fullName>Total_Answers__c</fullName>
    <label>Total Answers</label>
    <summaryForeignKey>Hero_Answer__c.Exam_Result__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Total_Correct__c.field-meta.xml
<CustomField>
    <fullName>Total_Correct__c</fullName>
    <label>Total Correct</label>
    <summaryFilterItems>
        <field>Hero_Answer__c.Correct__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Hero_Answer__c.Exam_Result__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

P3/force-app/main/default/classes/ExamList.cls
/////////////////////////////////////////////////////
//
//  Name: ExamList
//  Author: Josh Miccolo
//  Created: 5/24/2021
//  Updated: 5/25/2021
//  Description: Custom Class to build the Exam Results
//  conducive to parsing in JavaScript
// 
//
///////////////////////////////////////////////////
public class ExamList {

    //Exam Name
    @auraEnabled public String name{get;set;}
    
    //Next Exam
    @auraEnabled public Id nextExam{get;set;}
    
    //Assigned Exam
    @auraEnabled public Boolean assigned{get; set;}

    //Past Exam Results
    @auraEnabled public List<Exam_Result__c> pastResults{get;set;}
    
    //All exam results
    @auraEnabled public List<Exam_Result__c> currentResults{get;set;}

    //Did they pass the exam based on high score?
    @auraEnabled public Boolean isPassed{get;set;}

    @auraEnabled public Decimal highScore{get;set;}
	
    public ExamList( Exam__c exam ) {
        System.debug('In exam List');
        name = exam.Name;
        nextExam = exam.Next_Exam__c;
        currentResults = exam.Exam_Results__r;
        System.debug('In exam list after currentResults' + currentResults);
        pastResults = getPastResults( currentResults );
		System.debug('In exam list after pastResults' + pastResults);
        // check for if there is any current results if not don't set them up
        if (currentResults.size() > 0){
            if(currentResults[0] != null){
                System.debug('In exam List middle');
                isPassed = currentResults[0].Pass__C;
                if(currentResults[0].Total_Answers__c != 0){
                    
                    highScore = currentResults[0].Total_Correct__c/currentResults[0].Total_Answers__c;
                    highScore = highScore.setScale(2);
                    
                }
                else{
                        
                    highScore = null;
                    
                }
    
                if(currentResults[0].Status__c == 'Assigned' || currentResults[0].Status__c == 'Completed'){
                    assigned = true;
                }
                else{
                    assigned = false;
                }
            }
            else{
                isPassed = false;
                highScore = null;
                assigned = false;
            }
        }
        System.debug('In exam List end');
    }

    private List<Exam_Result__c> getPastResults(List<Exam_Result__c> results){
        
        //Use CreateDate to return past results older than the past business week
        List<Exam_Result__c> oldResults = [SELECT Pass__c, 
                                        Total_Answers__c, 
                                        Total_Correct__C,
                                        CreatedDate 
                                        FROM Exam_Result__c 
                                        WHERE Graded__C = true 
                                        AND Id IN :results 
                                        AND CreatedDate < THIS_WEEK 
                                        ORDER BY Score__c DESC NULLS LAST];
        
        return oldResults;
        
    }
}