TrialoftheTitansPackage/main/default/objects/Exam__c/Exam__c.object-meta.xml
<CustomObject>
    <label>Exam</label>
    <nameField>
        <label>Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exam_Result__c/Exam_Result__c.object-meta.xml
<CustomObject>
    <label>Exam Result</label>
    <nameField>
        <displayFormat>ExamResult-{0000}</displayFormat>
        <label>Exam Result Numer</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exam Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Exam__c.field-meta.xml
<CustomField>
    <fullName>Exam__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exam</label>
    <referenceTo>Exam__c</referenceTo>
    <relationshipLabel>Exam Results</relationshipLabel>
    <relationshipName>Exam_Results</relationshipName>
    <type>Lookup</type>
</CustomField>

P3/force-app/main/default/objects/Exam_Result__c/fields/Graded__c.field-meta.xml
<CustomField>
    <fullName>Graded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Graded</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <formula>IF( ISBLANK( Passing_Grade_Override__c ), ( Total_Correct__c / Total_Answers__c ) &gt;=  Exam__r.Default_Passing_Grade__c, ( Total_Correct__c / Total_Answers__c ) &gt;=  Passing_Grade_Override__c )</formula>
    <label>Pass</label>
    <type>Checkbox</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Total_Answers__c.field-meta.xml
<CustomField>
    <fullName>Total_Answers__c</fullName>
    <label>Total Answers</label>
    <summaryForeignKey>Hero_Answer__c.Exam_Result__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Exam_Result__c/fields/Total_Correct__c.field-meta.xml
<CustomField>
    <fullName>Total_Correct__c</fullName>
    <label>Total Correct</label>
    <summaryFilterItems>
        <field>Hero_Answer__c.Correct__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Hero_Answer__c.Exam_Result__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

HeroHubPackage/main/default/classes/ExamList.cls
/////////////////////////////////////////////////////
//
//  Name: ExamList
//  Author: Josh Miccolo
//  Created: 5/24/2021
//  Updated: 5/25/2021
//  Description: Custom Class to build the Exam Results
//  conducive to parsing in JavaScript
// 
//
///////////////////////////////////////////////////
public class ExamList {

    //Exam Name
    @auraEnabled public String name{get;set;}

    //Past Exam Results
    @auraEnabled public List<Exam_Result__c> pastResults{get;set;}
    
    //All exam results
    @auraEnabled public List<Exam_Result__c> currentResults{get;set;}

    @auraEnabled public Boolean isPassed{get;set;}
    @auraEnabled public Decimal highScore{get;set;}
	
    public ExamList( Exam__c exam ) {

        name = exam.Name;
        currentResults = exam.Exam_Results__r;
        pastResults = getPastResults( currentResults );

        // If no results isPassed is false
        if(currentResults.size() != 0){
            isPassed = currentResults[0].Pass__C;

            // If no answers highScore is null
            if(currentResults[0].Total_Answers__c != 0){
                
                highScore = currentResults[0].Total_Correct__c/currentResults[0].Total_Answers__c;
            
            }
            else{
                
                highScore = null;
            
            }
        }
        else{
            
            isPassed = false;
        
        }
    }

    private List<Exam_Result__c> getPastResults(List<Exam_Result__c> results){
        
        //Use CreateDate to return past results older than the past business week
        List<Exam_Result__c> oldResults = [SELECT Pass__c, 
                                        Total_Answers__c, 
                                        Total_Correct__C,
                                        CreatedDate 
                                        FROM Exam_Result__c 
                                        WHERE Graded__C = true 
                                        AND Id IN :results 
                                        AND CreatedDate < THIS_WEEK 
                                        ORDER BY Total_Correct__c ];
        
        return oldResults;
    }
}