QCHubPackage/main/default/objects/QC_Question__c/QC_Question__c.object-meta.xml
<CustomObject>
    <description>Pre-made question for QC Interviews.</description>
    <label>QC Question</label>
    <nameField>
        <label>QC Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Question__c/fields/Expected_Answer__c.field-meta.xml
<CustomField>
    <fullName>Expected_Answer__c</fullName>
    <label>Expected Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Question__c/fields/QC_Question_Deck__c.field-meta.xml
<CustomField>
    <fullName>QC_Question_Deck__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QC Question Deck</label>
    <referenceTo>QC_Question_Deck__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>QC_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question__c/fields/Question_Body__c.field-meta.xml
<CustomField>
    <fullName>Question_Body__c</fullName>
    <label>Question Body</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Question_Deck__c/QC_Question_Deck__c.object-meta.xml
<CustomObject>
    <label>QC Question Deck</label>
    <nameField>
        <label>QC Question Deck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Question Decks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

QCHubPackage/main/default/classes/QCQuestionEditController.cls
public with sharing class QCQuestionEditController {
     
    @AuraEnabled(cacheable=true)
     public static List<QC_Question__c> getQCQuestion(ID recordID ,Integer pageSize, Integer pageNumber) {
         Integer offset = (pageNumber - 1) * pageSize;
         List<QC_Question__c> qcQuestionList = new List<QC_Question__c>();
         
         try{
         qcQuestionList= [SELECT ID,Name,QC_Question_Deck__r.Name,Expected_Answer__c,Question_Body__c  FROM QC_Question__c WITH SECURITY_ENFORCED LIMIT :pageSize OFFSET :offset ];
           
         }
         catch( System.QueryException ex)
        {
            throw new SecurityException('Your user does not have the necessary permissions');
        }
         return  qcQuestionList;
    }
    @AuraEnabled(cacheable=true)
    public static void deleteQCQuestion( QC_Question__c qcq ){

        delete qcq;


    }
    
    @AuraEnabled(cacheable=true)
    public static void deleteQCQuestionRows( List<QC_Question__c> sRows ){

        delete sRows;


    }
    
    @AuraEnabled
    public static void updateQCQuestion( QC_Question__c qcqUpdate){

        update qcqUpdate;


    }

    @AuraEnabled(cacheable=true)
    public static List<QC_Question__c> getQuestion(){

        List<QC_Question__c> questionList = new List<QC_Question__c>();
        
        try{
            questionList= [SELECT ID,Name,QC_Question_Deck__r.Name,Expected_Answer__c,Question_Body__c  FROM QC_Question__c WITH SECURITY_ENFORCED];
              
            }
            catch( System.QueryException ex)
           {
               throw new SecurityException('Your user does not have the necessary permissions');
           }
            return  questionList;
        
    }

    @AuraEnabled
    public static void deleteQuestions(list<Id> questions){
        try {
            list<QC_Question__c> questionIdsToDelete = new list<QC_Question__c>();
            System.debug('questionIds ====> '+questions);
            for(Id qc : questions) {
                questionIdsToDelete.add(new QC_Question__c(Id = qc));
            }
            if(!questionIdsToDelete.isEmpty()) {
                delete questionIdsToDelete;
            }
        }
        catch(Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }


}