HeroHubPackage/main/default/objects/Account/fields/Squad__c.field-meta.xml
<CustomField>
    <fullName>Squad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The squad of the hero from The Trial of The Titans</description>
    <label>Squad</label>
    <referenceTo>Squad__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Account/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Hero&apos;s Team in The Trial of The Titans</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

HeroHubPackage/main/default/objects/Squad__c/Squad__c.object-meta.xml
<CustomObject>
    <label>Squad</label>
    <nameField>
        <label>Squad Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Squads</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

HeroHubPackage/main/default/objects/Squad__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Squads</relationshipLabel>
    <relationshipName>Squads</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

TitanPage/Main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanPage/Main/default/objects/Team__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Team a User belongs to.</description>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

HeroHubPackage/main/default/classes/UserContextInfoTest.cls
@isTest
public class UserContextInfoTest {
	
    @isTest
    static void userContextInfoReturnsAccount(){
        HeroHubTestUtilities.createRightUser();
        
        User rightUser = [SELECT Id FROM USER WHERE alias = 'testUser' Limit 1];
        Account rightAccount = [SELECT Id FROM Account Where name = 'User' Limit 1];
		
        UserContextInfo userInfo = new UserContextInfo(rightUser.Id);
            
        system.assertEquals(rightAccount.Id, userInfo.acc.Id);
            
    }
    
    @isTest
    static void userContextInfoReturnsTeam(){
        HeroHubTestUtilities.createRightUser();
        User rightUser = [SELECT Id FROM USER WHERE alias = 'testUser' Limit 1];
        Team__C rightTeam = [SELECT Id FROM Team__c WHERE Name = 'Amplifire'];
        
  		UserContextInfo userInfo = new UserContextInfo(rightUser.Id);
        
        system.assertEquals(rightTeam.Id, userInfo.team.Id);
    }
    
    @isTest
    static void userContextInfoReturnsSquad(){
        HeroHubTestUtilities.createRightUser();
        User rightUser = [SELECT Id FROM USER WHERE alias = 'testUser' Limit 1];
       	Squad__C rightSquad = [SELECT Id FROM Squad__c WHERE Name = 'This is Fire'];
        
  		UserContextInfo userInfo = new UserContextInfo(rightUser.Id);
        
        system.assertEquals(rightSquad.Id, userInfo.squad.Id);
    }
    
    @isTest
    static void userContextInfoReturnsAllTitans(){
        HeroHubTestUtilities.createRightUser();
        HeroHubTestUtilities.createTitans();
        
        User rightUser = [SELECT Id FROM USER WHERE alias = 'testUser' Limit 1];
        List<Titan__c> allTitans = [SELECT Id, Name FROM Titan__c];
        
        UserContextInfo userInfo = new UserContextInfo(rightUser.Id);
        
        for(Titan__c titan: allTitans){
            
            system.assert(userInfo.getAllTitans().contains(titan));
        
        }
        
    }
    
    @isTest
    static void userContextInfogetExams(){
        HeroHubTestUtilities.fullSetup();
        User rightUser = [SELECT Id FROM USER WHERE alias = 'testUser' Limit 1];
        
        UserContextInfo userInfo = new UserContextInfo(rightUser.Id);
        
        system.debug(userInfo);
        
        
    }
    
    @isTest
    static void userContextInfoThrowsWrongUser(){
        HeroHubTestUtilities.createRightUser();
        User wrongUser = [SELECT Id FROM USER WHERE alias = 'testTrainer' Limit 1];
        
        try{
            UserContextInfo userInfo = new UserContextInfo(wrongUser.Id);
            system.assert(false);
        }
        catch(Exception e){
            system.debug(e.getMessage());
            system.assert(true);
        }
    }
    
}