PortfolioPackage/main/default/objects/Certification_Exam__c/Certification_Exam__c.object-meta.xml
<CustomObject>
    <label>Certification Exam</label>
    <nameField>
        <label>Certification Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Exam_Topic__c/Exam_Topic__c.object-meta.xml
<CustomObject>
    <label>Exam Topic</label>
    <nameField>
        <label>Exam Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Exam_Topic__c/fields/Certification_Exam__c.field-meta.xml
<CustomField>
    <fullName>Certification_Exam__c</fullName>
    <label>Certification Exam</label>
    <referenceTo>Certification_Exam__c</referenceTo>
    <relationshipLabel>Exam Topics</relationshipLabel>
    <relationshipName>Exam_Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TitanHubPackage/main/default/objects/Exam_Topic__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Titan_Topic__c/Titan_Topic__c.object-meta.xml
<CustomObject>
    <label>Titan Topic</label>
    <nameField>
        <displayFormat>TT-{0000}</displayFormat>
        <label>Titan Topic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Titan Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Titan_Topic__c/fields/Exam_Topic__c.field-meta.xml
<CustomField>
    <fullName>Exam_Topic__c</fullName>
    <label>Exam Topic</label>
    <referenceTo>Exam_Topic__c</referenceTo>
    <relationshipLabel>Titan Topics</relationshipLabel>
    <relationshipName>Titan_Topics</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TitanHubPackage/main/default/objects/Titan_Topic__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Titan Topics</relationshipLabel>
    <relationshipName>Titan_Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TitanHubPackage/main/default/classes/TitanHubCertDetailsController.cls
///////////////////////////////////////////////////////////////////////////////// 
// 
// Name: TitanHubCertDetailsController
// Author: Alan Huang
// Created: 01/25/2022
// Updated: 01/25/2022
// Description: Apex Controller for titanHubCertDetails LWC component
// 
/////////////////////////////////////////////////////////////////////////////////
//
public with sharing class TitanHubCertDetailsController {
    
    @AuraEnabled(cacheable=true)
    public static List<Certification_Exam__c> getCertDetails(Id titanId) {
        List<Titan_Topic__c> titanTopics = [SELECT Exam_Topic__r.Certification_Exam__c
                                            FROM Titan_Topic__c WHERE Titan__c=:titanId];
        List<Id> certExamIds = new List<Id>();
        List<Id> examTopicIds = new List<Id>();
        for (Titan_Topic__c titanTopic : titanTopics) {
            certExamIds.add(titanTopic.Exam_Topic__r.Certification_Exam__c);
            examTopicIds.add(titantopic.Exam_Topic__c);
        }
        
        List<Certification_Exam__c> certExams = [SELECT Name,
                                                 (SELECT Name, Weight__c FROM Exam_Topics__r WHERE Id=:examTopicIds)
                                                 FROM Certification_Exam__c WHERE Id=:certExamIds];
        return certExams;
    }
    
}