PortfolioPackage/main/default/objects/Certification_Exam__c/Certification_Exam__c.object-meta.xml
<CustomObject>
    <label>Certification Exam</label>
    <nameField>
        <label>Certification Exam Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certification Exams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Exam_Topic__c/Exam_Topic__c.object-meta.xml
<CustomObject>
    <label>Exam Topic</label>
    <nameField>
        <label>Exam Topic Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Exam_Topic__c/fields/Certification_Exam__c.field-meta.xml
<CustomField>
    <fullName>Certification_Exam__c</fullName>
    <label>Certification Exam</label>
    <referenceTo>Certification_Exam__c</referenceTo>
    <relationshipLabel>Exam Topics</relationshipLabel>
    <relationshipName>Exam_Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TitanHubPackage/main/default/objects/Exam_Topic__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>Weight</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Technology__c/Technology__c.object-meta.xml
<CustomObject>
    <label>Technology</label>
    <nameField>
        <label>Technology Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Technologies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Titan__c/Titan__c.object-meta.xml
<CustomObject>
    <label>Titan</label>
    <nameField>
        <label>Titan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Titans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

CorePackage/main/default/objects/Titan__c/fields/Technology__c.field-meta.xml
<CustomField>
    <fullName>Technology__c</fullName>
    <description>Technology for the Titan in Trial of The Titan</description>
    <label>Technology</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Technology</valueSetName>
    </valueSet>
</CustomField>

TitanHubPackage/main/default/objects/Titan_Topic__c/Titan_Topic__c.object-meta.xml
<CustomObject>
    <label>Titan Topic</label>
    <nameField>
        <displayFormat>TT-{0000}</displayFormat>
        <label>Titan Topic Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Titan Topics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TitanHubPackage/main/default/objects/Titan_Topic__c/fields/Exam_Topic__c.field-meta.xml
<CustomField>
    <fullName>Exam_Topic__c</fullName>
    <label>Exam Topic</label>
    <referenceTo>Exam_Topic__c</referenceTo>
    <relationshipLabel>Titan Topics</relationshipLabel>
    <relationshipName>Titan_Topics</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TitanHubPackage/main/default/objects/Titan_Topic__c/fields/Titan__c.field-meta.xml
<CustomField>
    <fullName>Titan__c</fullName>
    <label>Titan</label>
    <referenceTo>Titan__c</referenceTo>
    <relationshipLabel>Titan Topics</relationshipLabel>
    <relationshipName>Titan_Topics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/globalValueSets/Technology.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Salesforce</fullName>
    </customValue>
    <description>Technologies in the Trial of The Titans</description>
    <masterLabel>Technology</masterLabel>
</GlobalValueSet>

TitanHubPackage/main/default/classes/TitanHubCertDetailsControllerTest.cls
///////////////////////////////////////////////////////////////////////////////// 
// 
// Name: TitanHubCertDetailsControllerTest
// Author: Alan Huang
// Created: 01/25/2022
// Updated: 01/25/2022
// Description: Test Class for Apex TitanHubCertDetailsController
// 
/////////////////////////////////////////////////////////////////////////////////

@isTest
class TitanHubCertDetailsControllerTest {
    
    @isTest
    static void getCertDetailsTest() {
        Titan__c titan = [SELECT Id FROM Titan__c];
        List<Certification_Exam__c> certExams = titanHubCertDetailsController.getCertDetails(titan.Id);
        
        List<Titan_Topic__c> titanTopics = [SELECT Exam_Topic__r.Certification_Exam__c
                                            FROM Titan_Topic__c WHERE Titan__c=:titan.Id];
        List<Id> certExamIds = new List<Id>();
        List<Id> examTopicIds = new List<Id>();
        for (Titan_Topic__c titanTopic : titanTopics) {
            certExamIds.add(titanTopic.Exam_Topic__r.Certification_Exam__c);
            examTopicIds.add(titantopic.Exam_Topic__c);
        }
        List<Certification_Exam__c> soqlCertExams = [SELECT Name,
                                                     (SELECT Name, Weight__c FROM Exam_Topics__r WHERE Id=:examTopicIds)
                                                     FROM Certification_Exam__c WHERE Id=:certExamIds];
        
        System.assertEquals(certExams, soqlCertExams);
    }
    
    @testSetup
    public static void testSetup() {
        List<Titan__c> titans = new List<Titan__c>{
            new Titan__c(Name='00 - Declarative - Titan 0', Technology__c='Salesforce')
        };
        insert titans;
        
        List<Certification_Exam__c> certExams = new List<Certification_Exam__c>{
        	new Certification_Exam__c(Name='Certification Exam 0')
        };
		insert certExams;
            
		List<Exam_Topic__c> examTopics = new List<Exam_Topic__c>{
            new Exam_Topic__c(Name='Exam Topic 0', Certification_Exam__c=certExams[0].Id, Weight__c=30)
        };
        insert examTopics;
        
        List<Titan_Topic__c> titanTopic = new List<Titan_Topic__c>{
            new Titan_Topic__c(Titan__c=titans[0].Id, Exam_Topic__c=examTopics[0].Id)
        };
		insert titanTopic;
    }
}