TrialoftheTitansPackage/main/default/objects/QC_Question__c/QC_Question__c.object-meta.xml
<CustomObject>
    <description>Pre-made question for QC Interviews.</description>
    <label>QC Question</label>
    <nameField>
        <label>QC Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Question__c/fields/Expected_Answer__c.field-meta.xml
<CustomField>
    <fullName>Expected_Answer__c</fullName>
    <label>Expected Answer</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question__c/fields/QC_Question_Deck__c.field-meta.xml
<CustomField>
    <fullName>QC_Question_Deck__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QC Question Deck</label>
    <referenceTo>QC_Question_Deck__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>QC_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question__c/fields/Question_Body__c.field-meta.xml
<CustomField>
    <fullName>Question_Body__c</fullName>
    <label>Question Body</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/QC_Question_Deck__c/QC_Question_Deck__c.object-meta.xml
<CustomObject>
    <label>QC Question Deck</label>
    <nameField>
        <label>QC Question Deck Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Question Decks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

MockInterviewPackage/main/default/classes/QCQuestionEditController.cls
public with sharing class QCQuestionEditController {
     
    @AuraEnabled
     public static List<QC_Question__c> getQCQuestion(ID recordID ,Integer pageSize, Integer pageNumber) {
         Integer offset = (pageNumber - 1) * pageSize;
         List<QC_Question__c> qcQuestionList = new List<QC_Question__c>();

         qcQuestionList= [SELECT ID,Name,QC_Question_Deck__c,Expected_Answer__c,Question_Body__c  FROM QC_Question__c LIMIT :pageSize OFFSET :offset];
         return  qcQuestionList;
    }
    @AuraEnabled
    public static void deleteQCQuestion( QC_Question__c qcq ){

        delete qcq;


    }
    
    @AuraEnabled
    public static void updateQCQuestion( QC_Question__c qcqUpdate){

        update qcqUpdate;


    }
}