QCHubPackage/main/default/objects/QC_Flag__c/QC_Flag__c.object-meta.xml
<CustomObject>
    <description>Added to a hero&apos;s QC Interview to note comments about the interview.</description>
    <label>QC Flag</label>
    <nameField>
        <label>QC Flag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Flags</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Flag__c/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>QC Flags</relationshipLabel>
    <relationshipName>QC_Flags</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

QCHubPackage/main/default/objects/QC_Interview__c/QC_Interview__c.object-meta.xml
<CustomObject>
    <label>QC Interview</label>
    <nameField>
        <label>QC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>QC Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

QCHubPackage/main/default/objects/QC_Question_Answer__c/QC_Question_Answer__c.object-meta.xml
<CustomObject>
    <label>QC Question Answer</label>
    <nameField>
        <displayFormat>QCA-{000000}</displayFormat>
        <label>QC Question Answer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QC Question Answers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/QC_Question_Answer__c/fields/QC_Interview__c.field-meta.xml
<CustomField>
    <fullName>QC_Interview__c</fullName>
    <description>The QC interview this question/answer data were a part of.</description>
    <inlineHelpText>The QC interview this set of questions and answers are a part of.</inlineHelpText>
    <label>QC Interview</label>
    <referenceTo>QC_Interview__c</referenceTo>
    <relationshipLabel>QC Question Answers</relationshipLabel>
    <relationshipName>QC_Question_Answers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

QCHubPackage/main/default/classes/QCInterviewAuraController.cls
public with sharing class QCInterviewAuraController {


    // ***CURRENTLY NOT IN USE***
    @AuraEnabled
    public static void InsertInterviewData(QC_Interview__c qcInterview, List<QC_Question_Answer__c> qcQA, List<QC_Flag__c> qcFlags) {

        insert qcInterview;

        for (QC_Question_Answer__c qa : qcQA){
            qa.QC_Interview__c = qcInterview.Id;
        }
        for (QC_Flag__c flag : qcFlags){
            flag.QC_Interview__c = qcInterview.Id;
        }

        insert qcQA;
        insert qcFlags;
    }
}