ExamPackage/main/default/objects/Exam_Question__c/Exam_Question__c.object-meta.xml
<CustomObject>
    <label>Exam Question</label>
    <nameField>
        <label>Question Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exam Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Exam_Question__c/fields/Answer_Explanation__c.field-meta.xml
<CustomField>
    <fullName>Answer_Explanation__c</fullName>
    <label>Answer Explanation</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/fields/Correct_Answer_s__c.field-meta.xml
<CustomField>
    <fullName>Correct_Answer_s__c</fullName>
    <label>Correct Answer(s)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/fields/Missing_Word__c.field-meta.xml
<CustomField>
    <fullName>Missing_Word__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Missing Word?</label>
    <type>Checkbox</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <label>Options</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/fields/Question_Text__c.field-meta.xml
<CustomField>
    <fullName>Question_Text__c</fullName>
    <label>Question Text</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/fields/Question_Type__c.field-meta.xml
<CustomField>
    <fullName>Question_Type__c</fullName>
    <label>Question Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Multiple Choice</fullName>
            </value>
            <value>
                <fullName>Multiple Choice - multiple answers</fullName>
            </value>
            <value>
                <fullName>True-false</fullName>
            </value>
            <value>
                <fullName>Matching</fullName>
            </value>
            <value>
                <fullName>Numerical</fullName>
            </value>
            <value>
                <fullName>Missing word</fullName>
            </value>
            <value>
                <fullName>Short answer</fullName>
            </value>
            <value>
                <fullName>Essay</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ExamPackage/main/default/objects/Exam_Question__c/fields/Skill__c.field-meta.xml
<CustomField>
    <fullName>Skill__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Skill</label>
    <referenceTo>Skill__c</referenceTo>
    <relationshipLabel>Exam Questions</relationshipLabel>
    <relationshipName>Exam_Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

ExamPackage/main/default/objects/Question_Assignment__c/Question_Assignment__c.object-meta.xml
<CustomObject>
    <label>Question Assignment</label>
    <nameField>
        <displayFormat>QA-{0000}</displayFormat>
        <label>Question Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Assignments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/objects/Question_Assignment__c/fields/Exam_Question__c.field-meta.xml
<CustomField>
    <fullName>Exam_Question__c</fullName>
    <label>Exam Question</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Question Assignments</relationshipLabel>
    <relationshipName>Question_Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Assignment__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Question_Pool__c</referenceTo>
    <relationshipLabel>Question Assignments</relationshipLabel>
    <relationshipName>Question_Assignments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ExamPackage/main/default/objects/Question_Pool__c/Question_Pool__c.object-meta.xml
<CustomObject>
    <label>Question Pool</label>
    <nameField>
        <label>Question Pool Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Question Pools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Trial of the Titans/CorePackage/objects/Question_Pool__c/fields/Question_Pool__c.field-meta.xml
<CustomField>
    <fullName>Question_Pool__c</fullName>
    <label>Question Pool</label>
    <referenceTo>Exam_Question__c</referenceTo>
    <relationshipLabel>Question Pool</relationshipLabel>
    <relationshipName>Question_Pools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

Trial of the Titans/CorePackage/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <label>Skill Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ExamPackage/main/default/classes/ExportQuestionPoolController.cls
public class ExportQuestionPoolController {
  
    public Id currentQuestionPoolId{get;set;}
    public List <Question_Assignment__c> examQuestionAssignments {get;set;}
    public List <Exam_Question__c> currentExamQuestions{get;set;}
    public Set <Id> currentExamQuestionIds{get;set;}
    public Question_Assignment__c questionAssignment{get;set;}
    public String formattedQuestion{get;set;}
    public List<String> allFormattedQuestions{get;set;}
    public String allFormattedQuestionsString{get; set;}
    
    public ExportQuestionPoolController(ApexPages.StandardController controller){
       	currentQuestionPoolId = ApexPages.currentPage().getparameters().get('id');
        //currentQuestionPoolId ='a0A1F000005izbeUAA';
        currentExamQuestionIds = new Set <Id>();
        questionAssignment = [SELECT id FROM Question_Assignment__c WHERE Question_Pool__c = :currentQuestionPoolId LIMIT 1];
        examQuestionAssignments=[SELECT Id, Exam_Question__c FROM Question_Assignment__c WHERE Question_Pool__c = :currentQuestionPoolId];
        for(Question_Assignment__c QA: examQuestionAssignments){
            currentExamQuestionIds.add(QA.Exam_Question__c);
        }
        
        currentExamQuestions = [SELECT Missing_Word__c, Answer_Explanation__c, Correct_Answer_s__c, options__c, Question_Text__c, Question_Type__c, Skill__c, Name
	                            FROM Exam_Question__c WHERE id in :currentExamQuestionIds];
        formattedQuestion =''; 
		allFormattedQuestions = new List<String>();
        allFormattedQuestionsString ='';
        export(currentExamQuestions);
        formatQuestions(allFormattedQuestions);
    }
   
    public void export(List<Exam_Question__c> currentExamQuestions){
        for(Exam_Question__c currentExamQuestion : currentExamQuestions){
        if(currentExamQuestion.Missing_Word__c == TRUE){
            String delimeter ='_____';
            String beforeSubstring = currentExamQuestion.Question_Text__c.substringBefore(delimeter);
            String afterSubstring = currentExamQuestion.Question_Text__c.substringAfter(delimeter);
            switch on currentExamQuestion.Question_Type__c{
                when 'Multiple Choice'{
                    formatMultipleChoiceQuestionMW(currentExamQuestion, beforeSubstring, afterSubstring);
                }
                when 'True-false'{
                    formatTrueFalseQuestionMW(currentExamQuestion, beforeSubstring, afterSubstring);
                }
                when 'Matching'{
                    formatMatchingQuestionMW(currentExamQuestion, beforeSubstring, afterSubstring);
                }
                when 'Multiple Choice - multiple answers'{
                    formatMultipleChoiceQuestionMultipleAnswersMW(currentExamQuestion, beforeSubstring, afterSubstring);
                }
                when 'Numerical'{
                    formatNumericalQuestionMW(currentExamQuestion, beforeSubstring, afterSubstring);
                }
                when 'Short answer'{
                    formatShortAnswerQuestionMW(currentExamQuestion, beforeSubstring, afterSubstring);
                }
                when 'Essay'{
                    formatEssayQuestionMW(currentExamQuestion, beforeSubstring, afterSubstring);
                } 
            }   
            }
        else{
            switch on currentExamQuestion.Question_Type__c{
                when 'Multiple Choice'{
                    formatMultipleChoiceQuestion(currentExamQuestion);
                }
                when 'True-false'{
                    formatTrueFalseQuestion(currentExamQuestion);
                }
                when 'Matching'{
                    formatMatchingQuestion(currentExamQuestion);
                }
                when 'Multiple Choice - multiple answers'{
                    formatMultipleChoiceQuestionMultipleAnswers(currentExamQuestion);
                }
                when 'Numerical'{
                    formatNumericalQuestion(currentExamQuestion);
                }
                when 'Short answer'{
                    formatShortAnswerQuestion(currentExamQuestion);
                }
                when 'Essay'{
                    formatEssayQuestion(currentExamQuestion);
                }
            }
        }
        }
    }
        
    /*------------------------------ Multiple Choice Question--------------------------------------------------*/
    public String formatMultipleChoiceQuestionMW(Exam_Question__c question, String beforeSubstring, String afterSubstring){
        String incorrectAnswerString = getIncorrectAnswers(question);
        formattedQuestion = '::' + question.Name + '::' + beforeSubstring + '{='+ question.Correct_Answer_s__c+ incorrectAnswerString +getCorrectAnswer(question)+ '}' + afterSubstring;
        allFormattedQuestions.add(formattedQuestion);
        return formattedQuestion;
    }
    
    
    public void formatMultipleChoiceQuestion(Exam_Question__c question){
        String incorrectAnswerString = getIncorrectAnswers(question);
        // GIFT format for MC: ::QuestionName:: QuestionText {= correctAnswer #comment ~incorrectanswers}
        formattedQuestion='::' + question.Name + '::' + question.Question_Text__c +'{='+ question.Correct_Answer_s__c
            + incorrectAnswerString +getCorrectAnswer(question)+ '}' ;
        allFormattedQuestions.add(formattedQuestion);
        system.debug('Formatted Question: '+ formattedQuestion);
        system.debug('all formatted questions: ' + allFormattedQuestions);
    }
    
    /************************* Multiple Choice Multi-Select Question *****************************/
    public void formatMultipleChoiceQuestionMultipleAnswers(Exam_Question__c question){
        String incorrectAnswerString = getIncorrectAnswersMultiSelect(question);
        String correctAnswerString = getCorrectAnswersMultiSelect(question);
        formattedQuestion = '::' + question.Name + '::' + question.Question_Text__c + '{' + correctAnswerString + incorrectAnswerString +getCorrectAnswer(question)+ '}';
        allFormattedQuestions.add(formattedQuestion);
        
    }
    public void formatMultipleChoiceQuestionMultipleAnswersMW(Exam_Question__c question, String beforeSubstring, String afterSubstring){
        String incorrectAnswerString = getIncorrectAnswersMultiSelect(question);
        String correctAnswerString = getCorrectAnswersMultiSelect(question);
        formattedQuestion = '::' + question.Name + '::' + beforeSubstring + '{' + correctAnswerString + incorrectAnswerString +getCorrectAnswer(question)+ '}' + afterSubstring;
        allFormattedQuestions.add(formattedQuestion);
    }
    /*--------------------------- Get Answers Functions -------------------------------------------*/
     public String getCorrectAnswers (Exam_Question__c question){
        List <String> correctAnswers = new List <String>();
        correctAnswers = question.Correct_Answer_s__c.split('\\|\\|'); 
       String correctAnswerString = string.join(correctAnswers, '');
        return correctAnswerString;
    }
    public String getIncorrectAnswers (Exam_Question__c question){
        List <String> options = new List <String>();
        options = question.Options__c.split('\\|\\|');
        system.debug('options: ' + options);
        List<String> incorrectAnswers = new List<String>();
        for(String option : options){ 
            if(option!= question.Correct_Answer_s__c){
                incorrectAnswers.add('~'+option);
            }}  
       String incorrectAnswerString = string.join(incorrectAnswers, '');
        return incorrectAnswerString;
    }
    
      public String getCorrectAnswersMultiSelect (Exam_Question__c question){
        List <String> correctAnswers = new List <String>();
        List<String> res = new List <String>();
        correctAnswers = question.Correct_Answer_s__c.split('\\|\\|'); 
        Integer numCorrectAnswers = correctAnswers.size();
          Integer percentQuestion = 100/numCorrectAnswers;
          String correctAnswerPercent = String.valueOf(percentQuestion);
          for(String correctAnswer: correctAnswers){
              res.add('~%' + correctAnswerPercent + '%' + correctAnswer);
          }
       	String correctAnswerString = string.join(res, '');
        return correctAnswerString;
    }
    public String getIncorrectAnswersMultiSelect (Exam_Question__c question){
        List <String> options = new List <String>();
        options = question.Options__c.split('\\|\\|');
        system.debug('options: ' + options);
        List<String> incorrectAnswers = new List<String>();
        for(String option : options){ 
            if(option!= question.Correct_Answer_s__c){
                incorrectAnswers.add('~%-100%'+option);
            }}  
       String incorrectAnswerString = string.join(incorrectAnswers, '');
        return incorrectAnswerString;
    }
    
    
  /*------------------------------ True or False Question--------------------------------------------------*/
    public void formatTrueFalseQuestion(Exam_Question__c question){
        formattedQuestion ='::' + question.Name+'::'+ question.Question_Text__c + '{'+question.Correct_Answer_s__c+getCorrectAnswer(question)+'}';
        allFormattedQuestions.add(formattedQuestion);
    }
    
    public void formatTrueFalseQuestionMW (Exam_Question__c question, String beforeSubstring, String afterSubstring){
        formattedQuestion = '::' + question.Name + '::' + beforeSubstring + '{'+ question.Correct_Answer_s__c +getCorrectAnswer(question)+ '}' + afterSubstring;
        allFormattedQuestions.add(formattedQuestion);
    }
    /*------------------------------ Matching Questions--------------------------------------------------*/
    public void formatMatchingQuestion(Exam_Question__c question){
        List <String> optionList = new List <String>();
        List <String> answerList = new List <String>();
        List <String> matchAnswers = new List <String>();
        //Map <String, String> matchedAnswers = new Map <String,String>();
        optionList = question.Options__c.split('\\|\\|');
        answerList = question.Correct_Answer_s__c.split('\\|\\|');
        for(Integer i=0; i< optionList.size(); i++){
            matchAnswers.add('=' + optionList[i]);
            matchAnswers.add('->' + answerList[i]);
        }
        //String matchedAnswersString = String.valueOf(matchedAnswers);
        String matchedAnswersString = string.join(matchAnswers,'');
        formattedQuestion = '::' + question.Name + '::' + question.Question_Text__c  +'{'+ matchedAnswersString+ getCorrectAnswer(question)+'}' ;
        allFormattedQuestions.add(formattedQuestion);
    }
    
    public void formatMatchingQuestionMW (Exam_Question__c question, String beforeSubstring, String afterSubstring){
        List <String> optionList = new List <String>();
        List <String> answerList = new List <String>();
        List <String> matchAnswers = new List <String>();
        //Map <String, String> matchedAnswers = new Map <String,String>();
        optionList = question.Options__c.split('\\|\\|');
        answerList = question.Correct_Answer_s__c.split('\\|\\|');
        for(Integer i=0; i< optionList.size(); i++){
            matchAnswers.add('=' + optionList[i]);
            matchAnswers.add('->' + answerList[i]);
        }
        //String matchedAnswersString = String.valueOf(matchedAnswers);
        String matchedAnswersString = string.join(matchAnswers,'');
        formattedQuestion = '::' + question.Name + '::' + beforeSubstring  +'{'+ matchedAnswersString+ getCorrectAnswer(question) +'}'+ afterSubstring ;
        allFormattedQuestions.add(formattedQuestion);
    }
  /*------------------------------ Fill in the Blank Question--------------------------------------------------*/
    public void formatShortAnswerQuestionMW(Exam_Question__c question, String beforeSubstring, String afterSubstring){
        List <String> correctAnswers = new List <String> ();
        List <String> formattedCorrectAnswers = new List <String>();
		correctAnswers = question.Correct_Answer_s__c.split('\\|\\|');
        for (String correctAnswer : correctAnswers){
           formattedCorrectAnswers.add('='+correctAnswer);
        }
        String correctAnswersString = string.join(formattedCorrectAnswers, '');
        formattedQuestion = '::' + question.Name + '::' + beforeSubstring + '{'+ correctAnswersString +getCorrectAnswer(question)+ '}' + afterSubstring;
        allFormattedQuestions.add(formattedQuestion);
    }
     /*------------------------------ Numerical Question --------------------------------------------------*/
    public void formatNumericalQuestion(Exam_Question__c question){
        formattedQuestion = '::' + question.Name + '::'+question.Question_Text__c + '{#' + question.Correct_Answer_s__c + ':0'+getCorrectAnswer(question)+'}';
        allFormattedQuestions.add(formattedQuestion);
    }
    public void formatNumericalQuestionMW(Exam_Question__c question, String beforeSubstring, String afterSubstring){
        formattedQuestion = '::' + question.Name + '::'+ beforeSubstring + '{#' + question.Correct_Answer_s__c + ':0' +getCorrectAnswer(question)+'}' + afterSubstring;
        allFormattedQuestions.add(formattedQuestion);
    }
    
   /*------------------------------ Short Answer Question --------------------------------------------------*/
    public void formatShortAnswerQuestion(Exam_Question__c question){
        List <String> correctAnswers = new List<String>();
        List <String> formattedCorrectAnswers = new List <String>();
        correctAnswers = question.Correct_Answer_s__c.split('\\|\\|');
          for (String correctAnswer : correctAnswers){
           formattedCorrectAnswers.add('='+correctAnswer);
        }
        String correctAnswersString = string.join(formattedCorrectAnswers, '');
        formattedQuestion = '::' + question.Name + '::'+question.Question_Text__c + '{'+ correctAnswersString+ getCorrectAnswer(question) +'}';
        allFormattedQuestions.add(formattedQuestion);
    }
  /*------------------------------ Essay Question --------------------------------------------------*/
    public void formatEssayQuestion(Exam_Question__c question){
        formattedQuestion='::' + question.Name + '::' + question.Question_Text__c+'{}';
        allFormattedQuestions.add(formattedQuestion);
    }
    public void formatEssayQuestionMW(Exam_Question__c question, String beforeSubstring, String afterSubstring){
        formattedQuestion='::' + question.Name + '::' + beforeSubstring+'{}'+afterSubstring;
        allFormattedQuestions.add(formattedQuestion);
    }
  /*------------------------------ Join List to String--------------------------------------------------*/    
    public void formatQuestions(List <String> questions){ 
    	allFormattedQuestionsString = string.join(questions, '\r\n\r\n');
    }
    public String getCorrectAnswer(Exam_Question__c question){
        String res = '';
        if(question.Answer_Explanation__c != null){
            res= '#'+question.Answer_Explanation__c;
        }
        return res;
    }
    
}