TrialoftheTitansPackage/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Projects listed in the Portfolio.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/Roles_Responsibilities__c.field-meta.xml
<CustomField>
    <fullName>Roles_Responsibilities__c</fullName>
    <label>Roles and Responsibilities</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/Technologies__c.field-meta.xml
<CustomField>
    <fullName>Technologies__c</fullName>
    <label>Technologies</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

P3/force-app/main/default/classes/PortfolioProjectControllerTest.cls
@isTest
public class PortfolioProjectControllerTest {
    

    
    @isTest
    static void positiveTests(){
        List<Project__c> projects = new List<Project__c>();
        Id testId = UserInfo.getUserId();
        
        Project__c a = new Project__c(Name='test project', Description__c='test description', 
                                      Roles_Responsibilities__c='test roles', Technologies__c='test tech',
                                      User__c=testId);

        
        projects.add(a);
        
        
        insert projects;
        
        List<Project__c> testget = new List<Project__c>();
        String testupsert = '';
        
        Test.startTest();
        testget = PortfolioProjectController.getProjects(testId);
        testupsert = PortfolioProjectController.createProject(a, false);
        Test.stopTest();
        
        System.assertEquals(1, testget.size());
        System.assertEquals(18, testupsert.length());
        
    }
    
    @isTest
    static void bulkTests(){
        List<Project__c> projects = new List<Project__c>();
        Id testId = UserInfo.getUserId();
        
        for(Integer i = 0; i < 200; i++){
        	Project__c b = new Project__c(Name='test project' + i, Description__c='test description', 
                                      Roles_Responsibilities__c='test roles', Technologies__c='test tech',
                                      User__c=testId);
            projects.add(b);
        }
        
        insert projects;
        
        List<Project__c> testget = new List<Project__c>();
        String testupsert = '';
        
        Test.startTest();
        testget = PortfolioProjectController.getProjects(testId);
        testupsert = PortfolioProjectController.createProject(projects[0], false);
        Test.stopTest();
        
        System.assertEquals(200, testget.size());
        System.assertEquals(18, testupsert.length());
  
    }

}