TrialoftheTitansPackage/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Projects listed in the Portfolio.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Project__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

PortfolioPackage/main/default/objects/Responsibility__c/Responsibility__c.object-meta.xml
<CustomObject>
    <description>Holds the responsibilities for a user&apos;s project and relate to skills</description>
    <label>Responsibility</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Responsibilities Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsibilities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PortfolioPackage/main/default/objects/Responsibility__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Responsibilities</relationshipLabel>
    <relationshipName>Responsibilities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PortfolioPackage/main/default/classes/ResponsibilitiesController.cls
public without sharing class ResponsibilitiesController{

  //method that returns a list of all responsibilities related to a project
  @AuraEnabled (cacheable=true) 
  public static List<Responsibility__c> getResponsibilities(Id projectID) {
    //query to get ALL responsibilities related to the logged in user
    return [SELECT Description__c FROM Responsibility__c
            WHERE Project__r.Id = :projectId];
  }
}