TrialoftheTitansPackage/main/default/objects/Account/recordTypes/Hero.recordType-meta.xml
<RecordType>
    <fullName>Hero</fullName>
    <active>true</active>
    <description>The record type for the Hero Account</description>
    <label>Hero</label>
</RecordType>

TrialoftheTitansPackage/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <description>Assessment object for 1-on-1s, projects, and misc.</description>
    <label>Assessment</label>
    <nameField>
        <label>Assessments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assessments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

TrainerHubPackage/main/default/objects/Hero_Assessment__c/Hero_Assessment__c.object-meta.xml
<CustomObject>
    <label>Hero Assessment</label>
    <nameField>
        <displayFormat>HA-{0000}</displayFormat>
        <label>Hero Assessment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hero Assessments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

TrialoftheTitansPackage/main/default/objects/Hero_Assessment__c/fields/Assessment__c.field-meta.xml
<CustomField>
    <fullName>Assessment__c</fullName>
    <description>Relating Hero Assessment to Assessment</description>
    <label>Assessment</label>
    <referenceTo>Assessment__c</referenceTo>
    <relationshipLabel>Hero Assessments</relationshipLabel>
    <relationshipName>Hero_Assessments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrainerHubPackage/main/default/objects/Hero_Assessment__c/fields/Hero__c.field-meta.xml
<CustomField>
    <fullName>Hero__c</fullName>
    <label>Hero</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hero Assessments</relationshipLabel>
    <relationshipName>Hero_Assessments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

TrialoftheTitansPackage/main/default/objects/Hero_Assessment__c/fields/Overall_Score__c.field-meta.xml
<CustomField>
    <fullName>Overall_Score__c</fullName>
    <description>Score for assessment.</description>
    <label>Overall Score</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

TrainerHubPackage/main/default/classes/HeroAssessmentListController.cls
////////////////////////////////////////////////////
//
//  Name: Hero Assessment Apex Controller
//  Author: Josue Cisneros
//  Description: Controller for Hero Assessment List
//               Component to be able disply data 
//               from org on the component
//
////////////////////////////////////////////////////

public with sharing class HeroAssessmentListController {
    @AuraEnabled
    public static List<Hero_Assessment__c> HeroList() {
        List<Hero_Assessment__c> heroAssessmentSearch = [SELECT Assessment__r.Name, Overall_Score__c,
                                                         Hero__r.Name
                                                         FROM Hero_Assessment__c];
        return heroAssessmentSearch;
    }

    @AuraEnabled
    public static List<Hero_Assessment__c> SearchHeroList(String searchKey) {
        String name =  + searchKey + '%';
        List<Hero_Assessment__c> heroAssessmentSearch = [SELECT Assessment__r.Name, Overall_Score__c,
                                                         Hero__r.Name
                                                         FROM Hero_Assessment__c
                                                         WHERE Hero__r.Name
                                                         LIKE :name];
        return heroAssessmentSearch;
    }
}